### ISSUE TITLE
Super GameBoy PlugIn,Turn scrolling off in Main-Menu,Fixing C8-Error

### ISSUE THREAD

**Issue by NDpendent** [ClusterM/hakchi2#1002]
I got 3 things,i would love to see.I got 100 SNES-Games in a Folder,i have to quit the folder to not get the C8-Error.Maybe assign a Button to go back to main menue,to not scroll the entire games to reach back-folder and/or fix that C8-Error.Tried to change the max-rom-settings in .cfg-file in hakchi2 folder to 99,but dosnt work.
Second thing would be really nice!If retroarch emulates GameBoy Roms,automaticly to add the Super Gameboy Menue to change the 4 Colors etc.
Third thing,i made 3 Folders for each Konsoletype,SNES,GBA and GameBoy,and the Folders jumpin arround if i choose.Would be great to stop the scrolling in Main Menue if there are max 4 Folders...
If someone knows,how to do,please responde...

**Comment by Drakonas** [comment]
Did you not see the "Not Recommended" in the menu when setting the folder limitation past 45? Having more than 60 games causes crashes when having too many games in a folder, but more than 45 cuts off the thumbnails. Lag with more than 60 games is a hardware limitation and cannot be fixed. Retroarch does emulate GameBoy roms if you install the gambette retroarch core module if you didn't notice. Super Gameboy most likely will never be supported though, and that is not something to do with Hakchi. We don't make the cores. For your third question, that is a limitation of the SNES Classic system if you have less than 12 items in a menu. Organize your stuff better. This cannot be fixed.

**Comment by ghost** [comment]
Drakonas you sound pretty harsh. especially saying "This cannot be fixed". I know that it might be no priority but to simply say "NO." is just stupid.

**Comment by JeffSeverino** [comment]
It's not about priority. He's just stating facts @Vogeluff. You guys have to learn about the limits of the project before requesting things that are just plain impossible, and still whine about it. There are already a lot of solutions out there, Why not adapt yourself?

**Comment by ghost** [comment]
damn you dont have to be an asshole. thats basically what i eanted drakonas to know. plus its stupid to claim something is impossible. people said running terranigma on canoe would never be possible aswell and now its running just fine. Requesting features is the right place to request a feature. its not a case of "whining" or demanding it, its just making sure its heard that that is wanted.

**Comment by JeffSeverino** [comment]
Now you are being a little too salty, as no one is offending you. If a ROM works now it doesn't mean everything is possible. 
Don't you think that all the limitations listed within hackchi were not tested? If hackchi was released this way (with its limitations) wouldn't be logical that these issues weren't noticed before? The OP is just stating obvious problems that you have to adapt yourself if you want to use it. OF COURSE if it is possible in the future ClusterM will do something about it. Before being so defensive about it, read the FAQ, try to understand why some things are still a problem, see other issues, etc.

**Comment by ghost** [comment]
i dont see why we are arguing. we are both stating that it could be possible in the future that certain things might change and then work. i just claimed that its a good thing people post as request what they'd like to see hakchi do. it's not a demand. it comes down to making your voice heard about what you'd like, not even necessarily what u need.
I just found that Drakonas sounded very aggressive and not helpful. Plus I think he has a different understanding of what requesting is meant for and means. I apologize if I sounded salty, it just really annoyed me how he especially responded. Reminded me of the people that just scream "JUST USE RETROARCH?!" if you voice that a certain game isnt working with canoe. have a nice day anyways!

**Comment by JeffSeverino** [comment]
I now seem to understand you a little bit. Everyone wants this hack to be the best possible. But for now would be nice to not fill the issue board with things that are not as important, and prioritize issues like the overheating bug, which is kinda serious. Even if ClusterM is doing all this as a hobby, we can help him by filtering what really is a problem at the moment and what isn't. Everyday somebody posts something about roms, about retroarch (even with ClusterM is doing his thing there too), and even asking where to download shit. You know what I'm saying? All this is because people (not including you, just mentioning) don't read the FAQs, don't research and so on. Have a nice day too :)

**Comment by Drakonas** [comment]
@Vogeluff I was not trying to sound harsh, neither am I in this message. I am just trying to be blunt. I was emphasizing that fixing rom compatibility is one thing. Increasing performance is another. C8 errors usually occur when the SNES Classic works too hard and hits limits. Be aware that Terranigma was not Cluster's doing. That was someone else actually modifying the rom code, not Hakchi code, so the official Terranigma rom does not run still. Regardless if rom compaibility can be fixed by ClusterM, making a hardware processor move faster or increasing the amount of memory on the SNES Classic with an update *IS* impossible. That is basically what would be required to show that many games at one time. It is not physically possible to fix that with software. If it was even possible, you'd have to open up your SNES Classic and know how to manually overclock the CPU from, or add memory to, the board, which is too risky to be fathomable. So yes, what you're asking with showing more games without errors *IS* impossible. You either limit the amount of games in one folder, or you will get C8 errors. Simple as that. Closing this as there is nothing in the OP that can really be addressed by Hakchi.
