### ISSUE TITLE
Hakchi2 doesnt add .7z after rom_name.sfrom in the .desktop file immediately!

### ISSUE THREAD

**Issue by bslenul** [ClusterM/hakchi2#1022]
Hey!

I was going crazy the other day: someone told me that Panel de Pon was working with Canoe but I got a C7 error, I tried again later and it worked, with the same rom... Oo

Yesterday I wanted to try the N64 emulation and same thing happened with Super Mario 64, rom didnt work then I re-uploaded it later and it worked by magic...

Looks like hakchi2 doesnt add the .7z extension after rom_name.sfrom in the .desktop file immediately: https://youtu.be/1nlRQ-rVhKY

The changes are made only after closing hakchi2 or by "forcing" it by unchecking and re-checking the "Compress" option for example.

I think the changes are also made when clicking the "Sync games" button so that's OK for most people I guess, but if you add your games manually with FTP like me (because I don't want to redo [this](https://www.reddit.com/r/miniSNESmods/comments/7b5v8p/quick_example_of_what_you_could_do_with_folders/dpfjfh4/) every time :D), don't forget to restart hakchi before!

**Comment by Drakonas** [comment]
Have you created a new folder for Hakchi any time since 2.20? I notice the dates of your folders haven't changed for a while. Upgrades to Hakchi usually require making a new folder for the new version, and moving the config, dump, games_snes, and user_mods folders to the new folder.

Also, be aware if you used versions prior to 2.21b (especially if you used the 2.20 build) you need to erase the config folder and start with a fresh config (all games will be there but will need to be rechecked) You will then need to backup your saves with the Hakchi save state manager, perform an uninstall from the Kernel -> Uninstall function, flash og kernel, perform a complete factory reset from your SNES Classic main menu after that to remove residual files from bad/old Hakchi installs (this is mandatory and will erase all saves, but may also free up a lot of space on your SNES Mini), then flash custom kernel again and install mods if you want them (and restore saves if you need to).

The reason I say this is if you never got the popup at any time using Hakchi of what console you are using (NES Mini/SNES Mini) 2.20 was defaulting to NES Mini, and later builds split it but if you didn't delete the config during the upgrade it would continue to think you're using an NES Mini.

**Comment by bslenul** [comment]
To clarify: I'm french so the dates are in DD/MM/YYYY format. When I upgrade I overwrite directly with the new version of hakchi so every older files are replaced. I think my last fresh install is from 2.21b. And I'm in SNES mode from the 1st start (I got the prompt).

But I just tried **on a fresh 2.21f install** to be sure: https://youtu.be/lKPvY0PYzCg

As you can see, same problem, in the .desktop file of the game the .7z extension isnt there immediately, it only appears when you close hakchi or when you click the "Sync your games" button or when you uncheck/re-check the "Compress" option (like I did in the video, you can see notepad++ detecting the change and asking to reload the file).

It's not a huge problem since I imagine 99% of the users upload their games with the sync button but I wanted to report the issue anyway.
