### ISSUE TITLE
[Reqest] A place for tips, hints, moves and useful information

### ISSUE THREAD

**Issue by erroneus0** [ClusterM/hakchi2#1029]
Like to many others, I'm interested in building a really polished configuration.  A good number of quality games and the information to play them.  It's nice when games have the moves already within the game itself, but that's not common in games where smaller amounts of memory is a limiting factor back in the day.  But we do have the "legal notices" are and the like which we might be able to play with.  Being able to update those areas with useful things can really be helpful as I share this with my little boy.  Fighting games have complex moves and that's a part of developing the skill.  But reference data would be nice if it were contained in the game system itself.  Obviously, I would expect to create the reference data myself (can pictures be added or only text?) but having the means of adding that information in Hakchi2 would be great!

**Comment by Drakonas** [comment]
@erroneus0 the legal notices were able to be modified because the user interface for that page was already in the SNES and ClusterM just modified the text. Hakchi can't actually add entirely new UI elements without risking large amounts of crashes. I'm sorry, but what you're asking for is not possible.
