### ISSUE TITLE
Music hack isn't working

### ISSUE THREAD

**Issue by brothan323** [ClusterM/hakchi2#1033]
Hello. Installing the music hack just removes the music from the main menu. Replacing it with any wav file doesn't help, just removing the music_hack.hmod solves the problem.

**Comment by Frank-5** [comment]
If you use the .wav file included with the hmod then it will just remove the factory music.  This behavior is intentional.   The format for the replacement wav file, as I understand from the FAQ and other areas I've looked, is PCM and it has to be at least a minute.  What is not clear, at least as far as I've researched, Is the PCM format. There are many different formats.  8bit, 16bit, 16bit little endian, 16 bit Big endian, etc.   nowhere that I've seen discusses the proper format.  I've watched YouTube tutorials, read the Reddit forums, and nothing is specifically mentioned, other than on one tutorial the person is using 8 bit (yuck). 
 I, like you tried the music hack, and successfully removed the music, but when I have tried 16 bit little endian (and big ensign) PCM at 44100Hz sample rate for 60 seconds ( or more) it usually causes a C7 error and what's worse I  end up having to completely start over because it black screens my system.   So... What would be nice here is some clarification from whomever wishes to provide a little illumination on this.

**Comment by Frank-5** [comment]
Edit:  endian. Not ensign 

Also would be nice to have a couple sample files to use.  Nothing copyrighted,  just some simple wav files as examples, other than the blank one

**Comment by Frank-5** [comment]
This isn't really an issue with Hakchi I don't think , so this discussion should be somewhere else like Reddit, etc.  (it just would be nice to have one tiny little sentence added to the read me file in this Hmod that clarifies what to use.)

**Comment by brothan323** [comment]
AHHHH. My music file was 54 seconds, so that's why. 

It would have been awesome if cluster put this info inside themusic_hack readme.

**Comment by Frank-5** [comment]
Yup, I agree. Would be nice to have one sentence added in the read me that explains all this. Let me know if you get it working and what PCM format you used!  Thanks!

**Comment by brothan323** [comment]
Yea. This hack still doesn't work. I have a wav file longer than 1minute yet the main menu still doesn't have music. WHat the hell is going on?

**Comment by brothan323** [comment]
The file is 16-bit signed pcm wav file.
