### ISSUE TITLE
Deleted Earlier Hakchi Folder

### ISSUE THREAD

**Issue by ghost** [ClusterM/hakchi2#1041]
Is there anyway to "download" the previous hakchi settings, games, and folder images from a NES classic unit if the original hackchi folder is no longer on a computer?

**Comment by bslenul** [comment]
You should be able to recover the games and boxarts with FTP.
On SNESC the games are in /usr/share/games but I don't know if it's the same on NESC, look for CLV-* folders. If the letters are the same as SNESC, CLV-H-* should be NES games, A for GBA, B for GB, C for GBC, G for Genesis, etc. (CLV-S-* are folders, since you want the folder images too),
And just download them in \hakchi2\games folder on your PC.

If you don't know how to FTP, I made a tutorial for someone on Reddit (keep in mind it was for SNESC, could be a bit different, idk): https://www.reddit.com/r/miniSNESmods/comments/7as9kr/purchased_a_already_modded_snes_questions/dpdg9y7/

**Comment by ghost** [comment]
You're awesome, thanks!
