### ISSUE TITLE
Problem loading games

### ISSUE THREAD

**Issue by kwise1** [ClusterM/hakchi2#1042]
I loaded games (about 300). The original work fine.  The loaded ones appear, but when I try to load one, I go right back to the game selection screen.

The controller hack works.
I used the same procedures (followed instructions on the screen) as when I loaded NES classic.

Any ideas?

**Comment by bslenul** [comment]
Maybe your roms extension? Few weeks ago I had the same problem with 2 or 3 roms, I didnt pay attention but the roms were in .fig format, I just replaced the extension by .smc then add the roms again in hakchi and this time it worked perfectly!

**Comment by kwise1** [comment]
I will give it a try.  Thanks.

**Comment by Drakonas** [comment]
The SNES Classic has less space than the NES Classic. You're probably using up too much space. How much free space is left on the system as reported by Hakchi?

**Comment by Shoothimnow** [comment]
On top of the SNES Classic having less space than the NES Classic (due to the default games being larger in size), the rewind function in the save states make save states HUGE in size.  If you put 300 games on your console, you will most likely not be able to use any sort of save state function.

As per #513, even if a game is 0.5MB in size, the save state can surpass 3.0MB in size.

**Comment by Shoothimnow** [comment]
@kwise1, any update on this.  Does this issue still need to be opened? can we **_close this ticket_**?

**Comment by Drakonas** [comment]
I am just going to close this as it has been 22 days since a response. I will reopen if necessary.
