### ISSUE TITLE
resizing of box art can give an odd value height and snes mini displays corrupted pixels on the last line

### ISSUE THREAD

**Issue by daPhie79** [ClusterM/hakchi2#1049]
when i add 2d snes box art that i got from emumovies, which i've found to be high quality, hakchi2 resizes automatically from 680x500 to 228x167. now normally this shouldn't be a problem, but the snes mini doesn't seem to like an odd value for image height, because the last line of the image is corrupted. i have a european version.

**Comment by ghost** [comment]
i found that its easiest to just use a bulk-resizing website like https://bulkresizephotos.com/ to do it "manually" instead of letting hakchi do it. choose exact size and enter what u want to use. i use png + black instead of transparent background and "no padding" in the "pro settings" but of course you can play with them.

**Comment by Drakonas** [comment]
@daPhie79 are you sure it's not the image just having a white line on one of the sides (which is common)? What do you mean "corrupted"?

**Comment by ghost** [comment]
@Drakonas if you look closely you can see the background through a narrow 1px gap that can occur when resizing with hakchi. atleast thats the bug i had.

**Comment by daPhie79** [comment]
@Vogeluff @Drakonas that's exactly it. last line of the picture in the bottom. not vertical lines on either side, but the last horizontal line. i haven't tested if a picture resized outside of hakchi with an odd height value would do the same thing, but i know that it does it when resized in hakchi2. not the end of the world, but definitely there.
