### ISSUE TITLE
[SNES Mini] SNES Mini not recognized by Windows anymore

### ISSUE THREAD

**Issue by daftpvnk3r** [ClusterM/hakchi2#1052]
Hello guys,

My SNES Mini is no more recognized by my workstation with Windows 10. 

I was able to:
-dump the kernel
-flash the kernel
-add a game (Turtles in Time)
-and play the game

I then wanted to add more games but when I was about to synchronize the SNES mini, hakchi2 prompted the message: 1 connect your snes via usb. 2. power it up 3. install driver

I was confused because I already installed the driver. I checked the Device Manager and it wasn't marked as "active". It was a hidden device, indicating that is not connected.
I deleted the "dead" entry and plugged SNES again-->still not recognized.

So I googled and tried (only USB-cable is connected):

- using different USB-ports -->**no changes**
- using different USB cables on different USB-ports -->**no changes**
- plugged it on a notebook with Windows 10  --> **no changes**

- -plugged it on a notebook with Windows 7 --> it was recognized as **"VMware USB Device"** and there was a yellow triangle and an exclamation mark, indicating that it is not really working.

So I downloaded Zadig 2.3, selected "VMware USB Device" and clicked on "Replace Driver" to install WinUSB (v6.1.7600.16385) --> it aborts the installation and says "FAILED. Resource already exists"
I am only able to install WCID Driver but nothing changes.

So I deleted the driver of "VMware USB Device" within the Device Manager and then it became an **"Unknown Device"** with a yellow triangle and exclamation mark. Same thing with Zadig here too:
cannot install WinUSB but able to insall WCID.

At this point, I'm out of ideas. It tried another notebook with Windows 7--> same thing as my Windows 10. I also tried it with VirtualBox+ExtensionPack+USB2. Virutal Box doesn't even see "VMware USB Device" or "Unknown Device"...

I am kind of frustrated. I regret that I did not add all my favorite games at the first try....
Please help me :((

**Comment by daftpvnk3r** [comment]
What really confuses me is, that my PC is not showing SNES as a device anymore. I still can connect USB drives or my android smartphone but SNES mini just wont be "seen" by windows.

I can power SNES mini by using the same ports on my Windows 10 PC.

**Comment by ghost** [comment]
Somewhere in your story I don't see you pressing and holding the reset button while switching the power-on button. You will need to do that and your system will detect it again, at least when you uninstall the driver completely and then reinstall it. Then using Hakchi install the original kernel again and then sync games and Hakchi will guide you through the process.

I also had the problem that at some point my Windows 10 station did not detect the device anymore, but dont worry, its almost impossible to break it, so booting up in fel mode (holding reset button and then flip power switch but keep on holding the reset button until you hear a sound in windows. Then you can release the reset button).
Also note that you should read very carefully when Hakchi asks you to power on the device. Only use the reset button (booting in fel) if it asks you.

Uninstalling the driver might also be a process of uninstalling it a couple of times (make sure you delete all driver fragments using the Zadig instructions, or from some googling results).
Good luck!

**Comment by daftpvnk3r** [comment]
@bewilderedthetan 
Thank you for your reply. 

I am always doing the "press reset, switch power one"-thing.
It is the only way the notebook with Windows 7 can see the SNES as a "VMware USB Device"

But when I try it on my Windows 10 PC (where I initially flashed SNES mini), it is not showing up in Device Manager. I do not hear the sound when I press reset and switch power on.

**Comment by ghost** [comment]
Hmm ok, well I hope someone else out there has some idea, because unfortunately I am out of ideas.
The thing is that I had this issue too, device not being recognized anymore and somehow I got it working again and I know it has to do with thoroughly uninstalling the driver AND the driver files (very, very important to also delete those).
That it's recognized as a vmware thingy I find strange, so you do have vmware installed? I am feeling in the dark here, but that might also be a showstopper in the sense that its possible that vmware has created some pseudo usb bridges that might fuck things up. But, thats only an idea, i might be completely wrong.

As for the reset button: after Hakchi has installed the custom kernel on your device, you should not boot it holding the reset button by the way, that does not work, that it only needed to install mods and games and Hakchi will tell you when to use the reset button, so really only use it if Hakchi tells you.

I hope someone can help you.

**Comment by daftpvnk3r** [comment]
I have installed VMware Workstation 8 a few years ago on both machines (Windows 10 PC and Windows 7 notebook).
Maybe thats the reason why it fails. I am trying to get a clean install of Windows 7 and try again.

Would you please explain how you were able to completely uninstalling the driver and driver files.

**Comment by ghost** [comment]
Ah a clean install should definitely do the trick.
Well, it has to appear in devicemanager and then when uninstalling the driver you have to tick the box that says you also want to delete the driver files, but I have the idea you already did that.

**Comment by ghost** [comment]
And beware of virusscanners, they can also be quite annoying

**Comment by daftpvnk3r** [comment]
Yep, I already have ticked the box where it said to delete software/files. 
I thought you meant something more like via command line or another tool....

**Comment by ghost** [comment]
Aaaah nope I also dont know of another way.

**Comment by ghost** [comment]
Oh btw, you must uninstall drivers for any usb port you might have connected the device to! And sometimes you have to uninstall a couple of times, as the previous driver will be installed if you uninstall drivers, so repeat that until there are no more drivers left for the device. I remembered all of a sudden I had to do that.

**Comment by ghost** [comment]
And try to rescan for new hardware in devicemanager after you uninstalled the drivers (without usb unplug!!) and keep on uninstalling drivers until it is detected as an unknown device (should definitely not be detected as a vmware... device).

**Comment by daftpvnk3r** [comment]
I think, I'm going with a clean installation of Windows tomorrow.

**Comment by ReyVGM** [comment]
OP, you overcomplicated things for you.

First of all, were you using the original USB cable that came with the system? Using a different one (even the NES Classic one) will cause issues. Also, you need to plug the cable on the same USB slot you used the first time, if you don't, then the drivers will not be installed for the other slot. And it has to be USB 2.0, not 3.0

If you did do all of the above, when hakchi gives you that message to hold reset and power on and at the end it asks to install the driver, all you have to do is the hold reset method, do not click on install the driver. That message appears there regardless if you installed it or not. The mistake you made was to manually uninstall the driver or whatever it was you deleted.

**Comment by ghost** [comment]
Just one last thing to try - this is weird, but hear me out - I had issues with my PC recognizing my NESC, I found out if I apply slight pressure to the mini USB connection on the back of the console, my PC would sound the "device connect/device disconnect" tone. Eventually, Hakchi2 recognized my console was connected, and I could flash the custom kernel.

This has worked for others, so it may be worth trying.

https://imgur.com/srbdDmU

**Comment by daftpvnk3r** [comment]
@ReyVGM 
I didn't use the original cable which came with SNES Mini. Of course, I tried it with the same port but my windows 10 just won't see it. Maybe I really should not have deleted the driver which was installed at the first try.

@maskedmaniac 
I also thought that this is the reason why windows is not seeing SNES mini. I applied a bit more pressure just like it is shown in the picture but nothing happens.

I will do a little more research when I'm back at home in a few hours.
Thank you so far.

**Comment by ReyVGM** [comment]
Not using the original cable is the problem. Always use the original cable.

**Comment by daftpvnk3r** [comment]
@ReyVGM 
While researching for ideas, some guys wrote that they were only able to flash SNES with another cable.
Using the original one did not help.

I had the same issue. I was not able to flash SNES with the original one.

**Comment by daftpvnk3r** [comment]
I've installed Windows 7 on a notebook and plugged the SNES on a port--> Windows is not recognizing SNES (tried all cables I had including the original one)

I've switched back to my notebook with Windows 7 which is somehow capable of "seeing" SNES as an unknown device, yet with the failure code 43.
I deleted the driver again and this time I was able to install the NES Mini driver manually by doing this:

- I had a list of all devices

- selected Universal Serial Bus device

- I could choos between Undefined Vendor, Nintendo and VMware

- I chose Nintendo and installed NES Mini driver.

Now it shows me the SNES as a NES Mini with failure code 10 indicating that the device is not able to start.

I'm going to find out what I can do with this failure code.

**Comment by daftpvnk3r** [comment]
No improvement so far.
I am going to give it a try with tower-PCs in my office....
If these PCs wont show the SNES then I am going to give up.

**Comment by daftpvnk3r** [comment]
I won't be able to try any further so I give up.
I somehow made my SNES Mini undetectable as a device in Windows.

Just for info:
This SNES is a **MOD.CLV-301** with Barcode **2017 SEE100816624**

**Comment by pakodx** [comment]
connect snes, install drivers, etc etc
it won't recognize it, so you have to force it
get the latest hakchi2 CE,
then go to>
modules
install extra modules
and install something, even if you already have it
that will force hakchi to admit your snes is connected and work properly
It's been more than half a year since you asked, so i hope you found that out by yourself by now.
you did nothing wrong, its a hakchi glitch

**Comment by rmstorms** [comment]
@Pakodx

Thank you! I just got a NESC today and hacked it. Then decided to add more games and couldn't get my pc to recognize my NESC again. I came across this thread searching for a solution and your method worked 100%! Thanks a bunch!

**Comment by mikaheino** [comment]
Thank you very much! The install extra modules tip worked for me

**Comment by jomalova** [comment]
hello Pacodx and daftpvnk3r your soultion did not work for me you are not being very clear with your instructions, 

should I connect the snes mini in on mode or fel mode?RE; because I tried both and none of them worked the mini is still recognize as a unknown device

open hakchi, install drivers, how am I suppose to install drivers if the mini isn't even recognized, even when I tried to install drives using zagig or windows itself the installation fail, if I try to install it manually a message always pop up saying that the best drivers for the mini are already installed
it won't recognize it, so you have to force it to
get the latest hakchi2 CE, Re; it wont installed hackchi ce if the mini isnt recognize, there is no way to force it to do that, even with the newest hackchi release
then go to>
modules
install extra modules Re; cant install extra modules the mini is not recognize 

and install something, even if you already have it
that will force hakchi to admit your snes is connected and work properlyRE: this is all wrong there is no way to force hackchi into recognize the mini unless it was property detected since the beggining
It's been more than half a year since you asked, so i hope you found that out by yourself by now.
you did nothing wrong, its a hakchi glitchRE: is not a hackchi glitch is a hardware issue, if you have a solution for that I would really apreciate a reply for that

thank you

**Comment by jomalova** [comment]
> connect snes, open hakchi, install drivers, etc etc
> it won't recognize it, so you have to force it to
> get the latest hakchi2 CE,
> then go to>
> modules
> install extra modules
> and install something, even if you already have it
> that will force hakchi to admit your snes is connected and work properly
> It's been more than half a year since you asked, so i hope you found that out by yourself by now.
> you did nothing wrong, its a hakchi glitch

hello Pacodx and daftpvnk3r your soultion did not work for me you are not being very clear with your instructions,

connect snes in on mode or fel mode?, open hakchi, install drivers, how am I suppose to install the drivers if the mini isnt even recognized etc etc
it won't recognize it, so you have to force it to
get the latest hakchi2 CE, Re; it wont installed hackchi ce if the mini isnt recognize
then go to>
modules
install extra modulesRe; cant install extra modules the mini is not recognize
and install something, even if you already have it
that will force hakchi to admit your snes is connected and work properly
It's been more than half a year since you asked, so i hope you found that out by yourself by now.
you did nothing wrong, its a hakchi glitch

**Comment by Mazgazine1** [comment]
ITS FIXED!!!!

USB 3.0 ports don't work!!!!!!

Use a USB 2.0 or lower! Keyboard/mouse legacy port on Motherboard works!!!!

******************************************************************************************************

Is there something in windows that just fundamentally blocks this program?!??!

My own post - reposting here since its been years for anyone and no solution - its my exact same issue.

https://old.reddit.com/r/miniSNESmods/comments/1h3ewx6/1_week_after_being_able_to_access_the_snes_fine/

I now can't see the SNES mini AT ALL, install drivers from Zadig, hold reset plug in, remove reinstall devices, firewall off, firewall not block, no AV, nothing changed other then windows as far as i know, same cables, same port etc.

Was going to help a friend and his SNES mini also couldn't be seen by either PC... (took his snes mini to my place to clone mine since before today it was working fine).

its also not showing as a DLYS and just "classic" as the device.

So its more then one mini, yes they are original and they haven't been bricked yet, the "install kernel option" DOES get somewhere, I can plug the HDMI in and see the Hakchi splash screen but Hakchi stopped being able to interface with the SNES after the first reboot it does when doing install/repair.

So yeah, is it really this temperamental or is there some update that is preventing access?

Its really weird, that I can't connect to either snes mini..

Hakchi2-ce 3.9.3 software Win10

tried a 3rd PC, same issue -

installs the DLY-SC or whatever driver fine.. Hakchi cant see the SNES anymore. EDIT 12/3/2024 Tried on laptop with win10 22H2 so older update, and same thing.. disabled all security / also tried giving hakchi full internet access and nothing..

I have NO security software outside of windows defender on the PCs I use.. sooo is there some option/checkbox/setting I need to find to get it to see the snes mini...

Running as admin had no change.

I have attempted using debug mode and it stops at the mini FTP stage. Likely something is blocked from connect the mini FTP program or the SNES mini side is not allowed to see it..

Please note, the same cable used to load roms, is one of the tested cables - Hakchi  just sits off-line no matter what.
