### ISSUE TITLE
Quick save bug to one game

### ISSUE THREAD

**Issue by larlyches** [ClusterM/hakchi2#1062]
Hello,
I’m french, sorry for my english.
Only quick save it’s ok but for cadash (pc engine) quick save bug sometimes.
I push reset to save and when i want load this save : black screen.
Thanks a lot

**Comment by Drakonas** [comment]
Cadash (U) from Goodset doesn't work with Mednafen. People on the internet report you need to use Cadash (USA) instead for Mednafen. Find it online. GoodSet roms have problems. However, Cadash may not be supported by ClusterM's Mednafen, because is is an older build of mednafen (newer Mednafen runs too slow).

**Comment by larlyches** [comment]
Thanks to answer
I use cadash japan because cadash usa doesn’t work.)67

**Comment by larlyches** [comment]
Thanks with cadash USA, it's perfect ...
