### ISSUE TITLE
Waiting for NES/SNES

### ISSUE THREAD

**Issue by skadizzle** [ClusterM/hakchi2#1065]
I know I'm not the first person to post this, but the other thread was closed. I can load up Hakchi, and put games in it, but can't get past the waiting for NES/SNES screen. I believe I installed the drivers correctly. I got the black screen, it installed, i hit enter.  When I plug it in and do the reset, it shows unknown device in the device manager. If I plug it in and turn it on, it shows as CLV-S-SNSY which I assume is the SNES name. I have tried all my USB ports, and I am on Windows 10, which someone else had the problem they were on XP. I don't know what I'm missing. I can't dump the kernel because I can't get past that screen. Tried watching YouTube videos, but no luck. Any help would be great. I'm going to try another computer since it seems that has been the problem for some as well.

**Comment by Drakonas** [comment]
I closed the original thread because it was not a Hakchi bug, but an incompatibility with USB ports due to newer ports not liking the driver, or not using the original cable that came with the SNES/NES Classic. Try using different ports or a different computer or using the cable it came with. Past that, please ask this kind of question on the MiniSNESMods subreddit. This is a bug report tracker, not a personal help line.

**Comment by Shoothimnow** [comment]
https://www.reddit.com/r/miniSNESmods/
