### ISSUE TITLE
NES Classic - Any added games will not run

### ISSUE THREAD

**Issue by skuskowski** [ClusterM/hakchi2#1068]
I just got my hands on a NES Classic, I added about 300 NES roms as .zips.  The NES has plenty of storage and I'm using less than 30 games on any one page (the rest are in folders).  I didn't change any settings in Hakchi 2 and all of the original games work. 

I also tested the roms on my computer and they do work there.

Any ideas?

**Comment by ReyVGM** [comment]
Open the zips, there should only be the .nes file inside and nothing else. If there's something else, you need to delete it.

**Comment by ghost** [comment]
Unless you added Retroarch to your Hakchi2 build, all your NES ROMs need to be unzipped. Hakchi2 as a stand-alone program only supports unzipped ROMs. You need to add Retroarch to be able to use zipped ROMs.

**Comment by Shoothimnow** [comment]
I just (now, literally 5 minutes ago) hacked a co-workers NES classic absolutely fine with 700+ games, no RetroArch, and they work flawlessly.  This issue is more of a user specific issue than an actual bug in the program

For issues that hakchi2 is encountering that ClusterM can fix via coding, post here
For questions / inquiries / how-to's / everything else : https://www.reddit.com/r/miniSNESmods/
