### ISSUE TITLE
Error occurred trying to install Hakchi2 web installer

### ISSUE THREAD

**Issue by Fallen8ngel** [ClusterM/hakchi2#1080]
Trying to install and I get this error?

The following properties have been set:
Property: [AdminUser] = true {boolean}
Property: [InstallMode] = HomeSite {string}
Property: [NTProductType] = 1 {int}
Property: [ProcessorArchitecture] = AMD64 {string}
Property: [VersionNT] = 10.0.0 {version}
Running checks for package '.NET Framework 3.5 SP1', phase BuildList
Reading value 'SP' of registry key 'HKLM\Software\Microsoft\NET Framework Setup\NDP\v3.5'
Read integer value 1
Setting value '1 {int}' for property 'DotNet35SP'
The following properties have been set for package '.NET Framework 3.5 SP1':
Property: [DotNet35SP] = 1 {int}
Running checks for command 'DotNetFX35SP1\dotNetFx35setup.exe'
Result of running operator 'ValueGreaterThanEqualTo' on property 'DotNet35SP' and value '1': true
Result of checks for command 'DotNetFX35SP1\dotNetFx35setup.exe' is 'Bypass'
'.NET Framework 3.5 SP1' RunCheck result: No Install Needed
Launching Application.
URLDownloadToCacheFile failed with HRESULT '-2146697208'
Error: An error occurred trying to download 'http://software.clusterrr.com/hakchi2/hakchi.application'.

**Comment by gBaH0JI9I** [comment]
The site "software.clusterrr.com" under maintenance. There is not a hakchi issue.
You may install portable version from here.

**Comment by travelinphan** [comment]
Getting the same message.  I'd prefer to install web version because thats what is recommended

**Comment by ReyVGM** [comment]
Do not use the web installer.

**Comment by Frank-5** [comment]
I agree. The portable version works just fine. Wish all these non Hackchi issues would not be posted here.  It is just cluttering up the git issue tracker making it harder for ClusterM to fix the real issues.

**Comment by Shoothimnow** [comment]
Technically this post could warrant some legitimacy being posted here (as Hakchi2 itself isn't working), however since we know what the current problem is (and there is about 4 issues created from this) and there are other workarounds (mainly using a different install type), some of these issues need closed.  But to go with @Frank-5, I completely agree, and it's highly irritating.  ClusterM can't see what real problems are when people keep asking "hey, how do I add a picture to my photo?" or "Genesis isn't working!"  *facepalm
