### ISSUE TITLE
Hakchi Files Failed Download

### ISSUE THREAD

**Issue by New2Hakchi** [ClusterM/hakchi2#1088]
When downloading Hakchi, the installer failed to download some files. One was named after a C complier, gcc. What are these files for exactly? Can I use the regular gcc from my cygwin install? Thank you.

**Comment by ReyVGM** [comment]
Don't use the web installer, download the portable version which doesn't need installation.

**Comment by New2Hakchi** [comment]
Why does the software rely on gcc? I appreciate your time.

**Comment by Drakonas** [comment]
@New2Hakchi actually the files are being downloaded from Cluster's server, which is currently down and/or having trouble at the moment. And whatever it was downloading, if gcc was being used to compile, then no the version from cygwin would not work because the gcc in cygwin is only designed to be used in a cygwin environment, which means that running the program requires you to have cygwin installed, or have the cygwin DLL's in the directory of the program.
