### ISSUE TITLE
Japanese Wii Classic Pro Controller [box RVL-A-R2K (JPN)]

### ISSUE THREAD

**Issue by rednal4451** [ClusterM/hakchi2#1094]
Would there be a possibility to add compatibility with the Japanese version of the Wii Classic Pro Controller (an official Nintendo-product)? I bought the controller (the box says it contains a controller "RVL-005(-02)", just as the American/European version), but the controller doesn't do anything on the SNES Classic Mini, so I guess there's an internal difference somehow... The controller works when connected to the Wii....

I'm using the most recent "hakchi2 - v2.21f"

**Comment by rednal4451** [comment]
I took some photo's of the controller:
Front: http://oi65.tinypic.com/2u8c57b.jpg
Back: http://oi67.tinypic.com/hx5c7k.jpg
To me, it really seems an official controller, so I really don't know why it doesn't work...

Nobody who've tested controllers like this on the SNES Classic?
Or someone who can redirect me to some alternative mods? (I used the web installer version of hakchi2)

**Comment by erroneus0** [comment]
I can attest I have used a controller which looks similar to that one which I acquired from Gamestop and it works fine.  I don't know how different the interface is from USB, but I suspect it is at least very much like USB in many ways.  Hakchi2 will allow a user to use protocols such as telnet and ftp against the SNES classic.  I believe if you were to log into your SNES classic and plug the controller into one of your ports, there may be some sort of message or log entry which reports on the device inserted. 

If this is incorrect, I would like to know otherwise.  I have just logged into my SNES classic through telnet and cannot yet find any log files and "dmesg" doesn't exist and reports "klogctl: Function not implemented."  Any help out there?
----
A little more digging and I find /etc/sdl2/gamecontrollerdb.txt with a LOT of numeric IDs followed by some descriptive information.  Among these I see "Nintendo Wii U Pro Controller."  If somehow we can identify the numbers associated with your controller, I suspect we could add that controller to the file.

Another thing I figured out was to do a "cat /dev/input/event2" with the controller plugged into the first port.  Move the sticks or press a button and you will see some binary data come out.  (ctrl-C to exit that) Add to that like this:

cat /dev/input/event2 | hexdump -C

And you will get a cleaner dump of the data coming from your controller.  I see no identifying or useful information, however.

I also notice "cat /proc/bus/input/devices" lists all manner of devices but specifically there are references to the two input ports at /devices/platform/twi.2/i2c-1/1-0052/input/input2 and /devices/platform/twi.2/i2c-2/2-0052/input/input3 referring to the ports rather than the devices plugged into them.

Over all, I'm not finding anything I know what to do with.

**Comment by rednal4451** [comment]
I found the following text from ClusterM in an old topic (https://github.com/ClusterM/hakchi2/issues/180 ), but the mentioned links are broken by now: "If you have controller that still not working on v2.14 please do the following steps:
1. Install mod with stecial debug version of controller driver (drag&drop on hakchi2 window): http://clusterrr.com/temp/clovercon_debug.hmod
[... see link to the topic for the entire text, but I guess it's outdated ...]"

But I also found that since v2.16, there are FTP- and Telnet-servers/clients (hakchi2->Tools) (https://github.com/ClusterM/hakchi2/wiki/Modifications-and-modules-guide ), which probably replaced this. I really don't know anything of this, so I'm quite helpless on this matter...

**Comment by erroneus0** [comment]
I attempted to get the clovercon_debug.hmod but my current network blocked access.  I hope rednal4451 has better luck.  I have a couple of knock-off controllers I'd like to have working.

**Comment by rednal4451** [comment]
When you try to open clovercon_debug.hmod, it just states "Not Found, Error 404. The page you are looking for no longer exists."

I think we have to download clovershell (https://github.com/ClusterM/clovershell-client/releases ) and install it on the SNES Classic as a mod. The page only mentions "NES" but I assume it would be OK for the SNES too? And after that, one should select the FTP server (or should it be Telnet?) and then open FTP client (or Telnet client?). And after that? Could this be the correct way?

**Comment by Drakonas** [comment]
I'll just say this now, if a controller doesn't work with the SNES classic at all, there's nothing Hakchi can do to fix hardware support for a controler. The Japanese Classic Wii [U] Pro Controllers use a different protocol than the American/Europeans do. You'd probably need a Japanese Super Famicom Mini (Japanese SNES Classic) for it to work.
