### ISSUE TITLE
Space issue

### ISSUE THREAD

**Issue by rg4lbaby** [ClusterM/hakchi2#1096]
I went from 250 to 163 for no apparent reason please help

![snesc](https://user-images.githubusercontent.com/33976929/33541098-d2c2e2b6-d89b-11e7-9fb0-7bf9f3f76f51.png)

**Comment by gBaH0JI9I** [comment]
Which cores for retroarch you have installed?
I see you have games for GB, GBA, ARCADE...
Emulators also takes place on the console. ARCADE (fb_alpha) takes a huge of space.
There is no mistake, the console shows the remaining space correctly.

**Comment by bslenul** [comment]
If I'm not mistaken save states and hmods decrease your total space.

For example if you have "150MB / 200MB" and you add 2 save states (2MB each) and a 10MB hmod, you won't see "164MB / 200MB" but you'll see "150MB / 186MB".

**Comment by Shoothimnow** [comment]
Saved data, cores installed, it really depends, however this is not a Hakchi2 issue, and should be posted on a forum instead of an issue tracker

https://www.reddit.com/r/miniSNESmods/

**Comment by rg4lbaby** [comment]
These are all the mods I have. The issue can't be save states because I don't have any.

![snesmods](https://user-images.githubusercontent.com/33976929/33563389-cf942a2e-d8e5-11e7-89b0-36cdbf8a342c.png)

**Comment by Shoothimnow** [comment]
This is the Hakchi2 issues board, where problems that need code changes get addressed so that ClusterM (the creator) can fix the problem.

What you are encountering is a unique instance, where if you post on a forum ( https://www.reddit.com/r/miniSNESmods/ ) you will get more answers.

You are currently asking here for ClusterM to directly fix your issue.

This is not a forum, this is an issue tracker.

**Comment by Drakonas** [comment]
@rg4lbaby save data AND save states increase the size.... if you've launched any games you are creating save data which uses anywhere from 1 to 3 MB of space each. Game boy advance games will use closer to the latter size because their saves are so large. You need to not put so many game boy advance games.
