### ISSUE TITLE
Issue when trying to sync games to my SNES classic.

### ISSUE THREAD

**Issue by Zudexa** [ClusterM/hakchi2#1103]
So I installed some games and the originals would black screen so I tried fixing it by flashing the original kernel and then re-doing the modding process, but now I get stuck when syncing games for it. A dialogue pops up saying the following:
"Waiting for your NES/SNES Mini...
Please do the following steps:
1. Connect your NES/SNES Mini to the PC via USB cable.
2. Turn it on.
3. Install driver if its not installed yet: [Install driver]"
So my SNES mini is connected and turned on in developer mode, and I tried installing the driver, but it installed the NES driver for some reason and the prompt isn't going away. Anyone know how I can fix this?

**Comment by ReyVGM** [comment]
ask on the https://www.reddit.com/r/miniSNESmods/ subreddit. This is a place for submitting bugs with the program.

**Comment by gBaH0JI9I** [comment]
@Zudexa 
Turn off, Reset+Power for 5 seconds. If the driver is installed, will start synchronization.
Are you sure that you have properly installed the driver?
For Windows 64-bit you **MUST** disable driver signature enforcement first.
https://www.drivethelife.com/windows-drivers/how-to-disable-driver-signature-enforcement-on-windows-10-8-7-xp-vista.html
If all done correctly, in the program you will see the free space on the console and green light.
![default](https://user-images.githubusercontent.com/13234037/33686553-4f4698c2-dae6-11e7-8d1f-d4a5207b5ed8.png)
Otherwise use Windows 32-bit or https://www.reddit.com/r/miniSNESmods/ 
It's not Hakchi2 issue.

**Comment by Drakonas** [comment]
This is a bug report tracker, not a personal support request line. Ask these kind of questions at the subreddit ReyVGM linked, please.
