### ISSUE TITLE
" this game pak is not designed for your super famicom or super nes mini snes "

### ISSUE THREAD

**Issue by LIMSA21** [ClusterM/hakchi2#1114]
Hello ,

I have a problem ,

when I run "super metroid" in PAL version, I have this error message.

And if I run "super metroid" in NTSC version (US or JAP) I still have this error message.

But if I run "super metroid" which and supplied with the original mini snes I am no error message.

Same problem with secret of mana, mario world 2, etc.

An idea of the cause of the problem?

Sorry for my bad english i'm a french

**Comment by Shoothimnow** [comment]
Hakchi2 is working as expected , **please close this issue** and post in the correct location (mainly, a forum, and not an issue tracker) - https://www.reddit.com/r/miniSNESmods/

**Comment by gBaH0JI9I** [comment]
@LIMSA21 
Meh.... RTFM.
Use Retroarch instead of built-in emu for troubled games.

**Comment by LIMSA21** [comment]
@gBaH0JI9I  I utilise retroarch and i have the same problem with .

And i enter the " --retroarch " in the url of my game and i have the same issue .


@Shoothimnow  

Sorry if i am in the wrong section , but for me hakchi2 are not working for this game .

But if you confirme me i'm in a wrong section i will close this issue if you want ;-) 


Thx for all

**Comment by Shoothimnow** [comment]
Were you able to add the games to the Classic?  Because Hakchi2 is just a computer application that allows you to add games.

Do you want @ClusterM to program you a fix because everyone is having this problem?  If yes, please keep this issue open.

Otherwise.... this isn't a forum, this is for actual problems with Hakchi2, not a place to ask "hey, how do I get this to work".  That is what a forum is for, mainly - https://www.reddit.com/r/miniSNESmods/

If anything, for your games are not working, that is because Canoe (which is Nintendo's emulator, not Hakchi2) is not working with the game, which again... warrants no reason for it to be posted here...  If you are saying that RetroArch is not allowing these games to play, then it needs to be posted in the correct location.

If you are able to add the games to the SNES Classic, then your issue with Hakchi 2 is.....?  Because it seems to have worked and ClusterM doesn't need to implement any code fixes for you being not not able to add games to the console itself...

**Comment by gBaH0JI9I** [comment]
@LIMSA21 
I just checked myself.
1. A built-in emulator:
   Secret of Mana (U) [!] - US version good dump - WORK, but font is bad (difficult to read).
   Secret of Mana (E) (V1.1) - Europe version - WORK, but font is bad (difficult to read).
   Secret of Mana (F) - French version - WORK, but font is bad (difficult to read).

   Super Metroid (E) [!] - works fine.
   Super Metroid (JU) [!] - works fine.

2. Retroarch:
   Secret of Mana (U) [!] - US version good dump - WORK EXCELLENT.
   Secret of Mana (E) (V1.1) - Europe version - WORK EXCELLENT..
   Secret of Mana (F) - French version - WORK EXCELLENT.

   Super Metroid (E) [!] - works fine.
   Super Metroid (JU) [!] - works fine.

So the conclusion is - download another ROM of the games.

**Comment by LIMSA21** [comment]
@gBaH0JI9I 

thx for all of your test !!!


i will test with 3 other rom of metroid and i have the same issue :-( 

But when i test this rom into my pc with Snes9x all of the rom works fine .

**Comment by gBaH0JI9I** [comment]
Anyway, it's not hakchi issue.
Games issues https://www.reddit.com/r/miniSNESmods/

**Comment by LIMSA21** [comment]
thx for all !! ;-)
