### ISSUE TITLE
C3 Error Everytime I select Game or Folder

### ISSUE THREAD

**Issue by Ishihado** [ClusterM/hakchi2#1126]
Everytime I select a game or folder, it gives me a C3 error. Everytime I leave it sit for a minute under the menue, I get a C3 error that stalls the system, then when I try and shut it down I get a C8 error. Any suggestions on how to fix this?
On a side note, I only have 20 games per menu.

**Comment by gBaH0JI9I** [comment]
You need to reinstall hakchi.
1. In hakchi2 menu: Core - Uninstall
2. Flash original kernel.
3. Factory reset the console in console menu.
4. Flash custom kernel.

**Comment by Shoothimnow** [comment]
This is more of a "anyone, help!" post instead of a "ClusterM, everyone needs this code fix" issue.

Please close this issue and repost in reddit : https://www.reddit.com/r/miniSNESmods/

![34943662-8acebffc-f9ca-11e7-99e9-9a0cb522d41c](https://user-images.githubusercontent.com/32903303/35013211-a694fe3e-fada-11e7-8a07-249b28afcc32.jpg)
