### ISSUE TITLE
Error when hacking mutiple SNES mini?

### ISSUE THREAD

**Issue by Pete856** [ClusterM/hakchi2#1129]

**Comment by Pete856** [comment]
Followed a youtube video and had no problems at all with my first SNES mini. I have two others that I am trying to hack and when following the same steps precisely I get error message that says cant unpack ramdisk.
After googling and looking through issues here I downloaded the debug version which yielded me this error:
![2](https://user-images.githubusercontent.com/34821323/34329721-03ffc86a-e8d9-11e7-8d02-7f0df9ee2c7b.jpg)

**Comment by mrTruch** [comment]
At the very first time you dump the kernel. This kernel is a unique and exclusive file.
If you want to repeat the process on new snesmini (maybe a friend of yours) dump the kernel on a new and clean hakchi to creat a new dump folder with the propietary kernel, and keep safe for the future.

Remember, every unique snes mini its own file kernel. Do not share.

**Comment by erroneus0** [comment]
I would recommend never using the installation version of the program but rather use the portable (.zip) version in different directories.  It seems in order to support multiple machines, it is simply the best way.  One can even re-zip the portable instance for archiving a whole configuration (games, etc) for redeployment on the same machine if one were to experiment with other things.

**Comment by Shoothimnow** [comment]
This is more of a "anyone, help!" post instead of a "ClusterM, everyone needs this code fix" issue.

Please close this issue and repost in reddit : https://www.reddit.com/r/miniSNESmods/

![34943662-8acebffc-f9ca-11e7-99e9-9a0cb522d41c](https://user-images.githubusercontent.com/32903303/35013211-a694fe3e-fada-11e7-8a07-249b28afcc32.jpg)
