### ISSUE TITLE
Security Alert????

### ISSUE THREAD

**Issue by ccateni** [ClusterM/hakchi2#1131]
When I download and try to install the web app, it loads, but then warns me that it will not open due to it being a security risk to the pc, and I can't open it! Please help!

**Comment by ReyVGM** [comment]
You know, it's pretty stupid to put your explanation in the thread title and not in the actual thread...

**Comment by megaDRONe86** [comment]
Also it's very stupid not even try to Google the issue first!

**Comment by Shoothimnow** [comment]
is this even an issue?  because this feels more like a forum post...

**Comment by erroneus0** [comment]
"is this even an issue? because this feels more like a forum post..."

Is there a forum out there somewhere?

**Comment by ReyVGM** [comment]
gbatemp, reddit, neogaf, resetera

**Comment by ccateni** [comment]
I did google it, nothing worked.

**Comment by Shoothimnow** [comment]
https://www.reddit.com/r/miniSNESmods/

**Comment by Shoothimnow** [comment]
This is more of a "anyone, help!" post instead of a "ClusterM, everyone needs this code fix" issue.

Please close this issue and repost in reddit : https://www.reddit.com/r/miniSNESmods/

![34943662-8acebffc-f9ca-11e7-99e9-9a0cb522d41c](https://user-images.githubusercontent.com/32903303/35013211-a694fe3e-fada-11e7-8a07-249b28afcc32.jpg)
