### ISSUE TITLE
extra space mod issues with dualboot 

### ISSUE THREAD

**Issue by jcmejia** [ClusterM/hakchi2#1132]
gives a c2 error when booting to famicom and a c3 error when selecting a game or folder and a c8 when shutting down yes I'm dual booting using a super famicom classic edition to famicom no issues on snes side just the nes side which is the error I mentioned if possible please find a way to make the extra space mod compatible with dual boot

**Comment by ReyVGM** [comment]
![new bitmap image](https://user-images.githubusercontent.com/7338867/34352537-8a172594-e9f9-11e7-98f3-5cc55375f5ae.PNG)

**Comment by Shoothimnow** [comment]
This is more of a "anyone, help!" post instead of a "ClusterM, everyone needs this code fix" issue.

Please close this issue and repost in reddit : https://www.reddit.com/r/miniSNESmods/

![34943662-8acebffc-f9ca-11e7-99e9-9a0cb522d41c](https://user-images.githubusercontent.com/32903303/35013211-a694fe3e-fada-11e7-8a07-249b28afcc32.jpg)
