### ISSUE TITLE
RAMDISK 2 Error

### ISSUE THREAD

**Issue by bluev808** [ClusterM/hakchi2#1134]
I've followed all of the steps to add the games to the SNES classic but I keep running into the same issue. To make sure, I even got another system and still have the same problem. It stops when I get ready to flash the custom kernel right before it starts building it and I'm unable to add the ROMS I've downloaded. Attached is the error message I get. Please help.
![ramdisk 2 error](https://user-images.githubusercontent.com/34892886/34387002-41de0d62-eaf1-11e7-84c6-54fae905946b.JPG)

**Comment by mrTruch** [comment]
Which version do you use? Using portable or installed?
Portable is a recommendation.

**Comment by Shoothimnow** [comment]
This is more of a "anyone, help!" post instead of a "ClusterM, everyone needs this code fix" issue.

Please close this issue and repost in reddit : https://www.reddit.com/r/miniSNESmods/

![34943662-8acebffc-f9ca-11e7-99e9-9a0cb522d41c](https://user-images.githubusercontent.com/32903303/35013211-a694fe3e-fada-11e7-8a07-249b28afcc32.jpg)
