### ISSUE TITLE
Access to 'Snes9x2010.hmod' path denied

### ISSUE THREAD

**Issue by L3ftyGI** [ClusterM/hakchi2#1135]
![capture](https://user-images.githubusercontent.com/34898738/34394591-2d240f20-eb28-11e7-942a-a2c9c25b8f59.PNG)

Any help is greatly appreciated, this comes up no matter what I try. Even trying to uninstall hakchi this comes up.

**Comment by erroneus0** [comment]
Access to path sounds like a local Windows related error.  To eliminate this as a possibility, try running the unzipped version of Hakchi2 from a FAT32 or EXFAT partition whether it is on an SD card or USB drive of some sort, those two file systems pay no attention to file and folder permissions and would eliminate the possibility that the files are blocked due to file level permissions of some kind.

**Comment by Starbuck1991** [comment]
I think this is not a Windows related failure. I've got a lynxboot.img access path error, different file, same trouble. This happened after using the latest version for some time. I managed to solve it flashing the original kernel from an older debug version, then upgrading to the newest debug version. The regular version still gives me the lynxboot.img access path error no matter what, even with a fresh setup. Also, this error prevents any operation, even uploading games, using the regular version. The only way to make it work is using the debug version.

**Comment by Shoothimnow** [comment]
This is more of a "anyone, help!" post instead of a "ClusterM, everyone needs this code fix" issue.

Please close this issue and repost in reddit : https://www.reddit.com/r/miniSNESmods/

![34943662-8acebffc-f9ca-11e7-99e9-9a0cb522d41c](https://user-images.githubusercontent.com/32903303/35013211-a694fe3e-fada-11e7-8a07-249b28afcc32.jpg)
