### ISSUE TITLE
Controller port one not working 

### ISSUE THREAD

**Issue by BigBoss05** [ClusterM/hakchi2#1137]
I flashed a custom kernel weeks ago, but when I booted up my console it didn't recognized controller 1. I tried doing the test menu on Putty but only controller port is recognized.

**Comment by mrTruch** [comment]
Rebooting the snes, normally the port works fine again.

**Comment by BigBoss05** [comment]
Rebooted the SNES multiple times, did not work

**Comment by Shoothimnow** [comment]
Works fine for me, you might need a NAND dump.  If you got this working though, please close this issue

**Comment by Shoothimnow** [comment]
This is more of a "anyone, help!" post instead of a "ClusterM, everyone needs this code fix" issue.

Please close this issue and repost in reddit : https://www.reddit.com/r/miniSNESmods/

![34943662-8acebffc-f9ca-11e7-99e9-9a0cb522d41c](https://user-images.githubusercontent.com/32903303/35013211-a694fe3e-fada-11e7-8a07-249b28afcc32.jpg)
