### ISSUE TITLE
Error C3

### ISSUE THREAD

**Issue by LudovicoPletto** [ClusterM/hakchi2#1141]
So, what should I do to fix the C3 problem?

**Comment by ghost** [comment]
This is a place to report a bug of Hakchi2, not a place to ask how to use it. Ask your question over on: https://www.reddit.com/r/minisnesmods

**Comment by ArieKindicator** [comment]
Check #1138. If you don't use the experimental USB-host feature: do a complete uninstall and factory reset and start over with a virgin OG kernel.
For USB-host, see #1138.

**Comment by Shoothimnow** [comment]
This is more of a "anyone, help!" post instead of a "ClusterM, everyone needs this code fix" issue.

Please close this issue and repost in reddit : https://www.reddit.com/r/miniSNESmods/

![34943662-8acebffc-f9ca-11e7-99e9-9a0cb522d41c](https://user-images.githubusercontent.com/32903303/35013211-a694fe3e-fada-11e7-8a07-249b28afcc32.jpg)
