### ISSUE TITLE
i got a snes hakchi2 c7 error 

### ISSUE THREAD

**Issue by davidyoon18** [ClusterM/hakchi2#1142]
i did it
1. uninstall
2. hakchi2
3. retroarch mod install
4. gui32 -> otg mode install

so i can see game with a otg memocard, but there is c7 error when i start a game.

please, tall me a reason, and solotion ^^ thx guys

**Comment by ghost** [comment]
This is a place to report a bug of Hakchi2, not a place to ask how to use it. Ask your question over on: https://www.reddit.com/r/minisnesmods

**Comment by ArieKindicator** [comment]
Check #1138. If you don't use the experimental USB-host feature: do a complete uninstall *and* factory reset and start over with a virgin OG kernel.
For USB-host, see #1138.

**Comment by Shoothimnow** [comment]
This is more of a "anyone, help!" post instead of a "ClusterM, everyone needs this code fix" issue.

Please close this issue and repost in reddit : https://www.reddit.com/r/miniSNESmods/

![34943662-8acebffc-f9ca-11e7-99e9-9a0cb522d41c](https://user-images.githubusercontent.com/32903303/35013211-a694fe3e-fada-11e7-8a07-249b28afcc32.jpg)
