### ISSUE TITLE
hakchi2 USB Support

### ISSUE THREAD

**Issue by markched** [ClusterM/hakchi2#1152]
Hello,

Love the software and everything you guys are doing.  I see online that there are people adding USB Support to their classics, is this something built into the stock Hakchi2 software or not? Every "how to" guide online shows we do it via someone else's firmware. 

Is this the case or am I misunderstanding things? BTW, using 2.0.21.72.  I think its the latest. 

Thanks, guys!

**Comment by gingerbeardman** [comment]
Go to Manic's channel for tutorial video (most recent): 
https://www.youtube.com/channel/UCoRrbw6gyi4KRPGUNnVVjMQ

And to his github for the best emulator core mods: 
https://github.com/KMFDManic/NESC-SNESC-Modifications

**Comment by djritz0** [comment]
Has anyone experienced overheating thru the USB-HOST method?

**Comment by gingerbeardman** [comment]
@djritz0 what are your symptoms?

**Comment by djritz0** [comment]
@gingerbeardman @clusterm can play unit for a out 20-30 mins, Snes classic gets hot as well as the OTG unit getting quite warm. Then it crashes and reboots. Sometimes is happens after a bunch of soft reboots to the menu. At first I thought it might be due to it creating too many save states, but I have a 128GB USB with save folder on the stick. 
I am under the 60 folders limit mentioned by Kyland K (3 separate folders with 15-20 games each).
Have uninstalled on hakchi2, did hakchi1 USB install. Still seems to do it. Totally clueless as to why is resets like that. Aside from the overheating and random reboots, all games work (I have Snes, ps1, and arcade ROMs working thru 3 separate folders, plus retroarch). Oh yea, also used to get C2,C3,C7,C8 errors as well. Infrequent but have got those.

Help!

**Comment by mrTruch** [comment]
@markched No USB official release. No official support.

@djritz0 Plase create own issue. I recommend change USB cable or power supply.

**Comment by gingerbeardman** [comment]
@djritz0 yes let's take this to your own issue. maybe your power supply is giving too many amps?

**Comment by Shoothimnow** [comment]
Please explain how this is an **issue** with Hakchi2.

This needs to be in a forum instead of the issues board.... https://www.reddit.com/r/miniSNESmods/

**Comment by markched** [comment]
@mrTruch 

Thank you very much! I wasn't sure if it was official yet or just a workaround! Thanks! I hope its official before an N64 classic comes out! That is when we're really going to need the extra storage!!!

**Comment by mycharge** [comment]
I have mycharge 6000 hub will it work for usb drive for for hakchi2 it works so for for a power adaptor and has usb on it i was using it to play my nes Classic thanks.
