### ISSUE TITLE
HELP! When turning on the power just a black screen

### ISSUE THREAD

**Issue by lowloud** [ClusterM/hakchi2#1153]
I am having a problem with my SNES classic I was playing Zelda and it didn’t like the save component on it so I was using the save component built into the SNES and then it kicked me out and now when I turn on my SNES it is only a black screen you can’t see anything else and if you try to turn it off the red light stays on

**Comment by ReyVGM** [comment]
This is a place for reporting bugs of Hakchi2, not a place for users to report issues they have when trying to use the software. There is already a large online community for modding Classics over on https://www.reddit.com/r/minisnesmods Please ask you question over there. You will likely get multiple people there to help you out.

**Comment by Shoothimnow** [comment]
This is more of a "anyone, help!" post instead of a "ClusterM, everyone needs this code fix" issue.

Please close this issue and repost in reddit : https://www.reddit.com/r/miniSNESmods/

![34943662-8acebffc-f9ca-11e7-99e9-9a0cb522d41c](https://user-images.githubusercontent.com/32903303/35013211-a694fe3e-fada-11e7-8a07-249b28afcc32.jpg)
