### ISSUE TITLE
Can't Launch application

### ISSUE THREAD

**Issue by Taizean** [ClusterM/hakchi2#1161]
I downloaded the web installer and everytime I click on it it says, "Cannot continue. The application is improperly formatted. Contact the application vendor for assistance." I can't seem to get around this.

**Comment by ghost** [comment]
People have ran into problems with the web installer. I would suggest trying the [portable version](https://github.com/ClusterM/hakchi2/releases/download/2.21f/hakchi2.21f.zip) to see if that works for you.

**Comment by Shoothimnow** [comment]
This is more of a "anyone, help!" post instead of a "ClusterM, everyone needs this code fix" issue.

Please close this issue and repost in reddit : https://www.reddit.com/r/miniSNESmods/

![34943662-8acebffc-f9ca-11e7-99e9-9a0cb522d41c](https://user-images.githubusercontent.com/32903303/35013211-a694fe3e-fada-11e7-8a07-249b28afcc32.jpg)
