### ISSUE TITLE
Overlay in retroarch does not work with NESC

### ISSUE THREAD

**Issue by darkdev1** [ClusterM/hakchi2#1163]
Overlay in retroarch does not work for the CRT mode with NESC.

**Comment by ghost** [comment]
Sounds like that's a Retroarch issue, not a Hakchi2 issue. Please close this issue report, and ask your question here: https://github.com/ClusterM/retroarch-clover/issues

In fact, your issue may be tied to [Issue #152](https://github.com/ClusterM/retroarch-clover/issues/152).

**Comment by darkdev1** [comment]
Thanks, I did not see this is already reported as a retroarch issue, nothing wrong with seeing it here too?

**Comment by ghost** [comment]
It's not a Hakchi2 issue though. This is where people should report issues of Hakchi2, not issues with Retroarch (since ClusterM, creator of Hakchi2, is not responsible for Retroarch). Please close this issue, and ask your question either on Reddit or on the retroarch-clover Github. 

> This is not RetroArch repository.

https://github.com/ClusterM/hakchi2/issues/118
