### ISSUE TITLE
snes mini doesn't boot

### ISSUE THREAD

**Issue by rainor77** [ClusterM/hakchi2#1164]
hi guys . help plz i need de snes mini stock kernel

**Comment by ghost** [comment]
This is a place to report bugs of Hakchi2, not a place to ask for the original kernel. No one is allowed to post their kernel, because it is copyrighted, and doing so could result in Nintendo taking legal action against Hakchi2.

And we don't want that.

I have seen people ask on Reddit. Whether anyone has emailed a copy to them, I don't know, but you may want to try and ask there: https://www.reddit.com/r/miniSNESmods/

Please close this issue report.

**Comment by Shoothimnow** [comment]
This is more of a "anyone, help!" post instead of a "ClusterM, everyone needs this code fix" issue.

Please close this issue and repost in reddit : https://www.reddit.com/r/miniSNESmods/

![34943662-8acebffc-f9ca-11e7-99e9-9a0cb522d41c](https://user-images.githubusercontent.com/32903303/35013211-a694fe3e-fada-11e7-8a07-249b28afcc32.jpg)

Also, we can't give you the stock kernel as that is illegal

**Comment by rainor77** [comment]
sorry about this....it was despair
