### ISSUE TITLE
Cannot sync due to incorrect reported total space

### ISSUE THREAD

**Issue by tap52384** [ClusterM/hakchi2#1165]
![virtualbox_win10vm_14_01_2018_00_08_04](https://user-images.githubusercontent.com/647983/34913036-7d1aa972-f8bf-11e7-9f4a-e92e387b8263.png)

Cannot synchronize games anymore since hakchi2 is incorrectly reporting the available amount of file space. I included a screenshot to show what I mean. This happened after I installed a module (mame2014).

**Comment by tap52384** [comment]
I realized that I had a different issue (could not install modules when using the web installer), so I copied the dump, games, and config folders to a portable installation. Originally, I had 200+ MB of space for files, but much less is available now.

**Comment by tap52384** [comment]
I found a link on reddit that suggested that the mame modules take a lot of space so I installed mame2010 and things got a bit better. It would be good to see a bar like this that broke down the space usage:

<img width="932" alt="screen shot 2018-01-14 at 12 19 03 am" src="https://user-images.githubusercontent.com/647983/34913060-b04dca3a-f8c0-11e7-969b-975a2748a27d.png">

**Comment by ghost** [comment]
The Hakchi2 user interface window did show a full progress bar, and explained that you were trying to write 109.4 MB into 90.8 MB of free space (in red down at the bottom of the window), and the error window broke down the used and available spaces for you.

> Total writable memory size: 290.6MBytes
> Available memory for games: 90.0MBytes
> Used by saves: 0.6MBytes
> Used by other files: 154.3MBytes

That isn’t sufficient enough?

Only reason I ask is that recoding Hakchi2 to add a multi-colored progress bar would probably take a bit of time, and we haven’t even had an update to the program since October. The likelihood that a feature like that will be added in the near future seems low to me. I can be wrong, though.

If it’s an important feature you want to see in Hakchi2, maybe you can pull the source code files and join others like DanTheMan and KMFDManic by working on a multi-colored progress bar on your own, and submit it to ClusterM so it can get integrated in a future release of Hakchi2.

As explained in the [FAQs](https://www.reddit.com/r/miniSNESmods/comments/73qve2/frequently_asked_questions/), you have about 250MB of free space on a stock (no USB mod) SNESC console. Obviously hmods will consume some of that free space when you add them to your system. Hakchi2 should reflect that at the bottom of the user interface window (like your example shows, your system shows only 90.8MB available while you are trying to add 109.4MB).

**Comment by tap52384** [comment]
It does tell you what was trying to happen, but the error message does not account for space taken up by modules. You're right that there hasn't been an update since October. Is this app still active? Are you one of the maintainers? I haven't coded C# at this level, but I can try to create the bar if it will help.

One question: where are the installed modules located (file path)? Or, since they seem to be installed differently, what is the original size once hakchi2 is installed but no modules have been added yet?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ghost** [comment]
No, I'm just a member of the modding community who is trying to help where I can.

ClusterM took a break working on Hakchi2 for a while. I know he started to look at it again (he seemed overwhelmed by how much the community has worked on in his absence), but I haven't heard anything hinting to a newer version on the horizon.

Not even mods are actively monitoring these issue reports anymore, so who knows.

Several people have stepped up to contribute to modding Classics, and that has truly been awesome. It's good to see this community work together like it has the last several months.

If you have the ability to look into the source code to try a few things, that'd be great! I'm sure ClusterM would appreciate your efforts.

**Comment by tap52384** [comment]
Thanks so much for responding. If I can make sense of what's going on I'll give it a shot.

**Comment by Shoothimnow** [comment]
This is more of a "anyone, help!" post instead of a "ClusterM, everyone needs this code fix" issue.

Please close this issue and repost in reddit : https://www.reddit.com/r/miniSNESmods/

![34943662-8acebffc-f9ca-11e7-99e9-9a0cb522d41c](https://user-images.githubusercontent.com/32903303/35013211-a694fe3e-fada-11e7-8a07-249b28afcc32.jpg)
