### ISSUE TITLE
can't launch retroarch GBA/GENESIS games : black screen and return to the home page

### ISSUE THREAD

**Issue by grokuik** [ClusterM/hakchi2#1167]
hello,
it work fine with SNES ( --retroarch) but nothing on megadrive and gba ( and NEOGEO)
i ve flashed the original kermel and try again , nothing change
i ve try with unzipped game , nothing
i ve watched thousand video of tutorial and still not understand.

can you help me ?

**Comment by ghost** [comment]
This is a configuration problem. Previous discussions over on Reddit have referred to bad file extensions as being the possible culprit.

https://www.reddit.com/r/miniSNESmods/comments/76q3wm/sega_genesis_rom_not_working_for_retroarch/

https://www.reddit.com/r/miniSNESmods/comments/755lv5/trouble_getting_gba_roms_to_work_with_retroarch/

Since this is a configuration problem (and not a bug in Hakchi2), please close this issue report, and if you have further questions, please post your questions here: https://www.reddit.com/r/miniSNESmods/

**Comment by Shoothimnow** [comment]
Please **close this Hakchi2 (as this isnt a Hakchi2 issue) issue** and re-post in the correct location, mainly the RetroArch issues board https://github.com/ClusterM/retroarch-clover/issues.

**Comment by grokuik** [comment]
ok thanks
