### ISSUE TITLE
Help! Can't Sync Games with SNES CLASSIC anymore

### ISSUE THREAD

**Issue by Mateotheshark** [ClusterM/hakchi2#1169]
I successfully synced games when going through the entire Hakchi2 Process the first time...and most games worked. I wanted to organize files and add more games but now I cant! I still have my original Dump...I have flashed the original kernel, uninstalled Hakchi, and did a manual factory reset on the fresh SNES. I then returned to my PC, flashed custom kernel without a problem, installed mods without a problem, but when I go to sync selected games, nothing happens...I believe drivers have installed correctly. I have repeated this process numerous times. I even spent a day backing up my entire computer's files to an external hard drive and did an entire system recovery on my PC 64bit windows 10...updated all computer drivers...re-downloaded Hakchi2 and went through the same process again...still cant sync games. I've read all the troubleshooting posts I could find?...am I missing something? I don't think my classic is bricked? because I cant still flash original kernel and uninstall everytime and it goes back to factory...any help would be much appreciated! Matt

**Comment by ghost** [comment]
This place is where people are supposed to report bugs in Hakchi2. This is not a help forum to ask how to use Hakchi2 properly. Please close this issue report (the button at the bottom of the page that says “Close Issue”), and ask your question over on the modding community’s Reddit group: https://www.reddit.com/r/miniSNESmods/ 

When you post on Reddit, make sure you explain exactly what happens when you try to sync games (like, is there an error message)?

You would only post here if you found a legitimate bug or glitch that may need to be looked into by ClusterM. If he is still actively working on this repository (he hasn’t had a release since mid-October), he’d probably look into it when he got the chance, and if he could find a fix, he’d incorporate it into a future update somewhere down the road (in other words, it’s unlikely that reported bugs/glitches will get fixed quickly).

**Comment by Shoothimnow** [comment]
This is more of a "anyone, help!" post instead of a "ClusterM, everyone needs this code fix" issue.

Please close this issue and repost in reddit : https://www.reddit.com/r/miniSNESmods/

![34943662-8acebffc-f9ca-11e7-99e9-9a0cb522d41c](https://user-images.githubusercontent.com/32903303/35013211-a694fe3e-fada-11e7-8a07-249b28afcc32.jpg)

**Comment by Mateotheshark** [comment]
sorry if I posted this in the wrong place and so late??? I didn't get my SNES classic until Christmas...I never was one of those spoiled kids that got his console the DAY it was released ;) ...and this is just the only place that was popping up when I googled my issue...thanks for  the Reddit link! I will check that out!
