### ISSUE TITLE
re stocked Mini Snes classic will not unpack kernel image after dump

### ISSUE THREAD

**Issue by ghost** [ClusterM/hakchi2#1170]
I bought the newly restocked snes mini

Used hakchi2 v2.21f  When flashing i get as far as building the custom kernal image...
An error window pops up saying Can't unpack kernel image.

Thanks.

**Comment by Shoothimnow** [comment]
This is more of a "anyone, help!" post instead of a "ClusterM, everyone needs this code fix" issue.

Please close this issue and repost in reddit : https://www.reddit.com/r/miniSNESmods/

![34943662-8acebffc-f9ca-11e7-99e9-9a0cb522d41c](https://user-images.githubusercontent.com/32903303/35013211-a694fe3e-fada-11e7-8a07-249b28afcc32.jpg)
