### ISSUE TITLE
cannot flash custom kernel

### ISSUE THREAD

**Issue by OddOttAllen** [ClusterM/hakchi2#1171]
hello. when I tried to add 9 games to my SNES Classic, the program would give me an error saying that I do not have permission to access some folder. I thought I had to add my original dump to the folder since it was empty, but that did not work. any help would be appreciated.

**Comment by OddOttAllen** [comment]
also, while I'm here, the program gave my father's laptop a virus, so thanks to the bugger that decided that adding a virus into the program would be funny. ha ha.

**Comment by Shoothimnow** [comment]
This is more of a "anyone, help!" post instead of a "ClusterM, everyone needs this code fix" issue.

Please close this issue and repost in reddit : https://www.reddit.com/r/miniSNESmods/

![34943662-8acebffc-f9ca-11e7-99e9-9a0cb522d41c](https://user-images.githubusercontent.com/32903303/35013211-a694fe3e-fada-11e7-8a07-249b28afcc32.jpg)

**Comment by OddOttAllen** [comment]
okay
