### ISSUE TITLE
No response from Controller

### ISSUE THREAD

**Issue by Zacowacko** [ClusterM/hakchi2#1172]
SNES Classic has been running fine for several weeks,  until today.  I get zero response from controller.  Tried multiple different controllers, with and without extensions.  Power down, unplug, you name it.  Unit powers on fine, but cannot navigate or get the unit to respond to any controller inputs.  

Running latest version of Hakchi.  I'm at a loss, any pointers?  Thanks

**Comment by Shoothimnow** [comment]
This is more of a "anyone, help!" post instead of a "ClusterM, everyone needs this code fix" issue.

Please close this issue and repost in reddit : https://www.reddit.com/r/miniSNESmods/

![34943662-8acebffc-f9ca-11e7-99e9-9a0cb522d41c](https://user-images.githubusercontent.com/32903303/35013200-99993d26-fada-11e7-858a-5aad51ac85b0.jpg)
