### ISSUE TITLE
ROM Hacked Games will not launch.

### ISSUE THREAD

**Issue by Alotofcam** [ClusterM/hakchi2#1175]
Black Screen then Home Screen thats all that happens

**Comment by ReyVGM** [comment]
This is a place to report a bug of Hakchi2, not a place to ask how to use it. Ask your question over on: https://www.reddit.com/r/minisnesmods

**Comment by Shoothimnow** [comment]
This is more of a "anyone, help!" post instead of a "ClusterM, everyone needs this code fix" issue.

Please close this issue and repost in reddit : https://www.reddit.com/r/miniSNESmods/

![34943662-8acebffc-f9ca-11e7-99e9-9a0cb522d41c](https://user-images.githubusercontent.com/32903303/35013211-a694fe3e-fada-11e7-8a07-249b28afcc32.jpg)

It seems you were able to put the game on the SNESC.  If you put the game on there, then Hakchi2 is working.  If you can't run the game, then RetroArch is giving you problems, not Hakchi2.  Hakchi2 is the computer application....
