### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by angelusjmw** [ClusterM/hakchi2#1177]
Having c3 and c8 error problems with my snes mini classic when I go to the games I downloaded but can’t move around to pick another game

As it would be frozen can’t use controller to move around or go back
And can’t go back to the original games repeatedly need help solving the issues 

Tried to change by flashing original kernel sync then downloading the games I wanted to add some games I was able to download easy and play them but now I can’t play anything

Wanted to add illusion of Gaia finally solved how to add the patch but can’t see if it works

Some games I already downloaded before they did work but can’t access them anymore

So need help to restore system to factory settings without access to the system to be able to download safely the games I want to add and play

**Comment by ReyVGM** [comment]
This is a place to report Hakchi2 bugs, not a place to ask how to use it. Ask your question over on: https://www.reddit.com/r/minisnesmods

**Comment by Shoothimnow** [comment]
This is more of a "anyone, help!" post instead of a "ClusterM, everyone needs this code fix" issue.

Please close this issue and repost in reddit : https://www.reddit.com/r/miniSNESmods/

![34943662-8acebffc-f9ca-11e7-99e9-9a0cb522d41c](https://user-images.githubusercontent.com/32903303/35013211-a694fe3e-fada-11e7-8a07-249b28afcc32.jpg)
