### ISSUE TITLE
SNES without FEL and/or LED always on

### ISSUE THREAD

**Issue by comolake34** [ClusterM/hakchi2#1180]
Hi There,

First thank for all the time you put in this project.

After having installed hakchi a first time with sucess, I've tried to re-install Hakchi (gui) for usb support.
Everything was running fine, until the very end when i tried to switch off. Console said no device in Fel mode...Since i'm unable to boot in fel mode and when i try to boot normally nothing happens and led is still on when i switch off.

Any help ?

Thanks
this tutorial was followed : http://snesclassicmods.com/add-more-storage-with-external-usb-hard-drive-mod-for-snes-classic-mini/

**Comment by Shoothimnow** [comment]
Hakchi2 is like KODI, all it is is the base hack on your system.  Anything else added... no longer is an issue with Hakchi2, but with whatever mods you are putting on.  Most likely a corrupted config file.  Best bet is to either remove everything and reinstall,

or ask on reddit seeing that this is more of a "anyone, help!" post instead of a "ClusterM, everyone (and I mean EVERYONE) needs this code fix for this **massive** problem" issue.

Please **close this issue** and repost in reddit : https://www.reddit.com/r/miniSNESmods/

![34943662-8acebffc-f9ca-11e7-99e9-9a0cb522d41c](https://user-images.githubusercontent.com/32903303/35013211-a694fe3e-fada-11e7-8a07-249b28afcc32.jpg)

This is something that needs to be handled in the SNES Classic mods subreddit. This tracker is for reporting known bugs to us, not troubleshooting our software.

**Comment by comolake34** [comment]
Tahnks for advices ! i'll do.
