### ISSUE TITLE
Hackchi debug showing an error from the start, what does this mean?

### ISSUE THREAD

**Issue by castro4eva** [ClusterM/hakchi2#1181]
Upon using hakchi 2.21f debug, I see this error in the log when I perform the very first step, which is dumping your original kernel.  What made me decide to do this was a series of subsequent problems when modding, all of which seemed to stem from something not going well at the very beginning:

Error: Exception of type 'com.clusterrr.FelLib.FelParseException' was thrown.   at com.clusterrr.FelLib.AWUSBResponse..ctor(Byte[] data) in D:\Projects\C#\hakchi2\FelLib\AWUSBResponse.cs:line 22
   at com.clusterrr.FelLib.Fel.FelRead(UInt32 length) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 241
   at com.clusterrr.FelLib.Fel.VerifyDevice() in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 274
   at com.clusterrr.FelLib.Fel.Open(UInt16 vid, UInt16 pid) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 155

I know this isn't the place to learn how to use hakchi. I just want to know if the above error indicates some software or hardware issue, or if its just user error on my part and I have to change how I go about taking my modded SNES classic back to its original state? I would think successful flashing of the original kernel and a factory reset would straighten any issues, but after seeing this and numerous other errors in the debug log, it makes me wonder.  At least it looks and plays fine whenever I start over and put it back to its original state.

I started out using hakchi 2.21f, then tried 2.21b a number of times before switching to 2.21f debug.  I'm using a PC laptop running Windows 8. When I get the dreaded "invalid kernel size" error and want to start over, I go to KERNEL -> UNINSTALL from the top menu, follow its prompts (which includes flashing the original unmodded kernel), then finish it off by doing a factory reset on my SNES classic. I delete the extracted hakchi folder I used before and start fresh with a new & clean extraction of hakchi.

**Comment by Drakonas** [comment]
Just because there is an error in a debug log does not mean there actually is a problem. It sounds to me like the features of hakchi2 are working as intended for you. Am I wrong? If everything is working correctly, there's not much use of us seeing an error if we don't know what exactly to look for...

**Comment by castro4eva** [comment]
That's what I was trying to figure out.  I am getting an "invalid kernel size" error when loading any cores of any kind right after I dump the original kernel. It worked fine for me the very first time, but since then, something hasn't been right. I uninstall the kernel, re-flash the original kernel from before I did any modding, and try again always changing something (e.g. usb port, usb cable, usb 3.0 port vs usb 2.0, different cores, etc.).  I just get the same result in the end.

So I wrote here trying to see if there's some sort of issue on the back end, either with hakchi or that I've caused by not doing something right.  Of course there could be other explanations, like the cores being an issue, but I'm just trying to cover my bases.  I've never used the debug version before, so I wasn't sure if those errors were common. From talking to others, it sounds like they are.

**Comment by Drakonas** [comment]
You probably need to obtain a fresh kernel from the internet. Yours may have corrupted. Either way, this needs to be handled on Reddit. This issue tracker is not intended for "I have an error HELP" issues, but is intended for "I have an error, and I found the problem to be X, please fix" issues. If you don't know what the problem is, discuss it on Reddit here: https://www.reddit.com/r/miniSNESmods/ ClusterM can't fix a problem if he doesn't know what produces it.
