### ISSUE TITLE
install driver if not installed problem

### ISSUE THREAD

**Issue by Crouchy12** [ClusterM/hakchi2#1184]
help with this one cant seem to get pasted it starting annoy me now

**Comment by Crouchy12** [comment]
any help i'd appreciate it

**Comment by Shoothimnow** [comment]
This issues board is for ClusterM (the creator) to patch Hakchi2 with known bugs.

If you are looking for a "how-to ---anything---" guide, please close this issue and repost on reddit: https://www.reddit.com/r/miniSNESmods/

![34943662-8acebffc-f9ca-11e7-99e9-9a0cb522d41c](https://user-images.githubusercontent.com/32903303/35013211-a694fe3e-fada-11e7-8a07-249b28afcc32.jpg)

**Comment by Crouchy12** [comment]
Appreciate it thanks any idea when they will be updated it making it so much easier to use

**Comment by Shoothimnow** [comment]
This isn't a problem with Hakchi2 and will most likely not be updated.  Most to everyone is not having this issue.

Again, this isn't a forum....  If you want answers on "how-to"'s, please post in an actual Forum, https://www.reddit.com/r/miniSNESmods/ instead of an issues tracker

and **close this issue** to help clean up false alarms / garbage that doesn't belong here
![34943662-8acebffc-f9ca-11e7-99e9-9a0cb522d41c](https://user-images.githubusercontent.com/32903303/35013211-a694fe3e-fada-11e7-8a07-249b28afcc32.jpg)
