### ISSUE TITLE
Game Titles

### ISSUE THREAD

**Issue by ghost** [ClusterM/hakchi2#1188]
Using the last release and after syncing with the system, I have noticed that the titles are missing letters. Example "Power" is "Poer" or words are missing. I've checked to make sure I didn't make a mistake and everything is fine on my end.

**Comment by Drakonas** [comment]
if you are having problems then everything must not be fine on your end. Nobody else is having this issue. This is more of a "anyone help!" issue than a "ClusterM, I know what the problem is, and it's right here" issue, which is what bug trackers are for. Finding what the issue is is supposed to be handled on an actual forum or reddit, like https://www.reddit.com/r/miniSNESmods/, which I suggest to request help from rather than here.
