### ISSUE TITLE
NES and Genesis games no longer work after hakchi 2.3 update 

### ISSUE THREAD

**Issue by fstbckgt** [ClusterM/hakchi2#1213]
Aside from free space going down by ~30MB my NES and Genesis games that previously worked on my SNES classic no longer load and the system gets stuck on a black screen.

**Comment by ghost** [comment]
Exact same thing here. GBA seems to work fine though.
For your storage problem, use the new feature: https://github.com/ClusterM/hakchi2/wiki/USB-storage-guide

**Comment by fstbckgt** [comment]
I don't really need more space but I would like to get my SNES working again.  Tried to go back to the previous version of Hakchi but when I did available space on the SNES went down to only 20MB even after returning the SNES to stock and re adding the custom kernel.

**Comment by bumfacekilla** [comment]
@fstbckgt, I had the same issue but the SNES roms requiring SNES9X to run also were also failing to play. My space also dropped to around 20MB after trying to return to the previous version of hakchi2. To get my space back, I had to use v2.30 to remove all roms and return to stock firmware and then use v2.21f to re-install custom kernel and additional modules and then re-add all games. Everything is now working as it did before the update. Hope this helps.

**Comment by gBaH0JI9I** [comment]
I have the same thing. 
Hakchi 2.30 + retroarch 1.1b = don't work various SNES, NES and GBA games.
Hakchi 2.30 + retroarch 1.0c = don't work various SNES, NES and GBA games.
Reinstall many times modules and reflash to factory and back to custom - no luck.

Return back to the Hakchi 2.21f + retroarch 1.0c. In this combination works all my games.

**Comment by timehlers** [comment]
Same thing here, console crashes really hard when trying to start a NES or Sega game, neither the reset button is working anymore, nor the power switch itself. I need to drop power and reconnect to run the console again.

**Comment by fstbckgt** [comment]
I ended up deleting and reloading the Genesis Games and removing the (U),(J), etc from the command lines on the nes games and this fixed the issue

**Comment by dbelyaev** [comment]
@ClusterM looks like there are multiple users facing this issue, can you check this out, if you have time?

**Comment by BreakerBeam** [comment]
Hi, just commenting to add more information as I am encountering the same issue. 

I only have NES and SNES games added to my console. All my original and added SNES games work fine but when I select an NES game the screen turns black and I can no longer reset or turn my system off. I have to pull the power plug to get it to shut off.

The last time my system was working I was using Hakchi 2.21f and retroarch 1.0c. I started getting this issue when I updated to Hackchi 2.3. Updating retroarch to 1.1b did not help the problem. 

I tried fstbckgt's solution of removing (U),(J), etc from the command lines on a few games. It did not work for me. Instead of the screen turning black and the console becoming unresponsive, instead the screen just turns black and then it returns me to the game selection screen. 

Hope that helps!

**Comment by MayarLink** [comment]
I can confirm, all my nes/genesis games work fine on v2.21f and 1.0c , today i update to 2.3 and new 1.1b, right now none of my nes or genesis games works, then you start them it's just black screen and dead console. Only thing you can do is turn off power.

**Comment by ClusterM** [comment]
Seems like it's because of some characters in filenames. Try to delete those games from hakchi 2 and re-add them again.

**Comment by MayarLink** [comment]
Thx, this is actualy works... after i delete all games, and re-add them, all games works fine.

**Comment by ClusterM** [comment]
Fixed that in hotfix update: https://github.com/ClusterM/retroarch-clover/releases/tag/1.1c
Just install it if you don't want to re-add all your games.
