### ISSUE TITLE
Hakchi v2.30 custom kernel issue

### ISSUE THREAD

**Issue by Dominik92B** [ClusterM/hakchi2#1219]
After I updated to hakchi2 v2.30 I started to have issues with my SNES mini so I uninstalled Hakchi and dumped the original kernel. I checked and the console was working properly so I just flashed the custom kernel, reinstalled retroarch cores (only the ones to read other console's games) and synchronized my previous games. At this point the console stops to work (I already tried several times and every time I flash the custom kernel the SNES stops to work). It turns on, my controllers syncs but my TV's screen remain black and there is no signal (it works anytime I restore the original kernel and stops working everytime right after I flash the custom one). Reset do nothing and even when I turn it off the red light remain on.

**Comment by jearbear713** [comment]
I’m having the same exact problem.

**Comment by Stone2k18** [comment]
Oh shit.  Im having the same issue.  Im trying something different Ill keep you guys posted

**Comment by ToastBoi** [comment]
Im having the same exact problem. I cant play my games! ;-;

**Comment by Stone2k18** [comment]
Ill work on mines tonight.  I'll let you guys know if I find anything.  I may just use the previous hackchi 2 and old retroarch. That may work.  

Dont forget to turn your clocks forward

**Comment by ProjektRF** [comment]
I'm having the exact same problem. Shame its been 14 days and still no fix.

**Comment by youngtune27** [comment]
Every time you upgrade stuff can get messed up. And then even if go back to another version it will still mess up. Try this these steps in order. Make sUre you have your factory dump moved over and then Open up hakchi. Uninstall all mods. Then under one of the tabs up top has uninstall hakchi in it. Click Uninstall hakchi. Then let it do its thing. Then Flash original kernel. Then Turn system on and factory reset it. Then flash custom kernel. Then add your mods and games. Assuming you don’t care about saves. You could ftp first Before any of this if you do. I would recommend going back to 2.21f.

**Comment by ProjektRF** [comment]
Have reinstalled it over and over again and it does the same thing every time. Was excited about this iteration because of its built in usb memory expansion but it just doesnt work at all

**Comment by youngtune27** [comment]
I know bro. But try those exact steps in order. Have you started anything with usb? Or still main memory etc.

**Comment by Dominik92B** [comment]
Your solution is very similar to what I tried over and over again too (the only difference is that you added the factory reset)...the point is that right after flashing the new custom kernel, even before adding retroarch cores and games, the console stop to work. It doesn't turn off anymore and when connected to the TV the screen remain black. Restoring it to the original kernel solve the problem and then the issue reappear as soon as the custom kernel is flashed again.

**Comment by youngtune27** [comment]
I know you have tried stuff but have you in the exact order I said? I’m just trying to help. Like last year this person was having issues till they tried it. https://github.com/ClusterM/hakchi2/issues/276 Different issue but still try it. You can also trying flashing 2.21f kernel on and see if that works. But reasons your steps above I can see why you haven’t fixed it. You don’t uninstall hakchi and dump original kernel. Only time
You dump original kernel is first time ever.

**Comment by Dominik92B** [comment]
The help is really appreciated :) will try again as soon as possible and let you all know

**Comment by youngtune27** [comment]
Okay let me know. Make sure in order. If you click #276 above you can go see the other github issue from before. There is a slight chance 2.30 is just messed up. If that’s the case I can get you fully functional on 2.21f or earlier.

**Comment by ProjektRF** [comment]
Telling us to go to an earlier version doesnt fix anything. Also issue #276  isnt even the same problem as we're having.

**Comment by youngtune27** [comment]
I know it’s not the same issue. I said it wasn’t. What I’m saying is stuff overlaps when you upgrade. That other issue is an EXAMPLE. Doing what I said fixed it. It could also for this issue. Going down from 2.30 would be if there is an actual problem with the custom kernel that only he can fix therefore going back down is your only option. And a lot of people don’t know how so I was just saying.

**Comment by ProjektRF** [comment]
Okay so I figured out what the issue was. For whatever reason my original kernel wasnt the actual original. I would assume at some point when I had originally dumped my kernel it must've had some leftover on it still. So I googled for a copy of the original kernel and then reinstalled it all over again. After making sure it was the actual original kernel it seems to be giving me video now.
I do not know if this is the issue everyone here is having but give a try and see if that helps at all.

**Comment by youngtune27** [comment]
See I told you. It’s always something to do with stuff overlapping. Each time you upgrade you have to dump kernel unless you move your original kernel to new hakchi. And you would be dumping a modified kernel which works sometimes but always tends to mess up. Since you’re good now let me know how external memory is. Is it worth it?

**Comment by ProjektRF** [comment]
With the last hakchi I had the external memory it was super worth it. Was just a pain to install. This makes it nice and easy though. All you really have to do is buy a Micro usb otg cable and you can have as many games as you want on it. Cluster put up a nice guide on setting it up as well.

**Comment by youngtune27** [comment]
Do games show up and launch and save from the GUI like Normal or do you have to load them through retroarch? I have a ras pi too but it’s kinda inconvenient. As long as stuff from usb loads the same then it would be worth it? What happens if you don’t haves usb plugged in? Just original 30 show up?

**Comment by ProjektRF** [comment]
My otg cable broke so I havent had the chance to test it with the new version of hakchi but with the other version everything would just show up normally on the system. And yea if you dont have the usb in it just shows the original 30.

**Comment by ibmp200** [comment]
I may have a similar issue to what this post started with, but thought i'd check by sharing mine. I am using hakchi version 2.0.30.14 in a Windows 7 computer, with a NES Classic. I initially added about 60 games to the 30, though having cut 30 to 22; for a total of 82. All added games are Nintendo. Two being Japan only releases, and those were properly working using Retroarch. This version of hakchi had been working fine. Recently though I decided to remove 2 of the added games. So, I deleted them from hakchi and 'reflashed'. I followed several different tutorials and other instructions, but after removing the 2 and connecting it back to the television and power-on; gives me a black screen without error messages. Just a no signal message from the television. Even pressing the power button on the Nintendo to 'off', leaves the power light lit. This case is also the same after synchronizing 'successfully' with the power light remaining on. Even during synchronization, the green light in hakchi appears at the corner, but instead of staying green, it changes to red after pressing okay in the 'finished' dialog. I already have a safe copy of the dumped kernel, so i've never dumped it again. But generally what I do is flash original, then custom, and then add necessary modules. After the modules, I choose synchronize. If I try to start with flashing custom, I get a ramdisk unpack error. This doesn't happen if I start with flashing original. I am nearly tired of flashing this thing and even adding any other games or other console modules. What i'm most worried about starting from scratch, is re choosing box art, and game genie codes; and unselecting the few from the 30. I am almost to the point of happily paying someone to properly flash my system for me. This system last successfully played, less than 2 days ago.

**Comment by youngtune27** [comment]
When you say you removed the games and then reflashed what do you mean exactly? You should just uncheck the games you don’t want and resync. And that’s then if yoU didn’t want it to even show up on hakchi on the computer then you’d just right click and delete it. No need to reflash kernel. It would take 1 min if that. Shouldn’t even need to look at a tutorial.

**Comment by ProjektRF** [comment]
Whats the file size on the original kernel you have? If its not 2.6 MB then its the wrong one. If it is that size then I'm not too sure what the issue would be.

**Comment by Dominik92B** [comment]
2 important things before the wall of text:
- sorry if it took me this long to try your suggestions from yesterday
- issue solved!!!!!! So thank you all for your moral support/help/ideas/etc.

Short summary of the discussion and of what I've tried: First I've tried what youngtune27 suggested without any result. Then ProjectRF pointed out that in his case the problem was caused by his kernel not being the original one... So I've searched my PC, found a folder named 'original kernel', replaced the kernel in the Hakchi2 folder with the one found there and then repeated the process suggested by youngtune27. Again, no result. When ProjectRF said the original kernel was 2,6mb I checked mine and realized it was 3,2mb (don't know whether there are regional differences between US and Europe - I live in Europe by the way). Anyway, I downloaded the 2,6mb kernel, repeated once again what youngtune27 said and it worked!

**Comment by youngtune27** [comment]
That’s great news man! Ya the process I said wouldn’t work without that 2.6 original kernel. That’s why I said you need original factory kernel. So I’m glad you got ahold Of that! Just remember that anytime you have issues this procedure helps clear up issues.  If you ever upgrade hakchi its best to do it in a new hakchi folder and move your stuff over. When I first tried hakchi first time I lost my original kernel but I had another snes so I got it from that. Sorry this has gone on for you for a couple weeks! I wish I would have looked earlier to try and help you.

**Comment by Dominik92B** [comment]
I was so sure that I was actually using the original kernel that I started to believe it was some kind of bug in the new Hakchi2.

Also, different "issue", but I'll ask you here without creating new topic... I did the USB mod and a couple of roms that were working before doesn't work anymore. Most of them are NES games: the screen turns black and reset/power do not work. I know retroarch used to cause this... But there are no special characters and I have the latest retroarch. Any idea?

**Comment by ibmp200** [comment]
alright, on removal, i selected the games with the mouse, and pressed the delete key, therein removing them from the hakchi list. i didnt think/know about just removing the check from the box would 'remove' it from appearing in the console. --but i suppose that is no different than 'removing' some of the original 30, which in itself is just with or without a check. the 30 cant 'permanently' be deleted.

the dump file size isnt 2.6, it is 3.45. i know that i had saved a copy of the dump, but i cannot find it now. all i have in my hakchi dump folder is the kernel file of 3.45 megabytes. if i had another smaller version, i may have accidentally deleted it after first dumping. mind you, this kernel dump is for the NES Classic, and not the SNES Classic. would the two console's dump files be the same size or different? and neither do i have the super nintendo classic, just the nintendo. if i use/download another kernel, like the 2.6 megabyte version, how would that affect the games ive added and the ones of the 30 i dont want? would i be using someone elses 'list' of games, downloading a different kernel than using my own?

i use the tutorials because although i am quite computer literate, the whole of the the 'flash' process can be confusing, especially the order of things. --flashing, dumping, synchronizing, installing modules, console power lights, the red/green light in the hakchi window.... i think i have also tried just using the synchronize button, but been met with it still needing drivers, even after they are installed. i used the web installer and hakchi is installed into my documents folder; per executable default. not the desktop or the root drive.

**Comment by youngtune27** [comment]
Snes and nes should have different original kernels. I have nes and snes Classic. You should use 1 hakchi folder for nes and whole separate for hakchi folder for nes classic. You can download someone else’s original dump cause it would be the same as your original that has the 30 games. Download this dump and see if works. Just go into hakchi folder and replace the 3.4 dumped with this one. http://www.filedropper.com/kernel_1

**Comment by youngtune27** [comment]
Then go up this page a little and follow my steps. Your games will still be in your hakchi. So you won’t lose them. But right now you have a modified kernel dump instead of the original factory one. Don’t worry it’s easy to lose it. You’re not the only one.

**Comment by youngtune27** [comment]
Dominik92B I haven’t tried usb yet for that sole reason. Too many people getting issues. Maybe projektrf can help since he’s tried it!

**Comment by ibmp200** [comment]
okay youngtune. what if i just put the games back in there that i 'deleted' and simply removed the check? if i flashed original kernel, and then custom kernel; added the games again, removing their checks and finally pressing synchronize, would that get it to work properly?

and would i also need to reinstall the modules, or wouldnt they already be there?

is this wrong size kernel what is causing the power light to remain on during synchronization, as well as staying on when the power switch is off once connected to the television?

**Comment by youngtune27** [comment]
ibmp200 I meant one folder for nes classic and one for snes Classic sorry. You could try that and see if it fixes it but I don’t see why adding those 2 back would help. Okay so your game list on hakchi doesn’t mean they are on the console. the original 30 can be hidden and not taken off by unchecking them. That is not the case with all other games. You could have 1000 games on hakchi. 900 unchecked and only 100 checked and synced on the system. If it is synced with the games unchecked then the game is no longer on system. BUT your saves stay and aren’t erased in case you put game back on again, unless you factory reset then saves then are gone. Everything you need to do is within the hakchi program itself Besides swapping the kernel out. Do that first in the hakchi folder. Then open hakchi and make sure you have the right system selected under hakchi settings. Make sure it’s nes classic and not snes Classic. Then uninstall all mods if you think they aren’t installed. Then up top under one of the tabs click Uninstall hakchi. Then flash the original kernel I told you to download. Then turn system on tv and factory reset it. If you don’t wanna lose saves then try skip that but I recommend. And then go back to hakchi and flash custom kernel and then install your mods and then sync games. Hopefully it’s the solution.

**Comment by youngtune27** [comment]
Even not if*

**Comment by ibmp200** [comment]
well i said adding in the event the larger kernel file has the games that were removed, part of it; therein adding them back (while removing the check afterward) would equal a 'matching' kernal flash.

but, if i download that smaller kernel and replce my larger one, would i still hafta add all my games again, and select box art and game genie cheats again?

i dont even use the console to play other console games. just nintendo games (8 bit) that i enjoyed playing. i have a computer and other emulators that i prefer to use than trying to cram them all into this neat little gadget. im sure it works great and all, but using hakchi for all those consoles and arcade stuff, is not for me. i prefer things 'separate', instead of things combined nicely like this. --i may eventually come around to putting all my games/systems into the classic. but some other day....

**Comment by youngtune27** [comment]
All the games and images etc will still be on hakchi. You won’t lose it. Just have to put them right back on. No your just replacing your original dump. You don’t have to redo setup etc. just follow my steps to clear stuff out and put what you want right back on after.

**Comment by ProjektRF** [comment]
I got the usb part set up and so far no issues with games not playing. Dominik92B maybe try getting those games to run from a different module besides retroarch?

**Comment by Dominik92B** [comment]
Don't know why my NES roms stopped working in the first place, but I've tried to download new roms and replace the old once before trying more invasive approaches and everything seems to work smoothly now. 187 games from NES, SNES, GB, GBC, GBA, N64 (most of N64 games I've tried don't run well, only few works properly - speaking in general), Sega Master System and Sega Genesis... All seems to work, hopefully I won't find more issues playing :)

**Comment by ibmp200** [comment]
i forget what i did now, but i got it working again. i did replace the kernel with the smaller file, and flashed original and then custom. i then added the games i deleted, and finally synchronized. i think one of what caused my failure before, was not following the synchronization instructions correctly. i thought it had to be in developer mode, and that wasnt working. pressing just power got it to work

so the games i didnt want are simply without checks and dont appear on-screen. it all works now. thank you all for your input.

i was wondering something else off topic about hakchi modifications. i know that folders and icon/graphics can be modified, as well as background music and thumbnail removal. but i am wondering about moving/removing some of the graphics/artwork that appear. like flipping the top to the bottom/bottom to top of the console graphics; per the attached image. and 'removing' the entire settings menu from the top where language, display, manuals and such are; also per the attached image. and their removal, such that pushing the up button doesnt do anything. while leaving of course the down button to access save states. and finally also hiding the 'hints' of what controller buttons do that appear just above the bottom half of the console graphics.

is it possible to create such a modification to install through hakchi?
![change](https://user-images.githubusercontent.com/29873815/37455659-7ccde876-2835-11e8-9cd3-6b2a29704dbe.jpg)

**Comment by Mirrix16** [comment]
So I ran into this same problem (power not turning off and unrecognized from TV) after trying to adjust my game library on my SNES.  I initially set this up on 2/3 and haven't done anything with it since so wanted to add a few more games.  Unfortunately after I did I ran into this issue.  

Will selecting Uninstall Hakchi2 remove it and the games I have selected from my system?  Should I save off the games somewhere else before doing it?  

I flashed the original kernel and then installed the custom kernel of 2.30.  From there I added retroarch and snes9x2010 modules then sync'd some NES and SNES games (the same games I had on previously with only a handful of new ones).  Everything seemed to work correctly in terms of the system shutting down when turned off.

I hooked it to my TV and everything looked good.  Games and save states are all there.  SNES games appear to work without issue BUT my NES games aren't working.  I just get a black screen and then the unit doesn't turn off when I put the on/off button in the off position.  Why is this?  am I missing a module or is there an issue with the 2.30 kernel?  If I install the 2.21f with the same modules will my NES games work?  Is there an easy way to revert my 2.30 to 2.21 or do I need to install 2.21f and import then select all of the games i want?  

Thanks.

**Comment by Leesin2002** [comment]
Same here but i have mini nes.

**Comment by ClusterM** [comment]
Make sure that you really using original kernel. Can you say size of it and MD5?

**Comment by Mirrix16** [comment]
I corrected my NES black screen issue by deleting all of my NES games from hakchi and then adding them back by dragging ROMs into hakchi.

**Comment by Apd451** [comment]
Can some one send me.a copy of their original nes flash kernal.  I erased mine..
 Need help to restore my bricked nes

**Comment by Nanoskywalker** [comment]
Sure, This is the Last euro version, Mine works flowless with 2.3

[kernel.img.zip](https://github.com/ClusterM/hakchi2/files/2303893/kernel.img.zip)

**Comment by Apd451** [comment]
Thank you



Sent from my Sprint Samsung Galaxy S8+.


-------- Original message --------
