### ISSUE TITLE
font and game can't play

### ISSUE THREAD

**Issue by kabutokouji** [ClusterM/hakchi2#13]
i 'm using hakchi2 version 2,08 in mini famicom.  if using extended font, original tittle in mini famicom many font is missing. if not using extended font, original tittle is fine, buat add game tittle font is missing.

b-wings and wai wai world can't play in nes mini and mini famicom
Sorry, B-Wings uses mapper #185 but this mapper
is not supported by nes mini and game probably will
not start. do you want to add this game anyway?
wai wai world a same, mapper #23

please fix font and add more mapper. thanks

**Comment by soulctcher** [comment]
The emulator is not something that is currently being modified to "add more mapper(s)".  You cannot play these games without some sort of hack to change the mappers on the game.

The extended font may not work on the famicom mini the same was it does on the NES Classic because it may have different characters.

**Comment by ClusterM** [comment]
Disable extended font. It's for NES Mini only.
I have not Japanese fonts. You can create one.
