### ISSUE TITLE
Pokemon

### ISSUE THREAD

**Issue by hungryhippo69** [ClusterM/hakchi2#1307]
Been trying to figure out how to trade to myself (you can do with an emulator on your PC or phone but not on SNES). How do I transfer or convert the game data so it's playable on my PC, save that data, then transfer everything back to the SNES? Anyone have any ideas?

**Comment by Shoothimnow** [comment]
Please re-ask this question on a forum (not an program issues board) : https://www.reddit.com/r/miniSNESmods/

And please **close this issue** before you dissappear forever

**Comment by hungryhippo69** [comment]
Thanks for the threat

**Comment by Shoothimnow** [comment]
For the threat?  LOL, most people post here and then never reply back.  I was just stating that statistically 1 in every 50 people actually care to close their posts or ever post again.  They do a **one and done** post and never care to come back.  Honestly (and seriously), thank you for closing this as it helps the creator with actual issues with his software (glitch in code that bricks every system based on a specific install pattern / overheating issue due to CPU being overwhelmed / etc problems that every user is encountering).  

There was no threat, just saying before you disappear forever (do a **one and done** post), please close the issue =).  And you did, so thank you =)

But for the Pokemon issue, people on Reddit will totally be able to help out!
