### ISSUE TITLE
SNES Mini Original games don't work/no sound or glitched sound

### ISSUE THREAD

**Issue by Ozwa123** [ClusterM/hakchi2#1309]
Everything else works. All my other games I've added using the USB Host are fine, but for some reason I'm having issues with the original 21 games on the system. Some will load, some will not, some will load but the audio is messed up entirely, or no sound at all. I'm not too sure what's going on with all that since I've been following "Syndrom208" tutorial on syncing games to the SNES Mini via USB Host method. Any help would be greatly appreciated, thank you!

**Comment by Shoothimnow** [comment]
I would either uninstall everything and reinstall Hakchi2.  Otherwise, I would ask on a forum (instead of a program issues board) : https://www.reddit.com/r/miniSNESmods/

It seems you were able to install Hakchi2 just fine, but are having user error.  User error can be cleared up by asking on Reddit.

Please **close this issue** before you disappear forever

**Comment by Ozwa123** [comment]
ok i will, sorry about that
