### ISSUE TITLE
snes: Emulator in high-rez

### ISSUE THREAD

**Issue by codemeasandwich** [ClusterM/hakchi2#1316]
I was just wondering as emulators like [dolphin](https://dolphin-emu.org/) can emulate in higher resolutions. 
Would it be outside the realms of possibility to have the SNES classic emulator in 480 or 720p? I'm thinking games with the super FX chip could look really nice.

**Update:**
I found this
https://www.reddit.com/r/emulation/comments/5psp0b/high_res_super_fx/
They talk about how their 3D rendering is part the game and is send from the card to the snes as flash images.

**Comment by Shoothimnow** [comment]
Please ask questions regarding everything NES/SNES Classic related on https://www.reddit.com/r/miniSNESmods/

Please explain Hakchi2 issues that everyone is encountering and how to replicate the issue here on https://github.com/ClusterM/hakchi2/issues

This is an issues board, not a forum.  Not trying to sound rude, you are just in the wrong place.  Please **close this issue** before you leave.
