### ISSUE TITLE
Commit ?

### ISSUE THREAD

**Issue by nappymike** [ClusterM/hakchi2#146]
Ok this is probably gonna sound dumb but every time cluster makes a commit if i want the update that he makes do I need to re download the hakchi2 2.12 file to get it?

**Comment by baconcow** [comment]
In order to have the most up-to-date version of hakchi2, with the latest commit, you need to download the source files and build them with Visual Studio. The release (v.2.12) file will never change. The releases are decided by ClusterM and are based on whatever commits were done up to the time of release.

**Comment by nappymike** [comment]
Ok thanks for clearing that up
