### ISSUE TITLE
exec request timeout

### ISSUE THREAD

**Issue by s1204IT** [ClusterM/hakchi2#1550]
I get a screen like this and cannot proceed.
![image](https://user-images.githubusercontent.com/52069677/124920228-13329200-e032-11eb-964b-78d3f602a00b.png)
How can I solve this problem?
I have already installed CloverShell.

/* Since I am Japanese, I used DeepL to translate it into English. */

**Comment by L10N37** [comment]
Try latest version 3.9.2 by team shinkansen

Based on hakchi by madmonkey.

Coders:
Alexey 'Cluster' Avdyukhin
princess_daphie
DanTheMan827
skogaby

Translators:
Arabic: AluCarD
French: princess_daphie, JumpmanFR
German: Domi78
Portuguese: kONNEN
Spanish (Latin America): ReyVGM
Swedish: yeager

Sega Boxart and spine templates designed by TheWez1981 with backgrounds designed by HerbFargus and taken from the EmulationStation "TronkyFran" Theme

Inspired by the original USA / EUR Boxarts
JP Boxarts are my own design inspired by various real Boxarts, because there is no standard in the JP Boxart theme

Go check him out on FB: WH Creative Designs
https://www.facebook.com/TheWez81

Special thanks:
madmonkey and pcm720 for great help with everything.
Pete Batard/Akeo for libwdi & Zadig.
Thomas Bleeker for WinUSBNet lib.
bootgod for cartridge database.
NeoRame for Graphics.
Faustbear (u/faustbear) for additional folder graphics.
Nhakin for Game Genie database.
Adam Hathcock for SharpCompress.
BoneSoft software for ProgressODoom.
Gert Driesen for SSH.NET.
