### ISSUE TITLE
Mapper 11 games (wisdom tree)

### ISSUE THREAD

**Issue by BagginsKQ** [ClusterM/hakchi2#162]
Anyway to get these games working? Doesn't seem to work with retroarch default either. 

Tested Bible Adventures, Just loads to black and then goes back into menu.

**Comment by baconcow** [comment]
hakchi2 is not an emulator. You will find better support on the [ROM compatibility megathread at the nesclassicmods subreddit](https://www.reddit.com/r/nesclassicmods/comments/5mpyxg/is_my_rom_x_working_megathreadconsolidation/) or [Official hakchi2 GBAtemp thread](https://gbatemp.net/threads/hakchi2-nes-mini-very-simple-pimp-tool.456256/).

**Comment by BagginsKQ** [comment]
Baconcow I realize that hackchi2 is not an emulator I was asking about core compatibility itself. In particular with what retroarch adds to the system. 

Thank you for the thread however.

**Comment by baconcow** [comment]
Sorry. I was only attempting to help you by directing you to active discussion on these topics. Several other nearly-identical issues have been started and closed, on the hakchi2 repository. The only games that have been made working, in the past, were from already-existing mapper patches and mapper changes due to similarities between mappers. As mentioned by ClusterM, in the 2.12 patch, mapper patches have been dropped in favour of using retroarch for better NES support. Therefore, your only hope to get these games working is finding a working emulator to use with the retroarch module.

Did you tried the nestopia core from the retroarch module? It is not the default retroarch NES core and has to be installed.

**Comment by BagginsKQ** [comment]
Right I understand restroarch business somewhat... MOstly was using the default which is fceux Fxceum or something like that?

Hmm, maybe is there a way to switch between cores? --retroarch in the command lines (I'm using it for specific games, not global) seems to default to the fceuxm?

Is there other commands to force nestopia in cases it might be better for certain games?

As far as I know fceux's pc branch is definitely compatible with Bible Acdventures, etc... but it seems this version isn't. 

I hope at some point they also add the 'lua' compatibility to these versions too... The lua for MDBtroid is incredible....

**Comment by BagginsKQ** [comment]
https://gbatemp.net/threads/hakchi2-nes-mini-very-simple-pimp-tool.456256/page-303#post-7124461

BTW love this suggestion someone put up, for adding some more options to switch between cores...

**Comment by baconcow** [comment]
Since you have only used the default core, definitely install the nestopia module and try it out. I am not certain the details (at this time) regarding running only nestopia on a specific game (I only know how to set it to use for all games). I would suggest seeking that answer and looking for the the compatibility of that core for the games using the Wisdom Tree mapper (mapper 11). Good luck.

**Comment by BagginsKQ** [comment]
Did a test of nestopia PC version and Bible Adventures, and it doesn't likie it... So my guess the retroarch core isn't going to like them either.

**Comment by baconcow** [comment]
You may have a bad set of ROMs. I just tried my copy of Bible Adventures (Rev. 1.4) and it worked just fine on PC Nestopia v1.40. MD5 for the game is 4E5E60157E28BA0A9D536692AF99FE87.

**Comment by BagginsKQ** [comment]
That's good to know I'll have to try to hunt down a different version then. I think the version I got was from something called a  "goodset".... Will have to try to look for a no-intro version and test too...

**Comment by BagginsKQ** [comment]
And a no-intro version of Bible Adventures also works on the pc Fceux... Will have to retest in Fxeum as well...

**Comment by BagginsKQ** [comment]
Once I got no-intro versions all the Wisdom tree games now work.... straight out of the box automatically detected don't require any extra --retroarch command.

**Comment by baconcow** [comment]
I have had several issues with GoodNES ROMs. The MD5 hash I provided was from a No-Intro set, which is the recommended set to use. I use GoodNES only for translations or other hacks (which I often try to apply on No-Intro on my own). I am glad that you were able to resolve this.

**Comment by BagginsKQ** [comment]
Its weird sometimes no intros don't work for me either... they have c7 errors or something. Or someone 'categorized' the rom, and its nto really a 'no intro'... that's a pain.

**Comment by baconcow** [comment]
You may want to consider having your No-Intro set audited to ensure it is valid. It is out of the realm of help I can give you here. If you would like help with an audit, look me up on Reddit or GBAtemp.

**Comment by bfluryx1234** [comment]
Trying to clean up the bug reports.  If this issue can be closed, please do so.  Thanks.

**Comment by BagginsKQ** [comment]
It was closed blflury you just reopened it.

**Comment by baconcow** [comment]
I don't believe this one was closed.

**Comment by ClusterM** [comment]
hakchi is not emulator.
