### ISSUE TITLE
Black screen after flashing custom kernel

### ISSUE THREAD

**Issue by Bob74** [ClusterM/hakchi2#218]
I use Hakchi2 2.13e and my mini-NES won't boot after flashing custom kernel (black screen).
I can dump original kernel perfectly (I can reflash it to make the NES booting again).
I tried to flash custom kernel alone and to flash it by Synchronizing games -> still unable to boot.

I tried on two differents computers, tried with 2.13e, 2.13e debug and 2.12. Debug version didn't show any error.
Reading FAQ, I also tried redownloading the files with different browsers.
Also tried to change USB port (but still, dumping original kernel works).

I don't know what to do! Is someone else having this issue?

**Comment by SupahDave** [comment]
I'm unable to even get my unit into flash mode after flashing the custom kernel

**Comment by seanrox** [comment]
Ok, so you were able to get it back to factory kernal, so that's positive. When hakchi2 says "waiting for your NES mini" during the syncing, be sure to hold the reset button on the NES mini for at least 5 seconds... count it out slow like 1... 2... 3... 4... 5... then release it. When I had the same issue waiting longer before releasing reset made it work. Hope that makes sense.

**Comment by Bob74** [comment]
Thanks Seanrox, I made sure to wait at least 5 seconds but sadly I still get the black screen on boot.

**Comment by seanrox** [comment]
@Bob74 No problem. Bummer that didn't work for you. Maybe someone else can chime in with a possible solution. Good luck with it.

**Comment by Bob74** [comment]
Tried on a 3rd computer and it worked!
That's weird, all 3 computers uses Windows 7, the only difference is that I used Zadig Driver to install the driver on the last computer.
I guess it is solved now.
