### ISSUE TITLE
Demo mode : Mario broke some covers

### ISSUE THREAD

**Issue by black-pudding** [ClusterM/hakchi2#220]
When the Nes mini was in demo mode, I saw Mario punching somme covers making them disappear. Even when the demo mode was over those covers were missing (for example the Japanese Castlevania 3). I had to play the related games to see them back.

**Comment by maskedmaniac** [comment]
That's due to the shell.

On a stock NES Classic, when in demo mode, Mario jumps up and hits the box art for one of the 30 games, which starts a gameplay demo of that particular game. When you press a button during the demo, the menu will come back with all 30 games displayed. The shell will only play gameplay demos for the default 30 games, so if Mario jumps up to hit box art for a game you added, it will disappear.

Since the demo is part of the shell, and it only plays gameplay demos for the default games, there may not be a way to change box art for games you've added from disappearing when in demo mode.

I'd suggest either don't let the system stay idle long enough for the demo to knock out cover art for added games, or disable demo mode in settings.

**Comment by black-pudding** [comment]
Isn't that possible to define a default demo (or to launch SMB's one for example) for added games?

**Comment by maskedmaniac** [comment]
In my experience, it will only start a gameplay demo for one of the default 30 games, and only if it's one of the 30 games (or however many you set up in Hakchi2) currently displayed on that particular screen (again, due to the shell). Mario will cycle through the games currently shown on screen, and if he doesn't find one of the default 30 games, he'll hit box art for a game you added, causing it to disappear.

Even if it was possible to set the demo to play a game like SMB whenever Mario jumps up in demo mode, SMB probably isn't displayed in your menu with Castlevania 3, so if Mario hits Castlevania 3's box art and the system goes to play a SMB demo, the box art for Castlevania 3 will "break" (disappear), and you'll likely come back to the menu with Castlevania 3 still missing anyway.

Based on what I've read in Hakchi2's FAQs, the shell limits what can be changed using Hakchi2. Easier to just disable demo mode.

**Comment by ClusterM** [comment]
It's possible to create your own demos using clovershell tool. In theory.
