### ISSUE TITLE
Future Versions

### ISSUE THREAD

**Issue by B9KnM8UqQ2W2Vwk7uvZ7** [ClusterM/hakchi2#240]
Hi,

This isn't an issue but I thought that it was important to let you know this.

I thought it was worth commenting on what you said here...

_"Also I'm not sure that many people want new versions since hype train is gone :)”_

A lot of people, like me, are complete beginners at this stuff so we actually wait until there’s a new final build but that doesn't mean that we’re not really hyped for new releases. WE ARE!! It just means that some of us would rather wait until a release is out and we don't get involved on GitHub because we don't really understand anything about this stuff.

Trust me, a lot of people are excited for the work that you do and I thought it was worth telling you that because I don't want you to think that people aren't really hyped for hakchi and also the future versions. 

Thank you, to you and everybody else who has put work into this project. It really is appreciated by a lot of people!! :)

**Comment by abijanfar** [comment]
Injecting more HYPE!

**Comment by zlinx** [comment]
This project keeps me hitting F5 all the time.

**Comment by baconcow** [comment]
Definitely hyped. I download a lot of the GitHub versions and compile them to test them out. However, I wait until there is a final version before actually sending things to my NESCE. I follow this project daily and I am very excited for the future of it. More and more people are getting NESCE's, everyday, and I believe the popularity of this application will only go up, from here.

**Comment by black-pudding** [comment]
I'm TOTALY F.CKING hyped by the project and huge enhancements on each release! Until now the project is exponentially getting cooler and cooler.

**Comment by hpd4cl** [comment]
I have to agree.  I'm constantly checking for a new version, but doing so patiently.  I don't comment often, because I usually have nothing to add, except for my requests for new features (still want to backup and edit save states).  I do, however, greatly appreciate all of the hard work that everyone has done on this project, and can't wait to see what's next.  I also prefer waiting for finished releases rather than intermediate release candidates, and I definitely have no clue how to do what other people on here do, so also big thanks for making the process easy for the non programmers among us.

**Comment by B9KnM8UqQ2W2Vwk7uvZ7** [comment]
I'm closing this down now to avoid having an open issue, which isn't actually an open issue. 

I really do hope that is understood that people do appreciate what's happening here and that there is real excitement for the product, you only have to look on different forums to see just how much people are really excited for this and any future versions.
