### ISSUE TITLE
Getting error 'System.OutOfMemeoryException' when trying to sync games with 2.14b

### ISSUE THREAD

**Issue by DatSpacedude** [ClusterM/hakchi2#254]
![img_0298](https://cloud.githubusercontent.com/assets/26557141/24124785/be503930-0d9b-11e7-9455-143f2da36afa.JPG)
Process of syncing begins and prompt above sync meter reads "building folder structure....." for around 5 to 10 mins then error shows up. I'm sure I have correct hmods in folder. Never had a problem with 2.13e.

**Comment by KMFDManic** [comment]
I, and a few others have also encountered this "memory" issue.  It seems to run out of space when synching, leading to the error of running out of memory exception.  One person I helped was able to successfully synch at 249mb, without this error.  2.13e, they could synch up to 314mb.  Will need to do more testing on my end.  But, hopefully, this issue is resolved:)  I am thinking there may also be a workaround, with HMOD uninstall, etc.

**Comment by DatSpacedude** [comment]
Thanks for the reply and input. I'll try again at 250mb to see if that does it.

**Comment by KMFDManic** [comment]
I tested out my theory, and fixed this error.  There may be fewer steps involved.  But, this is exactly how I fixed the issue.  

1.  Flash to Original Kernel
2.  Uninstall Hakchi2 traces
3.  Uninstalled all HMODS
4.  Flash Custom Kernel
5. Synch 300mb of games, 
6. Success!

I just did everything I thought that would remedy the issue.  You can probably remove 1 or 2 of these steps, and still succeed!  But, this is foolproof!  Note:  You cannot install the drivers for the NEW transfer method, until you do custom flash, upon removing hakchi2 traces.

**Comment by DatSpacedude** [comment]
So I followed the steps you put and it did indeed work the first time I synced at 250mb. Then I tried to sync again, but at 281mb. This time I got the past results of getting the exception error, so I'm back to not knowing what is giving me this error. I'm going to try and sync without a certain game that I think is giving me troubles.

**Comment by KMFDManic** [comment]
I did further testing with this.  My NES Mini, I was able to get to 300mb, by following the above steps.  I tried helping another friend, but was limited on time.  His NES Mini is still stuck at under 300mb.  I am wondering if, on top of uninstalling hakchi2 remnants, past hmods, etc...the clovershell module for access to the mini, would help remove the "extra" files, once you know which ones to remove.  The oddity here, is that...while being able to flash at JUST 250mb on 2.14b, you can go right back to 2.13e and flash at 300mb, without issue.  Somewhere, somehow, there is a memory issue:)  What happens is that is started to build the folder structure, then it gets stopped upon trying to actually transfer the files, if over the memory limit.  Hopefully, it gets pinpointed.  But, for now, my steps worked on my Mini.  And, they should help others, as a temporary fix: til ClusterM gets to the bottom of things:)

**Comment by DatSpacedude** [comment]
Yea, I kept getting the same results after running various syncs with different mb amounts and memory wipes. The only way I was able to get the sync to get work was with the aforementioned methods you have pointed out above. For now I'm going to stick with 2.13e until (hopefully) we get a more reliable fix for this. Again, thanks for the help and input, highly appreciated.

**Comment by KMFDManic** [comment]
I streamlined my method, and can now flash at 300mb.  I need to run a few more tests, then I will post how I did it.

**Comment by DatSpacedude** [comment]
Awesome, looking forward to test myself.

**Comment by KMFDManic** [comment]
Ok, DatSpacedude, try THIS test for me.  See how things go.  I was able to do 3 NES Minis on my end, and it worked.  But, there is still a conflict on my friend's Mac.  Anyways...

Have all the newest HMODS from pcm720 and clusterm in the user mods directory, uninstall everything you think you've used before, or just highlight each and every one.  Once are all uninstalled, Try flashing at automatic with 290 mb or so, then with folders, if you use them.  Let me know the results.  I tested at 300mb with all 3 minis.  Only failure right now is the Mac connected NES Mini.  Clovershell crashed a few times on that setup.

**Comment by KMFDManic** [comment]
Upon further testing, HERE are the results...

-NES Mini, with NO HMODS installed.  Flash at 299 MB, which is recommended hakchi2 limit, per gui warning.  SUCCESS!!!
-NES Mini, WITH HMODS installed, ran at 299, same exact games as previous test, FAIL!!!
-NES Mini, WITH HMODS installed, 299mb MINUS exact size of HMODS that were installed, SUCCESS!!!
-NES Mini. WITH NO HMODS installed.  Flash at 299 MB, again, SUCCESS!!! THEN! Install same HMODS as earlier, SUCCESS!!!

So, then, what it comes down to, is this.

In order to flash at 299mb, you Cannot have HMODS installed, or they will directly affect how much data you can transfer.  BUT, if you flash at 299, THEN install the HMODS, things are fine.  So, anytime you need to reflash the 299 or similar, you must FIRST uninstall HMODS, then reflash games, THEN reinstall HMODS.  This is definitely a memory bug issue.  

Further testing, previous version, 2.13e.  Successfully flashed 299mb WITH HMODS installed.  2.14b Failed to flash same game set from 2.13e at 299, WITH HMODS installed.  

2.14b is GREAT, of course.  But, this is the little loophole you have to workaround to get a 299 flash.

In essence, you cannot have ANY previous stuff installed, so you need to uninstall all previously installed HMODS.  I tested the perimeter of NOT uninstalling hakchi2, and that appeared to have no effect on the 299mb.  Only the HMODS did.  It also appears that the exact size of your hmods, are how much less you can flash at, under 299, if you leave them installed.  This is not an issue in 2.13e.  I am still theorizing this is related to "space needed" for clovershell to apply the game set to the mini, file transfer wise.

**Comment by Driche** [comment]
Nice find. Great testing.

**Comment by KMFDManic** [comment]
I did further testing, as well. You have approximately 310 mb of working space to install games and HMODS. That is 299 mb of games on Hakchi2, then slightly less than 10 mb of HMODS. If you bypass this, any HMODS bypassing that slightly under 10 mb point, will fail to work. So, if you have 299 of games, then add 12 in HMODS, the FINAL HMOD/S installed will fail to load games. So, using this mini formula. Add up total size of all HMODS you plan on using, then subtract their total size from 300mb, and flash with only that amount of games. 20 in HMODS, Flash with just 280 in games. I have not tested how save states are affected (as in if you are at 310 limit, if save states fail or not). I mainly cared about overall games and HMOD installations. So, as of right now, save states are the only test remaining. But, for the sake of being on the safe side, I would just leave room for them, regardless.

**Comment by DatSpacedude** [comment]
I just finished testing using the methods you have given me and unfortunately, I'm still getting the same error exception result. I have tried syncing at 281 mb using 2.14 before uninstalling hmods and after uninstalling hmods. I have tried uninstalling hakchi from nesmini completely and reinstalling everything from there. I've tried compression toggled on and off when syncing, flashing the original kernel then going back to custom before syncing. I even went back, uninstalled everything I could and returned the nesmini back to factory settings. Even after all that I'm still getting the same error. Back to 2.13, yet again. Really wish this working or me, takes me about 45 to 75 mins to sync each time with 2.13, sometimes even longer.

**Comment by KMFDManic** [comment]
Yes, you have an exact point you are able to successfully flash at.  Once you arrive at that number.  You have to take into account any HMODS you plan on installing, and DELETE that amount of MB from your total successful Flash Number.  In my case, I laid out every hakchi2 version I ever used, and opened up each and every one of them, uninstalling every HMOD that I previously used in each of them.  THEN, I uninstalled hakchi2.  Once I was back to factory spec, and reflashed the custom mod.  I was able to flash at 299.  Unfortunately, different people seem to have different results, depending on which hmods and hakchi versions they previously used.  It is just a bug you have to accept, for now, if you want fast flashing:)  I am sure Clusterm will fix it soon enough!

**Comment by baconcow** [comment]
Thanks for testing this.

**Comment by ClusterM** [comment]
It's normal for 32-bit version of Windows. I'll try to optimize memory usage.

**Comment by KMFDManic** [comment]
Thanks clusterm.  I do use 64bit, which is why I max out at 309 mb. 32bit users I helped out max out at 50mb less than that.  I knew the amazing quick flashing ability would likely need to pull system resources somehow.  Still, fantastic that the lightning quick flashes are even possible!!  Despite you saying the "hype train" is gone, you will remain to have your dedicated fan base.  Thanks for putting so much of your personal time into this project.

**Comment by KMFDManic** [comment]
As a final note, depending on whether you are on a 32 bit or 64 bit operating system, you will get about 250 mb or less max flash ability on 32 bit, and 299 or less max flash ability on 64 bit.  This is determined by the inclusion of exclusion of previous save states and hmods  So, If you are on 2.14b, figure out what size your hmods take up, and flash at 250mb - that for 32 bit, or 299 - that for 64 bit.  If you use save states, expect to lose up to an additional 20 mb.  So, factory settings on mini, to clear the save states, or subtract to compensate for save states.  Clusterm is currently working on memory optimization for this bug.  So, this is your best course of action til then:)

**Comment by ClusterM** [comment]
Fixed. Please wait for the next release :)

**Comment by DatSpacedude** [comment]
Thank You Cluster for the quick fix, hope it works for my problem and thanks Manic for all the testing and time you put into finding out why this certain error occurs. Looking forward to the new release.

**Comment by KMFDManic** [comment]
No problem at all.  Cant have solutions without test results:)
