### ISSUE TITLE
Sort by console type

### ISSUE THREAD

**Issue by SupahDave** [ClusterM/hakchi2#262]
Can you add the ability to sort the games list by console or just have dividers to indicate the different ROMs?

**Comment by baconcow** [comment]
Just thought I would link [my issue](https://github.com/ClusterM/hakchi2/issues/249), for notification purposes, as it is asking for something similar (indication of console, in the games list).

**Comment by burnjx** [comment]
This was posted as a Pull request with a couple other nice features: https://github.com/ClusterM/hakchi2/pull/199

I'm hoping it gets added in a future release.

**Comment by baconcow** [comment]
I think I remember elierodrigue mentioning that they were going to make some changes again.

**Comment by KMFDManic** [comment]
I actually addressed this issue since the advent introduction of RetroArch.  I added a preface (in hakchi2 gui, itseld) to each game name, to classify its game type.  Examples...

2600: Asteroids 
7800: Pole Position II
ARC: Michael Jackson's Moonwalker
GB: Super Mario Land
MD: Altered Beast
NES: Blaster Master
PCE: Legendary Axe
SMS: Alex Kidd in Miracle World 
SNES: Super Mario Kart

You get the idea.  It takes 20-45 min to do this to an entire set.  Copy and past NES: with a space,  etc. Directly before each game name.  Close and reopen hakchi2 sporadically to see new highly arranged ordering.  It looks fantastic and is very manageable.

**Comment by SupahDave** [comment]
Yeah, that's not what I'm looking for but thanks for your contribution. Some of us already have 2000+ mixed roms loaded into Hatching so that would take days to go through and decipher it when it would probably be easy to add a couple lines of code to do it automatically and actually have it sectioned off

**Comment by SupahDave** [comment]
baconcow, your idea would work very well also. I like the idea of merging the folder window with the main window

**Comment by KMFDManic** [comment]
Haha, took 45 minutes for me to do 1700 games.  It is, at least, a working solution til hakchi2 has ig as an option.

**Comment by baconcow** [comment]
This issue can also be easily solved by using a ListView form with multiple columns instead of CheckedListBox form, for the game list. This would allow multiple columns of data (i.e. Console, Emulator) that could be used for easy sorting. Unfortunately, as evident by my previous code submissions not being used, I am not the best coder and would likely butcher any attempt at adding it myself.

**Comment by SupahDave** [comment]
Very good point, baconcow! I'm sure that would be even easier to implement
and would do the trick.

On Mar 23, 2017 1:21 PM, "baconcow" <notifications@github.com> wrote:

This issue can also be easily solved by using a ListView form with multiple
columns instead of CheckedListBox form, for the game list. This would allow
multiple columns of data (i.e. Console, Emulator) that could be used for
easy sorting. Unfortunately, as evident by my previous code submissions not
being used, I am not the best coder and would likely butcher any attempt at
adding it myself.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ClusterM/hakchi2/issues/262#issuecomment-288795268>,
or mute
the thread

**Comment by ClusterM** [comment]
It's planned.

**Comment by SupahDave** [comment]
Thanks, Cluster!
