### ISSUE TITLE
C8 under 2.15

### ISSUE THREAD

**Issue by black-pudding** [ClusterM/hakchi2#289]
I had a C8 error under hakchi2.15 and retroach-clover 0.7.
I was testing shaders under snes9x2010 and mame2003 then back to the folders were it became to be very slow to get out/get in the folders. I tried to turn off the NESC and then a C8 error occurred.
I tried again to turn off the NESC. It worked. So I turned it on again and everything was back to normal.

**Comment by KMFDManic** [comment]
Up til 2.15 with Clusterm's "possible" c8 error fix on folder browsing, it has been a harmless error that reverts once memory is cleared upon a system shutdown.  You may or may not see this error again, or if you do...not necessarily often.  The main thing you can do is followup with more "test" results, as far as if it occurs again, and if it seems to have a direct cause, rather than be random...THEN, it is something that may potentially be fixed:)  Debug logs help!

**Comment by black-pudding** [comment]
I had a 2nd C8 error having used hakchi2.15 and retroach-clover 0.7. It happened while I was trying to load a save point of Progear under fba_cps2. Once again the turn off/on method worked fine.

**Comment by Drakonas** [comment]
Closing this as it is probably a corrupt install. OP: Please respond if you are still having this issue.
