### ISSUE TITLE
msx bios files

### ISSUE THREAD

**Issue by vinnyl69** [ClusterM/hakchi2#290]
installed module fmsx to see if coleovision games will play.   hakchi indicates the below bios files are needed.  any direction where they can be found?  i have had no luck searching
MSX.ROM
MSX2.ROM
MSX2EXT.ROM
MSX2P.ROM
MSX2PEXT.ROM

thanks!!

**Comment by KMFDManic** [comment]
colecovision would only work, if you had the colecovision bios installed.  I did make a post that msx emulators tend to have support for colecovision due to the similar architecture.  BUT, the bios will still be needed!  If it makes you feel any better, I DID get colecovision working on the MINI, a different way!

https://www.zophar.net/consoles/gameboy/coleco/cologne.html

You would use the GBA core to run the CUSTOM Colecovision ROM you make:)  You will STILL need the colecovision bios, and have to manually point to it in the cologne program.  I tested this out with a GBA emulator, and it works!

**Comment by vinnyl69** [comment]
thank you for the reply!  unfortunately, that is past my level of knowledge.  i found the coleco bios;  and have two different games;  one is .rom; other is .exe;

**Comment by KMFDManic** [comment]
You can contact me on Reddit, I am u/MDFMKanic there.  I frequent https://www.reddit.com/r/nesclassicmods/

Setting up Colecovision isn't as ridiculously difficult as it may seem.  But, you should still want to test the waters with a few other hmods first:)

**Comment by ClusterM** [comment]
This is not RetroArch repo.
