### ISSUE TITLE
Hakchi Helping Hand 1.0 release

### ISSUE THREAD

**Issue by elierodrigue** [ClusterM/hakchi2#302]
https://github.com/elierodrigue/Hakchi_HelpingHand/releases/tag/v1.0

Have a look.
Allow you to compress all games, even the NES ones
Allow you to make each game name unique. When duplicate games found for the same console, it will add the filename difference.
Allow you to cleanup game names. Remove extra space and underscores.
Allow you to fix rom names. It will rename all rom files to its game code. Avoiding some crash with special characters. Make sure you distinguish duplicate games first.
Clovershell console. Let you play around with a shell.

**Comment by KMFDManic** [comment]
https://www.reddit.com/r/nesclassicmods/comments/648uoq/easier_compression_for_nes_games/

**Comment by Driche** [comment]
Used it. Went from approx 298 to 267MB.

Nice work! And Thank You!

Sent from my iPhone

On Apr 8, 2017, at 7:46 AM, elierodrigue <notifications@github.com<mailto:notifications@github.com>> wrote:


https://github.com/elierodrigue/Hakchi_HelpingHand/releases/tag/v1.0

Have a look.
Allow you to compress all games, even the NES ones
Allow you to make each game name unique. When duplicate games found for the same console, it will add the filename difference.
Allow you to cleanup game names. Remove extra space and underscores.
Allow you to fix rom names. It will rename all rom files to its game code. Avoiding some crash with special characters. Make sure you distinguish duplicate games first.
Clovershell console. Let you play around with a shell.

**Comment by tjm694** [comment]
Wow!  Went from 283 to 178 megs.

**Comment by KMFDManic** [comment]
BUG report...MISSING 2 vital command line arguments, that are crucial to running NES games compressed...

/bin/nes /CLV-H-CNXBG/CLV-H-CNXBG.nes.7z is MISSING

/bin/nes /usr/share/games/nes/kachikachi/CLV-H-CNXBG/CLV-H-CNXBG.nes.7z

as WELL as...at the end, --retroarch --fceumm OR --retroarch --core nestopia

like so...

/bin/nes /usr/share/games/nes/kachikachi/CLV-H-CNXBG/CLV-H-CNXBG.nes.7z --retroarch --fceumm

Games cannot run using retroarch in compressed form without these command line arguments.

You did an excellent job with the compression technique.  So, I know it should be very easy to add these additional arguments as choices..  Choice between --retroarch --fceumm OR --retroarch --core nestopia, would also be very nice:)

MY post on reddit...

EDIT: The compression for the NEW Method WORKS great! But, it is missing a step (command line arguments!). I tested the compression! But, I did not realize it didn't take care of the command line arguments! So, here is how to fix it! I will inform him that he missed this vital step so that he can do an update to fix it! I apologize for any inconvenience!
Copy Exe into Games folder
Choose option to COMPRESS ALL GAMES
NES games require ONE more step...command line arguments that need added...Here is an example of 1942.
/bin/nes /CLV-H-THQIF/CLV-H-THQIF.nes.7z
AFTER /bin/nes/ you need to add /usr/share/games/nes/kachikachi, so it SHOULD be
/bin/nes /usr/share/games/nes/kachikachi/CLV-H-CNXBG/CLV-H-CNXBG.nes.7z
AND, at the VERY end, you need to choose the CORE, so it will be...
/bin/nes /usr/share/games/nes/kachikachi/CLV-H-CNXBG/CLV-H-CNXBG.nes.7z --retroarch --fceumm
or
/bin/nes /usr/share/games/nes/kachikachi/CLV-H-CNXBG/CLV-H-CNXBG.nes.7z --retroarch --core nestopia
You can ALSO do THIS for each game...
/bin/nes /usr/share/games/nes/kachikachi/CLV-H-CNXBG/CLV-H-CNXBG.nes.7z
MAKE sure to install RETROARCH HMOD, by itself! Then, you can install USE NESTOPIA, and that should take care of the END command line argument!
If anyone needs help fixing their set, private message me! I will help you out:) And, I am now going to post so he realizes he missed the command line arguments!

**Comment by elierodrigue** [comment]
Fixed in 1.1

**Comment by KMFDManic** [comment]
Thanks for the quick code fixes!  Looking forward to future versions!
