### ISSUE TITLE
No Issue, just an Info in case the community missed it... :-D

### ISSUE THREAD

**Issue by donlent** [ClusterM/hakchi2#329]
Hey guys!

Did you notice that Cluster updated the FAQ and statet the following?

![image](https://cloud.githubusercontent.com/assets/11975745/25181681/977dd5e0-2512-11e7-8a91-0f70f054549d.png)

As you can see Cluster is asking for some helping on re-designing the GUI.
I've seen that @elierodrigue (https://github.com/elierodrigue) once did "fork" the project and redesigned a couple of things.... maybe he or somebody out there that is also an experienced developer can help?

I think everybody here is waiting for the possibility to sort / re-arrange the games by console type, etc...

Just thought to share that here in case somebody missed it. :-)

**Comment by elierodrigue** [comment]
The pull request with tabbed rom browsing, system info tab and by system folder creation is still there : https://github.com/ClusterM/hakchi2/pull/199

**Comment by baconcow** [comment]
It seems that there are too many conflicts between the pull request and the current commit. This may be why ClusterM is not using it.

**Comment by ClusterM** [comment]
It will be very helpful if community will just "draw" concept design at least as image. I need help with concept ideas.

There are what I want:
* We can read NES Mini's memory, so it will be cool to sync to both ways - read current directory structure on NES Mini and dump games to local database.
* Maybe we should use real-time file transfer instead of "sync"? Transfer games instantly after drag-and-drop just like local files?
* Games database should be displayed as tree, not just a list with checkboxes. It will be cool to sort games locally, drag and drop folders into hakchi2 keeping directory structure. 
* We need a way to edit games settings in local database as well as games already writed to NES Mini.
* Inside NES Mini every game keeps as folder, not just a file. This folder can contain some additional data. So it's good idea to "expand" game into files.
* So wee need to display "local tree", "remote tree" and properties of selected item(s) at the same time in one window. Maybe make some GUI elements configurable, add ability to hide some panels?
* Multiselect and group operations - download covers for selected games, compress/uncompress selected games, etc. Compressed games should be marked someway. 
* Automatic directory structure creation (just like in Folder Manager now but also with sorting by console type).
* Display available save-states directly inside games-list with ability to export, import, delete, view screenshots.

I can't imagine a GUI with all this features.

**Comment by piklz** [comment]
The wii u helper app is approaching something you require in terms of gui feel /trees and nodes and remote syncing features etc and looks pretty nice too with floating tabs ..but would never work well on a tiny laptop screen like I have(but hakchi does fit with its shortcut keys and minimal interface )  but if we are going fancy then look at the pics online for https://www.wiiuusbhelper.com app gui it's very nice to use when coping with many wii u disc folders/files

**Comment by elierodrigue** [comment]
here's what i can suggest : 
I'll build something within helping hand, from there, if community likes it, ill integrate in hakchi2.
I can build a live tree view to edit folders and manage them, with a way to fetch from nes classic as well as only pushing the difference. I'll start with just local database however as I'm not fully confident in the way to package files on the nes classic. Should be fairly straight foward but the folder structure doesnt seems that intuitive.

**Comment by elierodrigue** [comment]
i'll try to make a sketch of what i have in mind later today

**Comment by donlent** [comment]
@ClusterM & @elierodrigue guys you're just amazing!
Really wanted to thank you both for your commitment!!
All the best!!

**Comment by elierodrigue** [comment]
Its been a while but here's a screenshot of my current local version : 
![image](https://cloud.githubusercontent.com/assets/2980364/25898660/0ec91378-355b-11e7-854a-4ce386535d36.png)

![image](https://cloud.githubusercontent.com/assets/2980364/25898690/3015c1a2-355b-11e7-9a04-65bf08ebec7a.png)

I'll need @ClusterM  to merge my 2 pull requests however before being able to do one for this fix. It required me a lot of internal reworking / cleanup to be able not to make this an hacked job.

**Comment by elierodrigue** [comment]
Pull request with that treeview created....

**Comment by donlent** [comment]
Hi @elierodrigue 

GREAT JOB! In my opinion it really looks nice and functional. Probably this is just what most people need.
Hopefully @ClusterM will acceppt the suggestion. :-)

Best regards

**Comment by elierodrigue** [comment]
feature is now merged.
