### ISSUE TITLE
hekp lost orginal Kernel

### ISSUE THREAD

**Issue by illexio** [ClusterM/hakchi2#335]
computer crashed right after modding nes anyone have the original kernel ? thanks in advance

**Comment by seanrox** [comment]
Attached

[kernel.zip](https://github.com/ClusterM/hakchi2/files/950509/kernel.zip)

**Comment by illexio** [comment]
Thanks

**Comment by seanrox** [comment]
Happy to help.

**Comment by illexio** [comment]
maybe you can help for some reason I can't mod my nes now.. I had it modded... but realized super mario bros wasn't in my play list so attempted to reset it... and remod it now nothing I do will add any games all I have at this point is the original 30 ? any ideas?


    On Monday, April 24, 2017 1:34 AM, Sean <notifications@github.com> wrote:
 

 Happy to help.—

**Comment by seanrox** [comment]
Please close this issue since you needed the original kernal which is now resolved so we can keep the issues clean, tidy and on topic. As for not being able to add more games, check the FAQ and do the steps like the first time you've ever used the program. If that doesn't help, open a new issue for your problem. Hope that makes sense.
