### ISSUE TITLE
50hz PAL / 60hz NTSC Rom Problem

### ISSUE THREAD

**Issue by FrankTheSNESTank** [ClusterM/hakchi2#455]
Hey Cluster, can you confirm the Problem with PAL (50hz) Roms on the SNES Classic Mini with Sound and Picture/Speed Problems? Is there a way to patch a PAL Rom to NTSC? Or is the Emulator in the SNES able to Switch bitween PAL and NTSC?

Thank you!

Greetings.

**Comment by Kevoot** [comment]
Right now games are launched through retroarch, which afaik supports both PAL and NTSC ROMs. To answer your question though, ROMs need their own NTSC <-> PAL patch if using Nintendo's SNES emulator.

**Comment by FrankTheSNESTank** [comment]
The Question is does the real Emulator on the SNES can run at 50 hz PAL? Otherwise you have sound and picture Problems (too fast/stuttering). Retroarch can do both. I think this can the be the Thing why are only US Roms for the EU Customers on the SNES.

Patching is only removing the Region copy Protection. But a pal 50hz rom is still a 50hz rom after doing this.

**Comment by Kevoot** [comment]
Depends on the patch/roms. If you look at certain patched PAL ROMs, they absolutrly run 60hz, Terranigma for instance.

**Comment by emufrance** [comment]
The real Emulator on the SNES run at 60 hz. You can apply ips patch PAL to NTSC (differents patches if HiRom or LoRom).

**Comment by Dark-Akuma** [comment]
Has anyone besides me thought to try changing byte 0x00 of the second header from 0x3C to 0x32 for PAL ROMs, rather than trying to hack the ROMS themselves to run at 60fps? 

Byte 0x00 in the second header is for emulation speed. 0x3C = 60, 0x32 = 50.

**Comment by mcintyre321** [comment]
@Dark-Akuma please keep us updated if you get this working

**Comment by Shoothimnow** [comment]
This really doesn't belong here.  Canoe and RetroArch problems don't belong in the **Hakchi2 issue boards**.  If you were able to install the games to the system, then Hakchi2 is working.

This issue be closed to clean up clutter and be continued over on reddit : https://www.reddit.com/r/miniSNESmods/

**Comment by Drakonas** [comment]
This needs to be discussed on Reddit as Shoothimnow stated. There are already many patches for making PAL roms run on the EUR and USA SNES Classics with Canoe without issues. Both SNES Classic regions (EUR and USA) are built for the USA NTSC library, meaning PAL games WILL have problems because the console is trying to convert a PAL 50Hz signal to 60Hz. This always results with problems with any emulator not built to handle it (aka Canoe, which was only designed for NTSC 60Hz). Please resort to patches available for specific games in this list, and ask on reddit for other help. https://docs.google.com/spreadsheets/d/17RX45oDSm-bYXPOiGz_cIVYt5wtZCYnacbDFciegnRk/edit#gid=201431776
