### ISSUE TITLE
Brick console ?

### ISSUE THREAD

**Issue by Christophedlr** [ClusterM/hakchi2#457]
Hello,

I've test a flash kernel custom of my SNES Mini, and now the console not start. After reinstall original kernel, the console not start.

**Comment by roflcopter777** [comment]
You knew the risks when you did this.

**Comment by warlockv2** [comment]
Why cant people just wait...

**Comment by roflcopter777** [comment]
I'm sorry, but people knew full well the chances they were taking by not being patient. *shrug* Just wait till it's officially out, please.

**Comment by Christophedlr** [comment]
I was afraid, but finally I managed to get the console back. But I can not get the list of games I've added.

**Comment by roflcopter777** [comment]
Then wait till the official release is out.

**Comment by ghost** [comment]
You're using an unfinished piece of software.  That is your only issue.  Stop it!

**Comment by ghost** [comment]
I experimented with the current stable codebase, compiled the driver and ran the program in debug-mode and basically I can only dump the original kernel, rewrite it back and write the custom kernel to the device, does that does not seem to work atm, so I might fiddle a bit with the code (and if it bricks my console, I did it myself, but I have a spare ;-))
After writing the custom kernel, it's booted from memory, but then the system does not boot up in FEL mode and I can't add any games. Supposedly FEL is not needed anymore after custom flash, but the driver only seems to work on the device if booted up in FEL mode. If not in FEL mode booted, Windows does register it as a valid USB device with a CLV id (before flashing btw), but a driver is missing. I am going to try and write a driver to communicate with it when not in FEL mode. Don't know what I will be confronted with, but it's a nice experiment.

Btw, what I still don't understand is why the UBoot system is modded by adding the sunxi flash write command and the whole UBoot system is rewritten to the console before executing a single command. Is that really necessary? Do you really need to reboot the whole system and rewrite the bootcmd variable to execute a single command? I can understand this is the 'easiest' way from the source I can see it's a direct port from the C code to C# (no comments there, awesome that Madmonkey and you created this tool Cluster dude), so maybe I should ask Madmonkey for this, because I am curious.

Btw....can anyone explain to me why there are two different kernels and UBoots in the OSS package of the OEM of the device?

Sorry....I am misusing this post a bit ....

**Comment by Timminator87** [comment]
@Christophedlr How did you fix it ? I have the same shit... and my snes mini doesnt work anymore -.- feelsbad

**Comment by Christophedlr** [comment]
@Timminator87 I've reinstall original kernel (Flash original kernel), and flash custom kernel again.

**Comment by roflcopter777** [comment]
So having a backup of the kernel makes this brick proof?

**Comment by Timminator87** [comment]
@Christophedlr my Kernel Backup doesn´t work :/ can you upload your file please for me ? Without the Kernel file i can´t reinstall it. Would be nice

**Comment by Christophedlr** [comment]
@Timminator87 here is my kernel, but my MD5 Hash is not reference in Hakchi2 (Europe version)
[kernel.zip](https://github.com/ClusterM/hakchi2/files/1361841/kernel.zip)

**Comment by Drakonas** [comment]
I would personally advise against writing a kernel that isn't from your serial number. That is my 2 cents though.

**Comment by zimmertr** [comment]
Any luck @Timminator87 ?

**Comment by ClusterM** [comment]
Can you say me checksum of your kernel dump? Or send it to me. Seems like it's broken.

**Comment by Drakonas** [comment]
Closing this as there has been no response for 4 months.
