### ISSUE TITLE
Games Fail to Launch after 2.0.20.4

### ISSUE THREAD

**Issue by anicoletti** [ClusterM/hakchi2#507]
I was able to compile and get the custom kernel installed and launching games properly using 2.0.20.4, but after getting latest on rc5 (commit 7b484538) or higher, any custom kernel fails to launch any games (even default games). I can revert back to stock kernel and open games properly, even roll back to the rc4 commit (specifically c7fc8c59) and get the games to launch. Anyone else experiencing this issue?

**Comment by DonkeyKong** [comment]
I was able to restore the stock firmware to get things running again, then redo the kernel install using the debug version of hakchi and everything has worked perfectly since.

File version 2.0.20.14 of Hakchi is what got me up and running.

 See the closed issue here: https://github.com/ClusterM/hakchi2/issues/504

**Comment by anicoletti** [comment]
Tried that a few times. Might be my fileset though. I'm going to nuke my local branch and pull everything down again. For now I'm using my backup of my compiled rc4 and it's working okay. Thanks for the reply.
