### ISSUE TITLE
Large save files

### ISSUE THREAD

**Issue by warlockv2** [ClusterM/hakchi2#513]
Is there a way to fix the large save file sizes?  Game saves can be over 3 megs whike tge game is only 500k.  This may cause issue?  Maybe its rewind feature

**Comment by warlockv2** [comment]
Snes

**Comment by ClusterM** [comment]
It's because of rewind feature.

**Comment by Drakonas** [comment]
Some canoe games' saves will be this large. There is nothing that can be done. However, there was an issue that was fixed with the latest 1.0c build of retroarch, if you use that, that fixed every retroarch game save being around 2.4 or so MB when retroarch clearly doesn't use the rewind feature. This does not affect games run with canoe however.
