### ISSUE TITLE
[SNES] Stuck at "Waiting for device"

### ISSUE THREAD

**Issue by NeoTechni** [ClusterM/hakchi2#522]
https://i.imgur.com/Kdymk72.png
![kdymk72](https://user-images.githubusercontent.com/24502732/31314263-849320d6-abca-11e7-8862-c617841453f7.png)

**Comment by ClusterM** [comment]
https://github.com/ClusterM/hakchi2/wiki/If-you-have-any-problems

**Comment by NeoTechni** [comment]
I have the debug version, there is no such hakhi2 directory. Unless you meant the directory everything was put in, in which case it's 50 megabytes. 

Debug log is just

Base directory: H:\Consoles\NES and SNES mini
Loading config
Starting, version: 2.0.20.14
Loading games
Loading H:\Consoles\NES and SNES mini\data\nescarts.xml
Loading H:\Consoles\NES and SNES mini\data\snescarts.xml
SNES XML loading done, 786 roms total
NES XML loading done, 2150 roms total
Executing task: DumpKernel
Closing main form
Saving config

**Comment by ClusterM** [comment]
Weird. Do you have some antivirus software? Try to disable it.

**Comment by caseygrun** [comment]
Unlikely this will help anyone, but I had a similar issue. I was running hakchi2 on Windows 7 within a VirtualBox virtual machine on a Mac host. I dumped the stock kernel, flashed the custom kernel, and installed RetroArch just fine, but when I tried to add games I got stuck on the "Waiting for device." I tried restarting, refreshing to stock kernel, uninstalling, repeating the process to no avail. I tried disabling Windows Defender, no good. My debug output was also unrevealing.

The problem was actually fixed by installing the [VirtualBox Extension Pack](https://www.virtualbox.org/wiki/Downloads) and enabling a USB 2.0 (EHCI) controller, as opposed to a USB 1.1 controller which was the default (Go to Settings > Ports > USB, and select "USB 2.0 (EHCI) Controller"). I doubt NeoTechni has the same unlikely configuration, but if they do that might solve it. Or if they're somehow using a USB 1.1 port, that may be the problem. Good luck!

**Comment by Drakonas** [comment]
Maybe next time don't use a prerelease version for an older console. :)

**Comment by edelgado** [comment]
@caseygrun thanks so much! That worked!

**Comment by ignacionelson** [comment]
In my case, it was the USB cable. Replaced it and it worked fine after that.
