### ISSUE TITLE
Zombies ate my Neighbours  Black screen and exits

### ISSUE THREAD

**Issue by DecanFrost** [ClusterM/hakchi2#532]
Hackchi2 2.20
     Flashed Custom Kernal,  added Retroarch and Snes9x2010 mods
       
I have 200 games installed plenty of room free still and a few games not working
    Zombies ate my Neighbours  Black screen and exits   

I have tried with stock SNES emu and added --retroarch command line to the game as well tried in global command line.    same effect block screen and then exits to main menu after 10 secs

**Comment by explosiveaction** [comment]
This is confirmed working on my Australian SNES CLV-301. I just played a game of it.
Rom: Zombies Ate My Neighbors (USA).sfc

**Comment by ghost** [comment]
Works for me. Super Famicom Mini. No-Intro version of the ROM.

**Comment by DecanFrost** [comment]
so it i readded that game and a few others i found to be black screens or c7 errors and they are now working..   however Secret of Mana,  Star Ocean and Street Fighter Alpha 2 wont work still

**Comment by Jamieasy** [comment]
I'm using the stock emulator and Zombies Ate My Neighbors runs fine using the USA ROM

**Comment by Drakonas** [comment]
@DecanFrost Secret of Mana requires a preset ID change (CTRL+ALT+E -> 10B0), Star Ocean will never run on Canoe due to an unsupported chip requirement, and Street Fighter Alpha 2, while using the same chip as Star Ocean, was using the chip for something that it didn't need to, and has received a patch to fix it: https://www.reddit.com/r/miniSNESmods/comments/760w0v/list_of_canoe_compatibility_patches/?st=j98xrfmz&sh=354e5524 The rest of your roms not working are probably due to other incompatibility issues, bad roms, or having too many games on your console.
