### ISSUE TITLE
[SNES] Workarounds in progress for non working games

### ISSUE THREAD

**Issue by codex785** [ClusterM/hakchi2#557]
Street Fighter Alpha 2 seems to be working
https://www.reddit.com/r/miniSNES/comments/74dc3c/snes_classic_hacking_how_is_the_progress_going/

**Comment by Linkinworm** [comment]
I dont have a reddit account but i can confirm that vortex is working currently says unknown on that page

**Comment by Dark-Akuma** [comment]
That list isn't meant to be always up-to-date. I just made it during the wait for a hakchi2 update to keep people busy with something to discuss.

However I did recently edit the SFA2 entry to "TBA". That wasn't meant to be seen as "Working?=YES". Because it's not working yet, until I'm finished and release it.

**Comment by Drakonas** [comment]
This is not the place to be discussing compatibility with Nintendo's Canoe. That is out of the bounds of Hakchi. Use reddit or discord for that.
