### ISSUE TITLE
Disable rewind?

### ISSUE THREAD

**Issue by scabfarm** [ClusterM/hakchi2#591]
Is it possible to disable or lower the amount of rewind time from the Command line, and if it is possible, will it help save space on save files? (I'm guessing rollback-snapshot-period 600 might be rewind time but maybe I'm wrong?)  Thanks!

**Comment by K4Z1** [comment]
If you use all 4 save slots on each of the original 30 games, and each save uses 2 MB (with rewind) ....that would be 240 MB. I wonder how that even works for the original unhacked SNES mini...

Anyway, Super Street Fighter II won't let me create proper savestates (in retroarch, because the game doesn't work normally), can't overwrite them, and when I load it, it just resets the game. I'd LOVE to disable the rewind function... or just use retroarch save/load function, but I can't make it save after changing games :<

**Comment by DecanFrost** [comment]
Here is an idea.  If we rewrite the Snes kernel with the nes mini kernel. We woulf have all the same features MINUS the rewind feature and full compatiblity with all games.   Also this method would give us alot more free space. .. nes kernel uses less pace due to no rewind feature

**Comment by Drakonas** [comment]
DecanFrost what you're asking for would be a headache for the developers and end users, not really realistic. @scabfarm that rollback-snapshot-period is the rewind time yes.
