### ISSUE TITLE
SNES C8: an error has occurred launching games

### ISSUE THREAD

**Issue by Cayde510** [ClusterM/hakchi2#611]
Hey guys, I keep getting "C8: an error has occurred" message every time I go to launch the games I have added. 

Here's the process I did:

1. Dump file
2. Flash Original Kernel
3. Flash Custom Kernel
4. Installed the necessary mods
5. Changed folders to custom 30 max
6. Added Games
7. Sync and installed games.

Please let me know if I messed up on any process and what I can do to get rid of this message to play the added games. Thanks!

**Comment by Drakonas** [comment]
What mods did you install? And where did you get them?

**Comment by Cayde510** [comment]
I installed the modules retroarch, gambatte, glupen64, mame2003, snes9x2010. Modules came with the hakchi 2.20 version.

**Comment by Drakonas** [comment]
You mean the ones that came separately from the separate github listing listed on the Hakchi2 release page? If so, then that shouldn't be the issue. How many games did you add? The maximum size you can add to the SNES Mini is 252MB including the mods and games. Unchecking the roms in the Original Games listing does not remove them, only hides them. Commonly, C8 errors on everything is due to adding too much to the console.

**Comment by Cayde510** [comment]
I added around 30 games. But when this happened I started over on a clean slate and only tried adding 5 games and it did the same thing. I have around 127 mb of space to spare.

**Comment by Drakonas** [comment]
How are you adding the games? Does any popup occur when adding? You need to be installing games that have the .sfc/.smc extensions, already extracted.

**Comment by Cayde510** [comment]
yes. I’m adding games with extensions with .sfc/.smc already extracted. I gave up and now I’m trying it the web installer way. Will update.

**Comment by Cayde510** [comment]
Update. For some weird reason the web installer way worked. But some games take me back to the menu.
