### ISSUE TITLE
[Feature Request]  Command Line for Original 21 games.

### ISSUE THREAD

**Issue by HowardC** [ClusterM/hakchi2#622]
Since Overclocking Star Fox and it's Sequel works really well, but corrupts other SFX titles, it'd be nice to be able to set individual command line options for the 21 stock games.

**Comment by zimmertr** [comment]
+1

**Comment by gnadenlos** [comment]
Yes, please add them as single games instead of one "21 games" container. This would also help for future improvements like linking to the original files instead of copying them. If they are separate we could handle some games differently.

**Comment by Drakonas** [comment]
This is impossible as the original games cannot be modified. They are read-only. You can, however, make duplicates of them by copying them from FTP using Hakchi's FTP feature, and then hide the original games. They are in /usr/share/games. However this means you will be using twice the space because the game will be duplicated.
