### ISSUE TITLE
Is retroarch installed automaticly in the new version of hakchi? And do i have to add anything to the commandline?

### ISSUE THREAD

**Issue by JPVDO** [ClusterM/hakchi2#649]
Do i still have to add -retroarch to the commandline in this version of Hakchi?
And do i still need to install Retroarch separately?

I am trying to play street fighter alpha 2 and my commandline has changed to:
/bin/snes /usr/share/games/CLV-U-XIAVZ/Street_Fighter_Alpha_2_(E)_[!].sfrom.7z

Am i correct that no emulator has been defined?

Other games look like this:

/bin/clover-canoe-shvc-wr -rom /usr/share/games/CLV-U-YWUYC/Super_Adventure_Island_(Europe).sfrom.7z --volume 100 -rollback-snapshot-period 600

**Comment by Asure** [comment]
You need to add 'retroarch_with_cores' to your device.
Download it from https://github.com/ClusterM/retroarch-clover/releases
Then power up the mini, and run Hakchi2. 
Then drag the zipfile onto the running Hackhi2 window. 
It will install and enable the command lines for use. Without it, the games will C7/C8 since they cannot find /bin/snes.

**Comment by JPVDO** [comment]
Thanks! it works!
