### ISSUE TITLE
kirby dream land 3  sram issues

### ISSUE THREAD

**Issue by nekonall** [ClusterM/hakchi2#677]
odd error where the game will only write if you make a savestate , exit and then load the state.. im not much with code but this is one of my favorite games .. so could someone plz look into this

**Comment by IkoMattorr** [comment]
Hi, it's my favorite game as well!
Well, I used the Japanese version of the game on my console and it saves correctly (it seems), but the transparency problem makes the game unplayable when there is water or other stuff in the foreground.

The only difference between the USA and the JP versions (besides the title screen) is the text during the credits, that's written in Japanese, but on the other hand it has a nicer font (that's why I usually prefer the Japanese version over the USA one).

I'd like this game to be fixed in some way, or at least it would be nice if it was possible to disable the foreground layer, the game would look uglier but at least it would become fully playable.

**Comment by nekonall** [comment]
the us rom im using has no transparency issues or slow down im at world 2-4.. its just i have to do alotta work to save it lo...l  make save state... load save state etc

**Comment by OliverUlm** [comment]
Are you running the game using the built in emulator or RetroArch? I have issues with saving SNES games in Retroarch as well. However the snes9x 2010 core has a mention of save issues in it's description.

**Comment by IkoMattorr** [comment]
I'm using canoe, not RetroArch, and I suppose nekonall also is using canoe since RetroArch has slowdown issues with the game but it should fix the save issue.

That's interesting, on a different site I got another report of another user who has no transparency issues, so it's possible that:
-USA rom, save issues
-JP rom, transparency issues
the google docs list says that the game has both issues, but apparently the issues are separated into the two versions of the game... this or 2.21 fixed the transparency, I have to test.

Maybe it's possible to fix both roms by studying what causes the issues in the 2 different roms and patching them...

**Comment by nekonall** [comment]
yes im using canoe ... i tried the retroarch but still had the issue with saving and a slow down with multiple eniemies on screen.. i know cluster can fix it he just needs to see this thread ..

**Comment by Drakonas** [comment]
Change the preset ID to A210 (ctrl+alt+e) to fix trasparency issues.
