### ISSUE TITLE
Arcade roms are not working

### ISSUE THREAD

**Issue by From90th** [ClusterM/hakchi2#682]
MAME arcade roms are not working, black screen for a while then it goes back to menu. Used 0.78 MAME roms, as it said in retroarch documentation. Roms i was trying to use are Ghouls'n Ghosts and Metal Slug 1. Does anyone have a such problem?

**Comment by ArieKindicator** [comment]
I don't know about 0.78 MAME rom reference set, but FB Alpha v0.2.97.39 Non-Merged roms are running just fine. Final Fight, Rainbow Island, Metal Slug (with bios roms [neogeo.zip] installed in the game directory; required for every neo geo rom).

Edit: tested Road Fighter (Mame 0.78, and not part of FB Alpha set): doesn't run, black screen. Identical to yours. 

-----
Question. Is it possible to add a symlink in a neogeo game directory that symlinks to the neo geo bios [neogeo.zip], and the bios files need to be installed once instead of adding them to every neogeo game directory. I.e. install and symlink to neogeo.zip in "\user_mods\etc\libretro\system"

**Comment by From90th** [comment]
Thanks for you testing MAME! I need it for me for just one game - Ghouls'n Ghosts (Arcade version). Non-merged? Do you mean there should be only one file in rar archive, or it should be even non-archived file with some kind of extension, like iso, for example?
Very tired in finding of these game roms, probably need to be satisfied by smd version)))

**Comment by ArieKindicator** [comment]
Tested ghouls.zip (MAME and FBA) doesn't run but ghoulsu.zip FBA does but MAME doesn't. Search fb alpha v0.2.97.39. First hit.

**Comment by ArieKindicator** [comment]
ghouls (MAME and FBA) doesn't run but ghoulsu (FBA) does.
