### ISSUE TITLE
someone plz fix sram in kirby dreamland 3 

### ISSUE THREAD

**Issue by nekonall** [ClusterM/hakchi2#784]
i had posted about this previously .. has anyone got it working yet????? can you look into it cluster??? basically you cant save the game for some reason .. i have already tried multiple roms and retroacrh doesnt fix it

**Comment by ClusterM** [comment]
ROM version, hakchi2 version?

**Comment by nekonall** [comment]
using kirby dreamland 3 .sfc as it has no transparency issues and hahchi 2.21b because i overheard the newer update to d was causing problems for some.. the game runs smooth off canoe but the only way to get the file to save is to make a save state on exit and then load the state ... once done it will show your progress when you select a file to play...

**Comment by IkoMattorr** [comment]
Hi, I already wrote this on a different thread, but since ClusterM replied I'll write it again.
I tried the Japanese version of the game (Hoshi no Kirby 3) on my EUR SNES classic mini (using canoe) and it was able to save correctly, but I had the transparency issue.
So I wonder if it's possible to look into the USA and JP roms and see what causes/fixes the issues in both of them.
If the USA version can't save but the JP can, maybe it's possible to copy a part of the HEX of the JP version and paste it into the USA version in order to make it save as well, and maybe the same could be made for the transparency in the JP version... Though I don't have much experience in modding roms so I'm not sure what I'm suggesting is possible at all.

I used Hakchi2.20, not the most recent version, not sure if that may have influenced anything.

**Comment by Drakonas** [comment]
We need more details from the OP, but they haven't responded. The moral of the story is to buy the region of the SNES Classic you plan to play games from. This isn't a hakchi limitation but a Nintendo firmware limitation. Japanese Super Famicom Classic has different compatibility from the EUR and American SNES Classics. Closing this ticket until further notice. If anyone has trouble running a normal rom on EUR/USA SNES Classic this is a Canoe limitation, not Hakchi. This does not belong in a Hakchi issue submission.

**Comment by Drakonas** [comment]
Change the preset ID to A210 (ctrl+alt+e) to fix trasparency issues.
