### ISSUE TITLE
Custom Font Not working

### ISSUE THREAD

**Issue by Shreddiebean** [ClusterM/hakchi2#8]
Hello, I can't seem to get the custom font feature to work on my NES mini (I have an NTSC version). I updated the application, seeing that it was updated, and noticed that a custom font feature was added, fixing previously invisible characters from being, well, invisible. I made sure that it was enabled, and I installed the kernel multiple times on my system but to no avail. I'm hoping you see this and, hopefully, provide a solution.

**Comment by ClusterM** [comment]
Hi.
Did you make sync? Custom font installs during sync, it's not inside patched kernel.

**Comment by flycartier** [comment]
Best of luck , this is an amazing tool.. Worked for
Me with the 2.6 like a charm smooth sailing .. I just started adding any games cause I was running out what I used to play.. What site is everyone getting their games from ?

**Comment by Shreddiebean** [comment]
Yes, I have synced,. multiple times.

**Comment by ClusterM** [comment]
Please download special debug version: https://github.com/ClusterM/hakchi2/releases/download/2.10/hakchi2_debug.exe
Do all steps and sync again.
If you still has some problems do the following steps:
Archive the whole hakchi2 folder back (it should contain "temp" folder and "debuglog.txt" file.
Send it to me: clusterrr@clusterrr.com
I'll investigate it

**Comment by Shreddiebean** [comment]
As of the latest update, it is working fine! Thanks for the assistance!

**Comment by ClusterM** [comment]
Re: [ClusterM/hakchi2] Custom Font Not working (#8)


Hi.

Sorry for long answer. There are many sites with ROMs. Just google them.





Best of luck , this is an amazing tool.. Worked for
Me with the 2.6 like a charm smooth sailing .. I just started adding any games cause I was running out what I used to play.. What site is everyone getting their games from ?
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.




-- 
С уважением,
 Алексей                          mailto:clusterrr@clusterrr.com
