### ISSUE TITLE
#C8 error in miniNES + hakchi2 v2.21d (internal version 2.0.21.50)

### ISSUE THREAD

**Issue by fpmpaolo** [ClusterM/hakchi2#813]
Hello folks. I recently updated my miniNES with 117 NES games, all in home page, but when I try to load one I have this issue.
These are only NES games: no console, no SNES, only .nes files.
Should I divide them in folders? 
Is it a .png files problem?
Thanks

**Comment by Robo-1982** [comment]
Devide into folders.

**Comment by ghost** [comment]
> But the shell is designed to show only 30 games and there are some issues with other numbers of games:

> The thumbnail bar at the bottom of screen can show only ~45 covers. Other covers will be drawn beyond bounds of the screen.
The shell can show up to ~90 games on NES Mini and only ~50 games on SNES Mini without glitches, otherwise you'll get some C8 errors.
Having too few games causes problems, too. There are should be at least 12 games in the menu to show them without glitches. Version 2.11 introduces a folder feature to avoid those problems. It's recommended to split you games in folders to show only 30-40 games per screen.

https://github.com/ClusterM/hakchi2/wiki/FAQ

Robo is right. You are more than likely running into the error because you are displaying too many games on screen at one time. The shell, the interface for the Classic, is designed to show a set number of games. If you try to display more games on screen than the UI is designed for, you risk running into a C8 error.

**Comment by ledste** [comment]
I did many test this summer with my mini NES and the limit with full functionality and good display is 40 each folder, don't go over them. ciao!

**Comment by PushkaCom** [comment]
I'm not sure what I was doing wrong - but I attempted to use hakchi/retroarch multiple times reading multiple guides and youtube videos - and either nothing happened and it was stock snes, or boot to C8 error - nothing working

This happened one time where I just added 1 snes game, retroarch and the snes module... I thought I was going crazy, how can 1 game cause a memory issue?

one thing I didn't read in any tutorial was - set up normally, but select "uninstall modules" - check all the modules - uninstall them all, then install modules and add them again - then magically games would add, no more errors, music hack worked...

**Comment by Drakonas** [comment]
@fpmpaolo Has this issue been resolved? Please close this ticket or respond if so.
