### ISSUE TITLE
Ryzen System Issues (but also intel?)

### ISSUE THREAD

**Issue by unshavendillon** [ClusterM/hakchi2#825]
I know that everyone knows that Ryzen systems have some particular issues with writing to USB during the flashing process.  Here is what had happened to me and what I've observed.

-  USB 3.0(1) is the only way for me to get the system to even pick up on the SNESC
-  Dumping the kernel is fine, but flashing the system is when things get messy. 
-  I can flash the kernel within it's own process (not syncing) in both 2.20 and 2.21, but it immediately 
    fails to flash it again when I sync the games.
-  Every time it fails flashing I've noticed that the SNESC sneakily unmounts itself and I can see the power 
    indicator come back on right before it says that it can't write to USB.
-  Only have one other PC (laptop) in the house.  Is an Intel, has USB 3.0, still doesn't work.

Hope this little info may help determine a fix.
Attached my Ryzen DXDIAG as well

[DxDiag.txt](https://github.com/ClusterM/hakchi2/files/1385831/DxDiag.txt)

**Comment by joetheuseless** [comment]
Same issue! i noticed there is sometimes some delay on the Snes Mini when its connect to the computer sometimes the power indicator will flash sometimes it will not.. Even though its still functioning in Device Manager i have tried all the USB available in my computer but its still an issue USB  3.1 ''3.0'' 2.0 it has something to do''' AMD USB eXtension controller Host controller '' in Device manager and because all the USB devices are being powered by the board itself..There is no way for me use another USB or any USB powered by Ryzen i have done so much troubleshooting the past week its unreal i know the creator is really busy with bug fixes i just hope a fix is released to address the issues where having :)

**Comment by ghost** [comment]
I had success with kernel related operations / flashing at first on most ports but I couldn't do anything related to NAND dumping on my Intel system. I have 16 USB ports on my motherboard / front panel. Only the USB 3.1 Gen 2 Type A port on the rear of my board would dump the NAND. Only four USB 3.0 ports could dump NAND-B and NAND-C. My Intel based laptop couldn't dump the NAND at all. Perhaps it's a controller issue? Have you tried dumping your NAND too?

Download the debug version of Hakchi from here https://github.com/ClusterM/hakchi2/releases and use the features that aren't working correctly for you, it will create a debug.log in the Hakchi2 debug directory. Zip up the Hakchi2 debug version folder and send it to:  clusterrr@clusterrr.com

It's either help out or try every port on your system or maybe a powered USB hub for joetheuseless? I'm sorry if this isn't great advice but this is early days and there are others with the same or similar problems, I would imagine this issue will be identified and fixed soon.

**Comment by Drakonas** [comment]
I know this may be a given, but have you guys tried updating your bios's for Ryzen? There have been issues like these fixed in the past for Ryzen by a BIOS update.
