### ISSUE TITLE
No added games work!

### ISSUE THREAD

**Issue by clubbedmink** [ClusterM/hakchi2#839]
I must be doing something wrong. I added 50 or so games and they all go to black screen and then back to the games menu. Any help would be aprecieated

**Comment by hoderer** [comment]
this is an issues board. please ask these kind of questions here:

https://gbatemp.net/threads/hakchi2-nes-mini-very-simple-pimp-tool.456256/

and add a little more information about how you did it. more information = better chance to get help.

**Comment by schaudhr** [comment]
I am having the same issue....anyone have a resolve for this?

I dragged over the 200 or so ROMs and when playing the system the original 20 games work, but everything else I added does not.  Just goes back to game select screen.

**Comment by DecanFrost** [comment]
Did you install retroarch and snes9x2010 hmods ?

**Comment by schaudhr** [comment]
I installed retroarch. I didnt Install the snes9x2010 mods but I thought those were already on Hackchi2.21d?

{PRIVATE INFO REDACTED (@Drakonas)}

**Comment by ClusterM** [comment]
Can you make NAND-C dump and send this dump to me?

**Comment by Rustythesnowman** [comment]
I am also having the same issue working added games. 
I have tried both hackchi 2.2.b and 2.2d with no joy. I have follwed vids on you tube but the games appear in the list but do not load when you click on them.

**Comment by warlockv2** [comment]
Why would you put your buisness signiture in your post lmao

**Comment by moltke44** [comment]
Same error with the single oddity that the first added game did and continues to load up fine. None of the others will work and just give a quick black screen and back to the menu. I have around 50 games set up in a couple folders. Box art all shows fine, and again the first game I choose at random works but no other added. The originals still work.

**Comment by Drakonas** [comment]
All of these can be fixed by making sure you limit how many roms you install, only install mods you really need, install the snes9x AND retroarch mod for other SNES games (REQUIRES BOTH to be installed), and only having a limit of 60 games shown in one folder at a time. I also advise against installing the extra_space mod when having a large amount of games, as it limits the savestates storage to a total of 50MB, which is not enough with large amounts of roms. @clubbedmink please respond if your original issue was resolved, and close this issue if that is so. This is not a forums. Ask about issues related to rom setup and such on the forums or on the nintendo classics discord. This is for bug submissions and feature requests only.

**Comment by Drakonas** [comment]
@clubbedmink are you still having issues?

**Comment by moltke44** [comment]
Grab roms from another source, my first group did same thing.

**Comment by Drakonas** [comment]
how much space do you have free?

**Comment by clubbedmink** [comment]
So I must have got some bad roms. It is up and going now. Thanks for all the responses

**Comment by clubbedmink** [comment]
So I must have got some bad roms. It is up and going now. Thanks for all the responses
