### ISSUE TITLE
Are games like Star Ocean ever going to be supported by hakchi2 or does it need Retroarch?

### ISSUE THREAD

**Issue by Tshakka** [ClusterM/hakchi2#843]
The title says it all. As i heard that games like Star Ocean and Tales of Phantasia are using a special graphic chip that may not be supported by the SNES Mini classic emulator, is that true? 

And does it mean in the end that it will most likely never going to run on hakchi2 without RetroArch?

ty in advance.

**Comment by Drakonas** [comment]
Please refrain from using the issue tracker for general questions. Use the Nintendo Classics discord for that. This is meant for bugs or feature requests only.

To answer your question, Star Ocean is 99.9% impossible. Street Fighter Alpha 2 was a rare case being able to be patched for Canoe, because it only used the custom chip it required for use with encrypting the graphics as some form of anti-piracy I believe. A bypass was able to be bypass the encryption thus not requiring the custom chip. Star Ocean, however, uses the custom chip for actual features that cannot be done without the chip, such as (I believe) the voice clips in the cutscene at the beginning of the game. Retroarch will most likely be the only way to play that game. Tales of Phantasia, remains to be seen why it does not work, but my guess is it is also because of the voices in the game. It's not like Retroarch doesn't play the game perfectly anyway.
