### ISSUE TITLE
[Feature-Request] Fifth invisible save state to backup in-game progress?

### ISSUE THREAD

**Issue by sweetpalma** [ClusterM/hakchi2#844]
**Preamble:**
I started playing Super Metroid and made a suspend point in first five minutes of gameplay, just to test this feature. After that I only used vanilla in-game saves for better authenticity and it worked great. After playing a decent period of time I've accidentally loaded that almost blank save point (derp) - and BAM!!! All my progress is lost.

Is it possible to store "vanilla" in-game save separately from save state ones, so they will not get overwritten in situations like this? That would be a great feature that will save much nerves.

**Comment by Drakonas** [comment]
Unfortunately this is not possible because of how savestates are designed. Emulators have always worked this way. If you load a savestate in any emulator, you are loading that game's instance when that savestate was made into memory, and thus the emulator will save any progress from that point over the main savedata. If you're going to load a savestate, make a backup savestate first. There is no way to extend the amount of savestates the system has.
