### ISSUE TITLE
Black screen with menu music...??!!

### ISSUE THREAD

**Issue by JustInsane360** [ClusterM/hakchi2#855]
Today, I downloaded the latest version 2.21d. I also added a couple extra cores to get some arcade games to play. Like a dummy, I forgot to set up the folders and had 175mb of arcade games checked and accidently synchronized the games...only the arcade games. I didn't wipe it before doing so either. Right now I have a black screen and the menu music plays in the background. I've tried to reflash with my kernel and uninstalling hackchi....nothing. I even found a stock kernel and tried that with no luck. It does show that it's shutting down when I turn it off. Is there a fix for this? Any direction would be helpful.

**Comment by djritz0** [comment]
Picture will come on after about 30 secs.

**Comment by JustInsane360** [comment]
I left it on for about 10 min last night while I tried to figure out a fix. I'm not 100% familiar with the nand files, but I did see some people were able to add the whole SNES mini interface to the NES classic by dumping the nand onto it. Anyway to just replace the one on the SNES?

**Comment by Drakonas** [comment]
@JustInsane360 uninstall hakchi, flash og kernel, then perform factory reset from the SNES Classic main menu (which will unfortunately erase your saves. You can try to back them up with Hakchi2 Savestate manager built into hakchi prior to uninstalling hakchi, if it works at all)

This is a full reset. Without the factory reset from the SNESC main menu, Hakchi residual files are left on the system, which may be causing your problem.

**Comment by Drakonas** [comment]
@JustInsane360 has this been resolved?

**Comment by JustInsane360** [comment]
No. I ended up replacing my unit. I think it could have been the cores that I added to it. Still not sure what the remedy could be. After uninstalling hackchi2 and flashing original kernal, still nothing.

**Comment by Drakonas** [comment]
I guess it's too late now, but the main piece of the puzzle is to factory reset after uninstalling and flashing og kernel. without that the problems usually persist. Problems like that are usually due to files left over from old/bad hakchi installs. The only way to remove them is the factory reset AFTER a uninstall and OG kernel flash. Older Hakchi versions were very alpha for the SNES Classic and left some files on the system between updates that caused a lot of problems for people that never factory reset after those early versions. No matter I suppose, since you've replaced it. Closing this.
