### ISSUE TITLE
You’re doing an awesome job.

### ISSUE THREAD

**Issue by Xavali** [ClusterM/hakchi2#858]
Thank you very much for everything you’ve done for us. I know everyone just complains about what isn’t working correctly, but we all appreciate the effort you’ve gone to. I hope you keep the great work up. Thanks again for what you’re doing for everyone and good luck with the future

**Comment by Shoothimnow** [comment]
I created an account just to say I laughed pretty hard at this.  

"I know everyone just complains about what isn't working correctly..." - This isn't Reddit...  This is the **issues** section to remove bugs.  People are not complaining... they are helping Cluster improve his program so that it is easier to use.

**Comment by JeffSeverino** [comment]
If you're really thankful, would be nice to donate to ClusterM for all his work instead of doing this. Even being for a good reason, posting things like this here kinda pollutes the issues board. Most people are asking about emulation and even where to find ROMS...

**Comment by hoderer** [comment]
You're right. Writing is one thing, but "doing" is another. I just donated 20 bucks a few days ago and it feels good. It's nice to write something like this, but it's actually kinda 'not the right place'.
