### ISSUE TITLE
problem from the message: Access to the path "music.wav" is denied

### ISSUE THREAD

**Issue by felipe2345rr** [ClusterM/hakchi2#864]
i tried to change the music of the nes mini and didnt work so i tried to put the original music.wav,so later i tried to put super mario land 3 but in the start of the process it says Access to the path "music.wav" is denied everytime, i was so dumb to deinstall hakchi2 that i delete the original kernel ._. .... so i install the portable version make another copy of my kernel but it give me the same error Access to the path "music.wav" is denied, what can i do? pls i need help

**Comment by felipe2345rr** [comment]
and sorry for bad english

**Comment by Drakonas** [comment]
If you have deleted your original kernel, dumping the kernel will dump it in a non-original state. You need to search the internet for an untouched original kernel for your region SNES Classic. That's why we always stress to keep your Original kernel. Keep backups next time. We can't provide a link to one here, so don't ask.

**Comment by Drakonas** [comment]
And no worries on the bad English. :-) I understood ok.

**Comment by Drakonas** [comment]
@felipe2345rr was this ever resolved?
