### ISSUE TITLE
Access to Path ".\..\busybox" is denied

### ISSUE THREAD

**Issue by VAsHachiRoku** [ClusterM/hakchi2#867]
When trying to run the first synchronization requires updating the kernel. Followed all the steps and after the kernel dump, the next step it fails with this error below.

C:\User\me\AppData\Local\Temp\hakchi-temp\kernel\initramfs\bin\busybox' is denied.

Windows 10 Pro 1709 x64
Windows Defender for AV
RunAs Adminstartor on hakchi2

When I browse the path to look at the busybox properties and clicking on security tab, another warning is displayed:

The permissions on busybox are incorrectly ordered, which may cause some entries to be ineffective.

Permission are:
NULL SID = Special
Everyone = Read, and Read & Execute
Account Unknown (S-1-xxxxx) = Full Controller

Not sure, but seems like AppData is not a good place. Any reason this isn't under C:\Program Files (x86) instead?

**Comment by Drakonas** [comment]
Yes, because the program files folder is not a good place for a program data like hakchi's data files, or else file writing errors will occur more often. (Windows 7+ locks down writes to the Program Files folder, and programs with advanced drivers do not like this) Thus only the program is stored there. However, as much as ClusterM recommends the web installer, the zipped version works best from our experience on the Nintendo Classics discord. Try that. But you'll want to copy your dump and games_snes folders over from the AppData folder. DO NOT COPY ANYTHING FROM PROGRAM FILES.

**Comment by Drakonas** [comment]
Please respond if this was resolved or not.
