### ISSUE TITLE
Randomly crashes

### ISSUE THREAD

**Issue by djritz0** [ClusterM/hakchi2#892]
This is an ongoing issue. It randomly crashes to the main screen during gameplay. But before it gets to the main menu, it goes thru some sort of loop where it tries to restart. Eventually gets to main menu, but after a couple minutes. This also happens when you try to soft reset. I've asked about this issues a few times. Is there a resolution @clusterm ?

**Comment by Babbonz** [comment]
Yep as before I also get the same issues on mine now and again

**Comment by MrPokemon270588** [comment]
I have the same problem. Primary on SEGA games. First black screen, then some boot loop a few times, then work again. Hakchi 2.21d. Maybe some power supply problem.

**Comment by Drakonas** [comment]
As @MrPokemon270588 guessed, this is usually due to using a usb port on a computer that isn't providing enough power. Try a different port or plugging directly into a wall adapter when not needing to add games from your computer.

Also you should avoid using TV/monitor ports, USB hubs, or game console ports as they will most likely not provide enough power to the mini.

**Comment by Drakonas** [comment]
@djritz0 are you still having problems with this?

**Comment by Drakonas** [comment]
Closing this as the OP has not responded.
