### ISSUE TITLE
[NOT WORK] I have an idea for hakchi, improve the tool: "Make a screenshot"

### ISSUE THREAD

**Issue by TechnoSurYoutube** [ClusterM/hakchi2#914]
Hello,
After hacking my Snes Mini and seeing hakchi options and tools, I came across "Make a Screenshot"

Here is my idea, why not improve this option to allow to play the Snes Mini from his computer?

This is just an idea, I do not force anyone to add this tool but it would still be really cool :)

That's all for now =)

TechnoSurYoutube

PS: I have used Google Translate because I am French, sorry

**Comment by Drakonas** [comment]
Because USB cannot handle that kind of data throughput. It's too much data at one time to send through the cable. The SNESC uses USB 2.0, not 3.0. 3.0 would be fast enough, but the port on the SNESC itself is 2.0.

Not only that, but the SNESC would not be able to send video output to two sources at once. That would basically lag the heck out of everything to be doing that. (Because even if you have the HDMI cable disconnected it is still processing the video for that port)
