### ISSUE TITLE
MD5 checksum error

### ISSUE THREAD

**Issue by dav333** [ClusterM/hakchi2#922]
I have the same Kernel dump error as many on my US SNES.

 I was using 2.21d and would get the following message when flashing the custom kernel:

Kernel dumped but the MD5 checksum is unknown:  5be67f86fb0b0aaa275cd730d8b40a91

 I upgraded to 2.21e and when flashing the custom kernel I got the following:

Kernel dumped but the MD5 checksum is unknown: ea5d1d9061bcc7d0c42374eca76eb611

I continued, and it appeared to complete the kernel dump.  It then told me I could upload my ROMs to the SNES Classic.  I clicked the upload button and immediately received the following Error message:

shell command "tar -xvC /" returned exit code 1: tar: can't open '._bin':
Read-only file system

Update:   A friend who had no issues hacking his SNES brought over his computer and hakchi2 program and had the same results with my SNES.  

 Since then I have uninstalled, factory reset, and flashed the original kernel  a few times but still get the same error when flashing the custom kernel.

At a loss as to what to do next.  Please advise.

**Comment by Drakonas** [comment]
It is because your kernel dump file is used to create the custom kernel image. You have corrupted your kernel file in the kernel folder, and need to redump the original kernel from an unmodded (as in never once hakchi'd) SNES Classic or find a dump elsewhere. Any SNES Classic you install the custom kernel on from that computer until you get a clean dump will have a corrupt kernel, which means games will be broken among other things. (or it just won't work entirely)

This most likely happened if you ever deleted the dump folder or made a new hakchi folder without copying the dump folder over, and hakchi dumped an already modified kernel from the SNES Classic to use to create the custom kernel from, which will 99% of the time result in failure.

You need to place an untouched clean dump in the hakchi2/dump folder and then uninstall hakchi and flash og kernel, then install custom kernel.

**Comment by dav333** [comment]
Wow.  That worked.  No more MD5 checksum errors. 

I get all of the way to Synchronize  selected games with NES/SNES Mini button.  When I click it.  I get the following.

Error message:

shell command "tar -xvC /" returned exit code 1: tar: can't open '._bin':
Read-only file system

I uninstalled and flashed the custom kernel twice and everything was smooth until it was time to synchronize.  Then I get no further.

**Comment by Drakonas** [comment]
Looks like this is a separate issue from your first it seems. Looks like one of your roms has an improper command line. Something may be saying /_bin/*** instead of /bin/*** from the looks of it.

If there are none I recommend uninstalling hakchi and initiating a full factory reset from the SNES Mini (erases all saves and residual data from bad/old hakchi installs) if you haven't since you got it working.

**Comment by dav333** [comment]
I've uninstalled and full factory reset about 4 times while attempting to make it work.  When that didn't work I unchecked everything but the Original Games and one other game.  I figure if one of my Roms has a bad command line then I should try one at a time.  (If having them in the games window but unchecked still effects the ability to sync, then I will start from scratch) Then I tried the same with a different game.  Then I tried with just the Original Games and nothing else.  

I still get the error message:

shell command "tar -xvC /" returned exit code 1: tar: can't open '._bin':
Read-only file system

I appreciate your help so far. Going to try to do it from scratch.

Update:  

I went back to version d to try a fresh start.  Uninstalled, factory reset, flashed custom kernel.  Everything worked great.  I added two games only and still got the the same error message. 

The really weird part is that my friend with the exact same dump (since I overwrote mine) is able to sync with his SNES.

**Comment by Drakonas** [comment]
@ClusterM @madmonkey1907  need you on this one. Should dav333 provide a NAND backup?

**Comment by dav333** [comment]
I hope so.  I've tried a few more times with the entire process and only get to the point of being able to synchronize, when the same error as above occurs.  I do plan to donate.  I even started from scratch again with a fresh download of the latest hakchi2 version, got a new ROM so there would only be one game.  Still get the same results.

**Comment by Drakonas** [comment]
You probably have a corrupted install. Seems like you need a full reset. Backup your saves while hakchi is installed (save state manager in hakchi menu), then uninstall hakchi from the hakchi menu, flash og kernel afterwards (if you get MD5 checksum errors then your og kernel dump is corrupted and you need to obtain an untouched one from an unmodified snes or from the internet), then after that perform a full factory reset from the SNES Classic main menu. THIS WILL ERASE ALL SAVES. Then you should go to your hakchi folder and delete all folders EXCEPT games_snes, user_mods, and dump (NEVER DELETE OR LOSE THE DUMP FOLDER). Then, download the latest 2.21f version released within the last hour, and extract it overwriting everything in your Hakchi directory. This will give you a fresh Hakchi setup, but your games are still there. Load up Hakchi, flash custom kernel, and reselect your games' checkmarks and resync your games.

**Comment by dav333** [comment]
Cool.  Will try tonight.  Thanks for your help.

**Comment by ClusterM** [comment]
Error message:

    shell command "tar -xvC /" returned exit code 1: tar: can't open '._bin':
    Read-only file system

Means that you hakchi2 install is corrupted and has some additional files for some reason.

**Comment by dav333** [comment]
It works.  I realize now what I was doing wrong.  I was using my Mac to download and unzip.  Then would pass hakchi2 to my fiance's PC.  Once I passed the zipped file over, unzipped, and opened it on her computer, everything worked.  Sorry to have wasted your time, although if there are others starting on the Mac and transferring to a PC, this is the problem. Your advice made it happen.  I am going to donate now.
