### ISSUE TITLE
Latest Hakchi2 stable version?

### ISSUE THREAD

**Issue by efgamer** [ClusterM/hakchi2#938]
This is related to the recent bug stated here:
https://github.com/ClusterM/hakchi2/issues/921

Ok. I know this is a question not a issue itself and shouldn't be here but I really need to know and no one better to answer this question than the developers themselves.

Is it safe to update to the 2.21e now? I have heard from some people that 2.21e received an update last night. Does the files from zip were updated as well?

**Comment by ShizCalev** [comment]
As I stated on Reddit to your previous inquiry, 2.21e is affected by that bug, as per the issue report you linked. The update to 2.21e from last night was fixing an issue with titles being sorted incorrectly.

**Comment by DanTheMan827** [comment]
If you want a fix without waiting for a full release, download [this file](https://busybox.net/downloads/binaries/1.21.1/busybox-armv7l) and save it in the `mods\mod_hakchi\bin` folder as `busybox` while replacing the original one.

Then you can either uninstall and reinstall hakchi, or use the "Boot patched kernel from RAM" option in hakchi2

This will also work with the webinstaller version if you can find the folder that hakchi is stored in, but any Hakchi2 update will replace the file.

It _is_ also possible to FTP it manually, but if you install any mods, I'm pretty sure it would get overwritten with the compressed one due to built-in repair/upgrade functionality.

**Comment by DecanFrost** [comment]
What does that feature do.. " Boot patched Kernal from ram" ?

**Comment by efgamer** [comment]
@DanTheMan827 May I have to download the 2.21e portable version, put the busybox file in the mods\mod_hakchi\bin folder and flash the custom kernel? Is that it?

I'm back to 2.21b.. is it worth to update to 2.21e or should I stay with 2.21b until the next release?

**Comment by Drakonas** [comment]
@efgamer he just said placing that file in the proper location fixes the bug that my issue (the one you linked) presented. @DecanFrost boot patched kernel from ram runs a custom kernel without actually installing it to the SNESC, so when you turn off the SNESC it is back to where it was before be it og kernel or your previous custom kernel.

**Comment by ghost** [comment]
Cluster just announced that this will be fixed soon.

**Comment by Drakonas** [comment]
@lich1708 @efgamer which is a good thing because the fix by DanTheMan827 breaks game demo mode. :/

**Comment by Drakonas** [comment]
Because this isn't really a bug report, I am closing this issue, but leaving the topic open for discussion.
