### ISSUE TITLE
King Arthur's World: only music, no sound, both normal command line and /snes retroarch

### ISSUE THREAD

**Issue by LeanderAT** [ClusterM/hakchi2#952]
King Arthur's World: only music, no sound, both normal command line and /snes retroarch

I only get music but no sound (enemy dies, bell is hit etc.). The in-game sound test in the options menu works...but the missions only have music. I loaded the rom normally and also in /snes mode, different core...but nothing works.

Any ideas?

**Comment by Drakonas** [comment]
You probably have a bad rom. This game is already confirmed working.

**Comment by LeanderAT** [comment]
It works in a normal SNES emulator for PC though.

**Comment by Drakonas** [comment]
emulators for PC are more updated to handle that. The cores that are coded for the SNESC are much older (try 7 years). This is because newer versions require more processing and run slower on the SNESC. Find a No-Intro version of your rom. This isn't something that should be reported in the Hakchi bug tracker anyway, as the rom is considered perfectly running by others. This is something unrelated to a Hakchi bug... Ask on the MiniSNESMods subreddit if you need help. You'll get a faster answer there anyway.

**Comment by LeanderAT** [comment]
Thanks!

**Comment by LeanderAT** [comment]
I think the problem is that the game is in Dolby Surround...and SNES Mini can only output stereo..,so you don't hear the sound samples.

**Comment by Drakonas** [comment]
Using the USA rom works fine in Retroarch for me. I hear death sounds and such.

**Comment by LeanderAT** [comment]
Tried different roms. None of them work. The EU version has normal graphics but the US version has some errors (the sky in level 1 for example). 

What settings do you use?

I use /snes .... -retroarch and have the SNES2002 core.

**Comment by Drakonas** [comment]
It's supposed to be /bin/snes and you don't use --retroarch unless you are using a module that allows running the SNES core through the canoe command line (/bin/clover-canoe-shvc-wr -rom) @LeanderAT

**Comment by LeanderAT** [comment]
It works now! It wasn't the rom but the in-game settings. After changing the in-game sound settings (surround on or off) both music and sound worked. :)

**Comment by LeanderAT** [comment]
Drakonas, help please! The game worked but then I deleted it...installed it again but it does not work anymore. I tried different roms, different settings...for 1.5 hours. :(

**Comment by Drakonas** [comment]
@LeanderAT It'd be easier for you if you asked on the [MiniSNESMods](https://www.reddit.com/r/miniSNESmods/) subreddit. I don't have any idea what's wrong.

**Comment by Logitude** [comment]
I have the same problem, and I think I figured out what's going on. The problem is not game-wide. It's with the song "Team Work". While that song is playing, you won't hear any sound effects, even in the sound settings screen. Try playing the "Team Work" song and then scrolling through the sound effects... nothing. Next try playing any other song besides the surround sound test and then scrolling through the sound effects... you'll hear each one.

The reason the problem seemed to go away after messing with the game for a while and return when you reinstalled the game is that the "Team Work" song is the song that plays during the training levels, which are the first levels in the game. When it started working for you, it must be that you advanced past the training levels and didn't realize that the particular song was the cause. Then when you reinstalled the game, you started over with the training levels again and encountered the same problem once again.

I leave this comment for posterity in the hope that it prevents at least some amount of baldness.

**Comment by LeanderAT** [comment]
Thank you! No, this is not the case. I gave up by the way. I only start the first tutorial level, listen if there are sound effects and then test a different ROM. I got it to work once but that's it. Still don't know why it worked once.
