### ISSUE TITLE
Massive Framedrops in Legend of Zelda PAL and the original ROM

### ISSUE THREAD

**Issue by Duveru** [ClusterM/hakchi2#969]
Hello!

I've massive framedrops in the game, when i'm fighting against more enemys. I'm using the PAL rom and i spoke with a friend and he has the same problems after hacking his SNES Classic mini. He told me that before Version 2.21d he had no problem with the original Zelda ROM but now he has the same issues. Can anyone confirm same issues or are we the only two person with this problem?

Btw. great and quick work! Thank you a lot! :-)

Thanks!
Duveru

**Comment by THE-PBV** [comment]
Stay on 2.21D thats the only stable version.

**Comment by Duveru** [comment]
thank's for the tipp. will flash the kernel back to 2.21D after a few tests.

today i tested 2.21f. i flashed the kernel again, synced the games with the snes classic mini and the framedrops are still there. when i'm surrounded by enemies, i will check the original legend of zelda rom, if there are any issues too.

okay, there's no workaround atm.? have anyone the same problems?

bb
duveru

**Comment by Drakonas** [comment]
Why don't you not use the PAL rom, because PAL roms are listed as unsupported for Nintendo's Canoe on the SNES Classic. The SNES Classic for both Europe and America use the USA library of game support, so only the American roms are guaranteed to work.

**Comment by ghost** [comment]
@Drakonas The SNES Classic does support many PAL roms. And why we want to use them sometimes: because we grew up the the version that has our native language (for me german). You wouldn't want to play the japanese versions only because the NTSC-U versions could be problematic, would u?

**Comment by JeffSeverino** [comment]
You have 2 solutions: Use retroarch, or patch the game with the translation (the NTSC version) and hope it'll work, instead of trying to make the console do what it can't naturally. Since the first version of hackchi which supports SNES, Cluster mentioned the incompatibility. Have some patience.

**Comment by Drakonas** [comment]
As @JeffSeverino said @Vogeluff, Canoe only supports North American roms as a standard. Some PAL roms will run, but most will not. If you have a problem with one, there is nothing that Hakchi can do to fix this. You will have to use Retroarch or look for a working NTSC patch. PAL games on the SNES ran at 50Hz, and NTSC games ran at 60Hz, which is the standard in both America and Europe today, so that is what they decided to focus on. This is a Nintendo issue, not a Cluster issue. Closing this ticket as the OP has not responded and this is not an issue regarding Hakchi.
