### ISSUE TITLE
Size reduced on SNES Classic (188Mo)

### ISSUE THREAD

**Issue by chris121278** [ClusterM/hakchi2#972]
Hello,

i've got an issue: the size available on my SNES Classic is now at 188Mo. Before it was much more, about 250 if i don't mistake.
I Flash the original Kernel but it doesn't anything.
Someone can help me?
Thanks

**Comment by Gab-75** [comment]
How many savestates did you make? You need to consider that each savestate requires about 2-2.2 MB of storage space...

**Comment by chris121278** [comment]
No save state.
But if I flash original kernel, it doesn’t reset all?
I think the  problem is that I deleted game from hakchi2 instead of uncheck it.
A way to find out the entire space ?

**Comment by Gab-75** [comment]
You can manage the savestates from hakchi2 savestate manager... in any case you can try with a "factory reset" (directly from your SNES mini)...

**Comment by chris121278** [comment]
Ok, I will chek it.
Factory reset from snes don’t work for this, already tried.
I ‘ll keep you informed.

**Comment by MrXCuci** [comment]
Are you using dualboot feature?

**Comment by chris121278** [comment]
Hello,

no, no dualboot feature.
No savestate. 188,6Mo total size available on my SNES Classic. I've read other person have the same mystake on french forum (I'm french).
Don't know what to do...

**Comment by Drakonas** [comment]
You probably used an old version of Hakchi2, and there are probably leftover files that won't be removed without a full factory reset. You need to uninstall Hakchi from the Hakchi menu, flash og kernel (making sure there are no MD5 checksum errors), then go to your SNES Classic main menu and perform a factory reset from the options menu on your SNES Classic. Then flash custom kernel, and you should have around 238MB total space. You won't have more unless you install the extra_space mod, but that is NOT recommended, because it limits the total space for save files to 50MB. (Save files use anywhere from 150KB to 2.4MB, so you need all the space you can get for saves)

**Comment by chris121278** [comment]
Hello Drakonas,

I did it. Flashed original kernel, performed a Factory reset from my TV, flashed custom Kernel. The size avalaible is now 199,1Mo. Strange, not at 238Mo.
Very strange...
At the begining, I extracted my Nand (about 500Mo). Can I do something with it?
Thanks,

**Comment by gBaH0JI9I** [comment]
@chris121278 
Do you have installed retroarch with modules?
I did the same than you and after flashing custon kernel the size of available memory was 237Mb.
Next step I installed retroarch with modules - the size was 198,5Mb.
I did this 2 times, the result the same. 
If you don't  need to launch sega, N64 games don't install retroarch and size of available memory will be around 237Mb otherwise the size will be 190Mb with ability to play other console games.
I think so.

**Comment by chris121278** [comment]
So, yes and no.
Yes, but after flashing original kernel, the size is about 200Mo.
I manage to install proper version of Hakchi2, and plug in a « Virgin » SNES Classic un ordre to see what happen.
If the size is ok, I will use the dump to flash back my SNES.
Hope it will work.
What do you think about it?

**Comment by gBaH0JI9I** [comment]
Are you uninstalled old hakchi2 installation before install og kernel?
I did three steps to make SNES virgin again:
1. Menu "Kernel" - "Uninstall"
2. Menu "Kernel" - "Flash factory kernel"
3. Go to SNES menu and factory reset.

To install hakchi2 after that:
1. Menu "Kernel" - "Flash custom kernel"
Thats it. After that the size is 237Mb (without installed retroarch).

**Comment by chris121278** [comment]
So,

I’ll try it ASAP. Thank’s a lot for your answer.

**Comment by chris121278** [comment]
Re,

@gBaH0JI9I: I've just done it. 
Eureka!
Thanks a lot, I've just not seen the Menu "Kernel" - "Uninstall".
The size available is right 237,5Mb, so much mort than before.

I think I would probably install Retroarch because some game doesn't work without.

Anyway Thank you all for your help!!!

**Comment by gBaH0JI9I** [comment]
👍
I am install only 
![default](https://user-images.githubusercontent.com/13234037/32195741-40071d02-bdcf-11e7-8990-92680c69cc42.png)
for Sega Genesis, Nes, N64 and Sega 32X. And after that I have 227Mb free.
Good luck.
