### ISSUE TITLE
Hackchi 2 on pc

### ISSUE THREAD

**Issue by Svears** [ClusterM/hakchi2#974]
When i download the installer, it gets removed by my virus scanner, is that normal?

**Comment by NoeleyC** [comment]
You'll either have to disable your virus scanner, or else add the file as an exception? I has bug problems with Norton but managed to get it working OK in the end. Another issue is that because of hakchi being updated regularly, virus scanners are more suspicious of them as the files are brand new and not registered on their databases. If you add the program as a trusted one, that will help

**Comment by Drakonas** [comment]
This is not a Hakchi issue, and thus should not have been asked here. Report the Hakchi program as a false positive (meaning falsely accused as a virus) to your Antivirus software. This is in their hands, not ours. For now you can add it as an exception to your antivirus.
