### ISSUE TITLE
Retroarch SNES core change request

### ISSUE THREAD

**Issue by efgamer** [ClusterM/hakchi2#982]
The Snes9x with no end year seems to be more accurate then Snes9x2010 as stated on the link below: 

https://wiki.libretro.com/index.php?title=Nintendo_SNES_Core_Compatibility#SNES9x_Next

Is it possible to change Retroarch Clover to come bundled with the Snes9x with no end year or even with the higan core (old bsnes) instead of the actual Snes9x2010 core? If not, is it possible to change the core myself?

**Comment by Arakon** [comment]
https://github.com/ClusterM/retroarch-clover/commit/165f2f2bf7c1a0389fe98df877f6d13c742c4960
That seems to be commited already and should be in the next release then.

**Comment by Drakonas** [comment]
Be aware @Arakon and @efgamer with more accuracy comes slower emulation. This core is not stable on the SNES Classic. Because it requires more processing, it runs most games at a cost of performance. Even Zelda Link to the Past romhacks run with audio skipping. 2010/2005 is more stable to run on lower end hardware. Newer SNES9x builds were built with more modern hardware in mind.
